(()=>{"use strict";
const D=window.QF_DATA,V=window.QF_V5,M=V.managers,MODES=V.modes,$=id=>document.getElementById(id);
const U={home:$("homeScreen"),lobby:$("lobbyScreen"),game:$("gameScreen"),final:$("finalScreen"),brand:$("brandBtn"),profilePill:$("profilePill"),profileBtn:$("profileBtn"),leaderboardBtn:$("leaderboardBtn"),leaderboardFinalBtn:$("leaderboardFinalBtn"),sound:$("soundBtn"),fullscreen:$("fullscreenBtn"),profileNameInput:$("profileNameInput"),saveProfile:$("saveProfileBtn"),profileSetup:$("profileSetup"),profileAvatar:$("profileAvatar"),profileNameText:$("profileNameText"),profileRatingText:$("profileRatingText"),profileLevelText:$("profileLevelText"),cloudChip:$("cloudChip"),modeGrid:$("modeGrid"),homeModeCount:$("homeModeCount"),selectedModeName:$("selectedModeName"),selectedModeDesc:$("selectedModeDesc"),createRoom:$("createRoomBtn"),soloStart:$("soloStartBtn"),joinCode:$("joinCode"),joinRoom:$("joinRoomBtn"),spectatorJoin:$("spectatorJoin"),lobbyModeTitle:$("lobbyModeTitle"),lobbyModeDesc:$("lobbyModeDesc"),roomCode:$("roomCodeText"),copyRoom:$("copyRoomBtn"),qrRoom:$("qrRoomBtn"),lobbyPlayers:$("lobbyPlayers"),lobbyCapacity:$("lobbyCapacity"),ready:$("readyBtn"),spectatorInfo:$("spectatorInfo"),modeSelect:$("modeSelect"),choiceSelect:$("choiceCountSelect"),maxPlayers:$("maxPlayersSelect"),contentSelect:$("contentSelect"),format:$("formatPreview"),teamTools:$("teamTools"),start:$("startGameBtn"),hostHint:$("hostHint"),hostControl:$("hostControlText"),modeRules:$("modeRules"),connectionDot:$("connectionDot"),connectionText:$("connectionText"),pingText:$("pingText"),gameModeIcon:$("gameModeIcon"),gameModeName:$("gameModeName"),gameContent:$("gameContentType"),matchClock:$("matchClock"),timerText:$("timerText"),timerBar:$("timerBar"),roundProgress:$("roundProgress"),scorePlayers:$("scorePlayers"),teamScoreText:$("teamScoreText"),progressBar:$("progressBar"),finalChip:$("finalStageChip"),roundStatus:$("roundStatus"),questionType:$("questionTypeChip"),optionChip:$("gameOptionChip"),teamALogo:$("teamALogo"),teamBLogo:$("teamBLogo"),teamAName:$("teamAName"),teamBName:$("teamBName"),relation:$("relationLabel"),answerGrid:$("answerGrid"),result:$("resultFlash"),feed:$("selectionFeed"),personalStats:$("personalStats"),winnerTitle:$("winnerTitle"),winnerSubtitle:$("winnerSubtitle"),ratingResult:$("ratingResult"),finalScores:$("finalScores"),awards:$("matchAwards"),again:$("playAgainBtn"),back:$("backHomeBtn"),toast:$("toast"),backdrop:$("modalBackdrop"),leaderModal:$("leaderboardModal"),profileModal:$("profileModal"),qrModal:$("qrModal"),leaderList:$("leaderboardList"),leaderStatus:$("leaderboardStatus"),profileModalName:$("profileModalName"),profileStats:$("profileStatsGrid"),badgeGrid:$("badgeGrid"),historyList:$("matchHistoryList"),qrCanvas:$("qrCanvas"),qrCodeText:$("qrCodeText")};
const PROFILE_LS="qf-v5-profile",HISTORY_LS="qf-v5-history",MODE_LS="qf-v5-mode",SOUND_LS="qf-sound";
let peer=null,hostConn=null,conns=new Map(),isHost=false,room="",me="",tickTimer=null,pingTimer=null,renderTimer=null,toastTimer=null,reconnectTimer=null,selectedMode=localStorage.getItem(MODE_LS)||"classic25",recordedMatch="",music=null,audio=null,sound=localStorage.getItem(SOUND_LS)!=="0";
let profile=loadProfile(),history=loadHistory(),S=blank();
const managerCards=buildManagerCards();
function safeJSON(v,f){try{return JSON.parse(v)||f}catch{return f}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function cleanName(v){return String(v||"").trim().replace(/[<>]/g,"").replace(/\s+/g," ").slice(0,18)}
function initials(v){return String(v||"QF").split(/\s+/).slice(0,2).map(x=>x[0]||"").join("").toUpperCase()}
function code(v){return String(v||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,8)}
function mkcode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",x=new Uint32Array(6);crypto.getRandomValues(x);return[...x].map(n=>a[n%a.length]).join("")}
function hostPeerId(c){return"quizfootball-v5-"+c.toLowerCase()}
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function loadProfile(){let p=safeJSON(localStorage.getItem(PROFILE_LS),{});return{profileKey:p.profileKey||uuid(),username:cleanName(p.username||""),rating:Number(p.rating)||1000,xp:Number(p.xp)||0,level:Number(p.level)||1,games:Number(p.games)||0,wins:Number(p.wins)||0,losses:Number(p.losses)||0,draws:Number(p.draws)||0,correct:Number(p.correct)||0,wrong:Number(p.wrong)||0,bestStreak:Number(p.bestStreak)||0,timedBest:Number(p.timedBest)||0,soloBest:Number(p.soloBest)||0,rankedWins:Number(p.rankedWins)||0,chillGames:Number(p.chillGames)||0,managerCorrect:Number(p.managerCorrect)||0,badges:Array.isArray(p.badges)?p.badges:[]}}
function saveProfileLocal(){localStorage.setItem(PROFILE_LS,JSON.stringify(profile));syncProfileUI()}
function loadHistory(){return safeJSON(localStorage.getItem(HISTORY_LS),[])}function saveHistory(){history=history.slice(0,30);localStorage.setItem(HISTORY_LS,JSON.stringify(history))}
function blank(){return{status:"home",hostId:null,players:{},settings:settingsFor(selectedMode),deck:[],roundIndex:-1,cycle:0,currentRound:null,options:[],selections:{},locked:false,winnerId:null,correctAnswerId:null,roundStartedAt:0,matchStartedAt:0,endsAt:0,matchId:"",teamScores:{A:0,B:0,coop:0},finishReason:"",awards:[],spectators:0}}
function settingsFor(id){const m=MODES[id]||MODES.classic25;return{modeId:m.id,roundCount:m.roundCount,optionCount:m.optionCount,timeLimit:m.timeLimit,content:m.content,rule:m.rule,rated:!!m.rated,chill:!!m.chill,solo:!!m.solo,maxPlayers:8,targetScore:+m.targetScore||0,scoring:m.scoring||"normal"}}
function mode(id=S.settings.modeId){return MODES[id]||MODES.classic25}
function shuf(a,r=Math.random){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function rng(str){let h=2166136261;for(const c of String(str)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return()=>{h+=0x6D2B79F5;let r=h;r=Math.imul(r^r>>>15,r|1);r^=r+Math.imul(r^r>>>7,r|61);return((r^r>>>14)>>>0)/4294967296}}
function buildManagerCards(){const out=[];for(const m of Object.values(M)){for(let i=0;i<m.clubs.length;i++)for(let j=i+1;j<m.clubs.length;j++){const A=m.clubs[i],B=m.clubs[j];if(D.teams[A]&&D.teams[B])out.push({id:`mgr-${m.id}-${A}-${B}`,kind:"manager",teamA:A,teamB:B,answer:m.id})}}return out}
function playerRound(id){const c=D.cards.find(x=>x.id===id);return c?{id:c.id,kind:"player",teamA:c.teamA,teamB:c.teamB,answer:c.answer}:null}
function makeDeck(content){const cfg=mode(),poolId=cfg.pool,allowed=poolId&&V.pools?.[poolId]?new Set(V.pools[poolId]):null,rand=cfg.daily?rng(new Date().toISOString().slice(0,10)+":"+cfg.id):Math.random;const allow=c=>!allowed||(allowed.has(c.teamA)&&allowed.has(c.teamB));const p=shuf(D.cards.filter(allow),rand).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards.filter(allow),rand).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out.length?out:[...p,...m]}
function resolveDeckItem(x){if(!x)return null;if(x.kind==="player")return playerRound(x.id);return managerCards.find(c=>c.id===x.id)||null}
function entity(kind,id){return kind==="manager"?M[id]:D.players[id]}
function key(kind,id){return(kind==="manager"?"m:":"p:")+id}
function fromKey(k){const [t,id]=String(k||"").split(":");return{kind:t==="m"?"manager":"player",id}}
function buildOptions(r,count=S.settings.optionCount){count=[4,6,8].includes(+count)?+count:6;const pool=r.kind==="manager"?Object.values(M):Object.values(D.players),answer=entity(r.kind,r.answer),rand=rng(`${S.matchId}:${r.id}:${count}:${S.cycle}`),safe=pool.filter(p=>p.id!==r.answer&&!(p.clubs.includes(r.teamA)&&p.clubs.includes(r.teamB))),near=shuf(safe.filter(p=>p.clubs.includes(r.teamA)||p.clubs.includes(r.teamB)),rand),far=shuf(safe.filter(p=>!p.clubs.includes(r.teamA)&&!p.clubs.includes(r.teamB)),rand),pick=[];for(const p of [...near,...far]){if(pick.length>=count-1)break;if(!pick.some(x=>x.id===p.id))pick.push(p)}return shuf([answer,...pick],rand).slice(0,count).map(p=>key(r.kind,p.id))}
function competitors(){return Object.values(S.players).filter(p=>p.active!==false&&!p.spectator)}function eligible(){return competitors().filter(p=>!p.eliminated)}function activeCount(){return competitors().length}
function snap(){return{status:S.status,hostId:S.hostId,players:S.players,settings:S.settings,deck:S.deck,roundIndex:S.roundIndex,cycle:S.cycle,currentRound:S.currentRound?{id:S.currentRound.id,kind:S.currentRound.kind,teamA:S.currentRound.teamA,teamB:S.currentRound.teamB}:null,options:S.options,selections:S.selections,locked:S.locked,winnerId:S.winnerId,correctAnswerId:S.correctAnswerId,roundStartedAt:S.roundStartedAt,matchStartedAt:S.matchStartedAt,endsAt:S.endsAt,matchId:S.matchId,teamScores:S.teamScores,finishReason:S.finishReason,awards:S.awards,spectators:Object.values(S.players).filter(p=>p.spectator&&p.active!==false).length}}
function screen(n){["home","lobby","game","final"].forEach(k=>U[k].classList.toggle("active",k===n))}
function toast(t){clearTimeout(toastTimer);U.toast.textContent=t;U.toast.classList.add("show");toastTimer=setTimeout(()=>U.toast.classList.remove("show"),1800)}
function send(c,type,payload={}){if(c?.open)try{c.send({type,payload})}catch{}}function broadcast(type,payload={}){conns.forEach(c=>send(c,type,payload))}
function sync(){if(isHost){broadcast("state",snap());render()}}
function destroyNet(){clearInterval(pingTimer);clearTimeout(reconnectTimer);try{hostConn?.close()}catch{}conns.forEach(c=>{try{c.close()}catch{}});conns.clear();try{peer?.destroy()}catch{}peer=null;hostConn=null}
function applyTheme(seed){const themes=["royal","aurora","midnight","emerald"];let h=0;for(const c of String(seed||"home"))h=(h*31+c.charCodeAt(0))>>>0;document.body.dataset.theme=themes[h%themes.length]}
function ensureName(){if(profile.username)return true;toast("Önce kullanıcı adını kaydet");U.profileNameInput.focus();return false}
function saveName(){const n=cleanName(U.profileNameInput.value);if(n.length<2)return toast("Kullanıcı adı en az 2 karakter olsun");if((location.hostname==="127.0.0.1"||location.hostname==="localhost")&&/QA$/i.test(n)&&!String(profile.profileKey||"").startsWith("qa-"))profile.profileKey="qa-"+n.toLowerCase()+"-"+uuid().slice(0,8);profile.username=n;saveProfileLocal();U.profileSetup.classList.add("saved");window.QFCloud?.ensureProfile?.({profile_key:profile.profileKey,username:n,rating:profile.rating,xp:profile.xp,level:profile.level,games:profile.games,wins:profile.wins,losses:profile.losses,draws:profile.draws,correct:profile.correct,wrong:profile.wrong,best_streak:profile.bestStreak,timed_best:profile.timedBest,solo_best:profile.soloBest,ranked_wins:profile.rankedWins,chill_games:profile.chillGames,manager_correct:profile.managerCorrect,badges:profile.badges});toast("Profil kaydedildi")}
function syncProfileUI(){U.profileNameInput.value=profile.username||"";U.profileNameText.textContent=profile.username||"Oyuncu";U.profileAvatar.textContent=initials(profile.username||"QF");U.profileRatingText.textContent=Math.round(profile.rating);U.profileLevelText.textContent=profile.level;U.profileSetup.classList.toggle("saved",!!profile.username)}
function renderModeTabs(group="competitive"){document.querySelectorAll(".mode-tab").forEach(b=>b.classList.toggle("active",b.dataset.group===group));const arr=Object.values(MODES).filter(m=>m.group===group);U.modeGrid.innerHTML=arr.map(m=>`<button class="mode-card ${m.id===selectedMode?"selected":""}" data-mode="${m.id}"><span class="mode-icon">${m.icon}</span>${m.rated?'<span class="rated-flag">RANKED</span>':""}<h3>${esc(m.name)}</h3><p>${esc(m.desc)}</p><div class="mode-meta"><span>${m.timeLimit?Math.round(m.timeLimit/60)+" DK":m.roundCount+" KART"}</span><span>${m.optionCount} SEÇENEK</span><span>${m.content==="manager"?"HOCA":m.content==="mixed"?"KARMA":"OYUNCU"}</span></div></button>`).join("");U.modeGrid.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>selectMode(b.dataset.mode,group))}
function selectMode(id,group){selectedMode=MODES[id]?id:"classic25";localStorage.setItem(MODE_LS,selectedMode);document.querySelectorAll(".mode-card").forEach(b=>b.classList.toggle("selected",b.dataset.mode===selectedMode));const m=MODES[selectedMode];U.selectedModeName.textContent=m.name;U.selectedModeDesc.textContent=m.desc;U.soloStart.textContent=m.group==="solo"?"Tek Oyuncu Başlat":"Tek Başına Dene";if(group&&m.group!==group)renderModeTabs(m.group)}
function populateModeSelect(){U.modeSelect.innerHTML=Object.values(MODES).filter(m=>m.group!=="solo").map(m=>`<option value="${m.id}">${m.icon} ${esc(m.name)}</option>`).join("")}
function hostRoom(){if(!ensureName())return;destroyNet();isHost=true;room=mkcode();applyTheme(room);let tries=0;const go=()=>{if(typeof Peer==="undefined")return toast("Çevrimiçi bağlantı kütüphanesi yüklenemedi");peer=new Peer(hostPeerId(room),{debug:0});peer.on("open",id=>{me=id;S=blank();S.status="lobby";S.hostId=id;S.settings=settingsFor(selectedMode);S.players[id]=newPlayer(id,profile,true,false);render();startPingLoop()});peer.on("connection",c=>wireGuest(c));peer.on("error",e=>{if(e.type==="unavailable-id"&&tries++<4){try{peer.destroy()}catch{}room=mkcode();return setTimeout(go,120)}toast("Oda bağlantısı kurulamadı")})};go()}
function newPlayer(id,p,host=false,spectator=false){return{id,name:p.username||p.name||"Oyuncu",profileKey:p.profileKey||p.profile_key||"",rating:Number(p.rating)||1000,score:0,correct:0,wrong:0,streak:0,bestStreak:0,fastest:0,managerCorrect:0,host,active:true,ready:host,team:"A",spectator,eliminated:false,ping:0,ratingDelta:0,placement:0,joinedAt:Date.now()}}
function wireGuest(c){c.on("data",m=>guestMsg(c,m));c.on("close",()=>dropPlayer(c.peer));c.on("error",()=>dropPlayer(c.peer))}
function guestMsg(c,m){if(!m?.type)return;const x=m.payload||{};if(m.type==="join"){const n=cleanName(x.name),previousEntry=Object.entries(S.players).find(([id,p])=>p.profileKey&&p.profileKey===x.profileKey&&id!==S.hostId),previous=previousEntry?.[1],spectate=!!x.spectator||(S.status!=="lobby"&&!previous);if(!n)return send(c,"reject",{reason:"Geçersiz kullanıcı adı"});const duplicate=Object.values(S.players).find(p=>p.active!==false&&!p.spectator&&p.name.toLocaleLowerCase("tr")===n.toLocaleLowerCase("tr")&&p.profileKey!==x.profileKey);if(duplicate)return send(c,"reject",{reason:"Bu kullanıcı adı odada kullanılıyor."});if(!previous&&!spectate&&competitors().length>=S.settings.maxPlayers)return send(c,"reject",{reason:"Oyuncu kapasitesi dolu. Seyirci olarak katılabilirsin."});conns.set(c.peer,c);let p;if(previous){if(previousEntry[0]!==c.peer)delete S.players[previousEntry[0]];p={...previous,id:c.peer,name:n,profileKey:x.profileKey||previous.profileKey,rating:Number(x.rating)||previous.rating,active:true,host:false,ping:0,spectator:previous.spectator&&S.status!=="lobby"?true:spectate}}else{p=newPlayer(c.peer,{username:n,profileKey:x.profileKey,rating:x.rating},false,spectate);p.team=teamForNewPlayer()}S.players[c.peer]=p;send(c,"welcome",{playerId:c.peer,roomCode:room,state:snap()});sync();toast(n+(spectate?" seyirci oldu":previous?" yeniden bağlandı":" katıldı"))}else if(m.type==="select")choose(c.peer,x.optionId,x.roundId);else if(m.type==="ready"&&S.players[c.peer]){S.players[c.peer].ready=!!x.ready;sync()}else if(m.type==="latency"&&S.players[c.peer]){S.players[c.peer].ping=Math.max(0,Math.min(999,+x.ms||0));sync()}else if(m.type==="reaction"){const emoji=String(x.emoji||"");const allowed=["🔥","👏","⚽","🤯","😂","👍"];if(allowed.includes(emoji)){const name=S.players[c.peer]?.name||x.name||"Oyuncu";showReaction(name,emoji);conns.forEach((conn,id)=>{if(id!==c.peer)send(conn,"reaction",{name,emoji})})}}/*guestMsgReactionV5*/else if(m.type==="ping")send(c,"pong",{t:x.t})}
function teamForNewPlayer(){const a=competitors().filter(p=>p.team==="A").length,b=competitors().filter(p=>p.team==="B").length;return a<=b?"A":"B"}
function dropPlayer(id){conns.delete(id);if(!S.players[id])return;if(S.status==="lobby")delete S.players[id];else S.players[id].active=false;sync();checkSpent()}
function joinRoom(){if(!ensureName())return;const c=code(U.joinCode.value);if(c.length<4)return toast("Oda kodunu gir");destroyNet();isHost=false;room=c;applyTheme(room);connectAsGuest(!!U.spectatorJoin.checked)}
function connectAsGuest(spectator=false){if(typeof Peer==="undefined")return toast("Bağlantı kütüphanesi yüklenemedi");peer=new Peer(undefined,{debug:0});peer.on("open",id=>{me=id;openHostConnection(spectator)});peer.on("error",e=>{if(e.type==="peer-unavailable")toast("Oda bulunamadı");else toast("Bağlantı hatası")})}
function openHostConnection(spectator=false){hostConn=peer.connect(hostPeerId(room),{reliable:true});hostConn.on("open",()=>{send(hostConn,"join",{name:profile.username,profileKey:profile.profileKey,rating:profile.rating,spectator});connectionUI(true)});hostConn.on("data",hostMsg);hostConn.on("close",()=>{connectionUI(false);attemptReconnect(spectator)});hostConn.on("error",()=>connectionUI(false))}
let migrationBusy=false;
function migrationCandidate(){return Object.values(S.players).filter(p=>p.active!==false&&!p.spectator&&p.id!==S.hostId).sort((a,b)=>(a.joinedAt||0)-(b.joinedAt||0)||String(a.id).localeCompare(String(b.id)))[0]||null}
function promoteToHost(){if(isHost||migrationBusy)return false;const candidate=migrationCandidate();if(!candidate||candidate.id!==me)return false;migrationBusy=true;clearTimeout(reconnectTimer);const oldMe=me,oldHost=S.hostId,mine={...S.players[oldMe]};if(S.players[oldHost]){const departed={...S.players[oldHost],id:"departed-"+Date.now(),active:false,host:false};S.players[departed.id]=departed;delete S.players[oldHost]}delete S.players[oldMe];try{hostConn?.close()}catch{}hostConn=null;try{peer?.destroy()}catch{}peer=null;conns.clear();let attempts=0;const launch=()=>{attempts++;peer=new Peer(hostPeerId(room),{debug:0});peer.on("connection",c=>wireGuest(c));peer.on("open",id=>{me=id;isHost=true;S.hostId=id;S.players[id]={...mine,id,host:true,active:true,ready:true,ping:0};migrationBusy=false;connectionUI(true,0);if(S.status==="playing"){clearInterval(tickTimer);tickTimer=setInterval(()=>{if(isHost&&S.status==="playing"&&S.endsAt&&Date.now()>=S.endsAt)finishMatch("time")},200)}render();sync();toast("Kurucu ayrıldı • Yeni kurucu sensin")});peer.on("error",e=>{try{peer.destroy()}catch{}if(e.type==="unavailable-id"&&attempts<10)return setTimeout(launch,450);migrationBusy=false;toast("Oda devri tamamlanamadı")})};setTimeout(launch,350);return true}
function attemptReconnect(spectator){if(promoteToHost())return;let tries=0;clearTimeout(reconnectTimer);const retry=()=>{if(isHost||!peer||tries++>=10){if(!isHost)toast("Kurucu bağlantısı kesildi");return}if(promoteToHost())return;toast(`Yeniden bağlanılıyor ${tries}/10`);try{hostConn?.close()}catch{}hostConn=peer.connect(hostPeerId(room),{reliable:true});hostConn.on("open",()=>{send(hostConn,"join",{name:profile.username,profileKey:profile.profileKey,rating:profile.rating,spectator});connectionUI(true)});hostConn.on("data",hostMsg);hostConn.on("close",()=>{connectionUI(false);reconnectTimer=setTimeout(retry,800)});hostConn.on("error",()=>{connectionUI(false);reconnectTimer=setTimeout(retry,800)})};reconnectTimer=setTimeout(retry,650)}
function hostMsg(m){if(!m?.type)return;const x=m.payload||{};if(m.type==="reject"){toast(x.reason||"Giriş reddedildi");return}if(m.type==="welcome"){me=x.playerId;room=x.roomCode;Object.assign(S,x.state);render();startPingLoop()}else if(m.type==="state"){Object.assign(S,x);render()}else if(m.type==="kick"){toast("Odadan çıkarıldın");setTimeout(home,900)}else if(m.type==="pong"){const ms=Date.now()-x.t;send(hostConn,"latency",{ms});if(S.players[me])S.players[me].ping=ms;connectionUI(true,ms)}else if(m.type==="reaction"){showReaction(x.name,x.emoji)}else if(m.type==="result"){x.good?okSound():wrongSound()}/*hostMsgReactionV5*/}
function showReaction(name,emoji){const el=document.createElement("div");el.className="reaction-pop";el.innerHTML=`<b>${esc(name||"Oyuncu")}</b><span>${emoji}</span>`;document.body.appendChild(el);requestAnimationFrame(()=>el.classList.add("show"));setTimeout(()=>{el.classList.remove("show");setTimeout(()=>el.remove(),260)},1650)}
function sendReaction(emoji){const allowed=["🔥","👏","⚽","🤯","😂","👍"];if(!allowed.includes(emoji))return;const name=S.players[me]?.name||profile.username||"Oyuncu";showReaction(name,emoji);if(isHost)broadcast("reaction",{name,emoji});else send(hostConn,"reaction",{name,emoji})}
function startPingLoop(){clearInterval(pingTimer);pingTimer=setInterval(()=>{if(isHost){if(S.players[me])S.players[me].ping=0;conns.forEach(c=>send(c,"ping",{t:Date.now()}))}else if(hostConn?.open)send(hostConn,"ping",{t:Date.now()})},5000)}
function connectionUI(ok,ms){U.connectionDot.classList.toggle("online",!!ok);U.connectionText.textContent=ok?"Bağlantı aktif":"Bağlantı kesildi";U.pingText.textContent=ok?(typeof ms==="number"?`${Math.round(ms)} ms`:"Canlı senkronizasyon"):"Yeniden bağlanma bekleniyor"}
function startSolo(){if(!ensureName())return;destroyNet();isHost=true;room="SOLO";me="solo-"+profile.profileKey.slice(0,8);S=blank();S.status="lobby";S.hostId=me;S.settings=settingsFor(selectedMode);S.players[me]=newPlayer(me,profile,true,false);S.players[me].ready=true;applyTheme(profile.profileKey);startMatch()}
function applyMode(id){const max=S.settings.maxPlayers||8;S.settings={...settingsFor(id),maxPlayers:max};renderLobby();sync()}
function startMatch(){if(!isHost)return;if(competitors().length<1)return toast("En az 1 oyuncu gerekli");const m=mode();for(const p of Object.values(S.players)){p.score=0;p.correct=0;p.wrong=0;p.streak=0;p.bestStreak=0;p.fastest=0;p.managerCorrect=0;p.eliminated=false;p.ratingDelta=0;p.placement=0}S.status="playing";S.deck=makeDeck(S.settings.content);S.roundIndex=-1;S.cycle=0;S.matchId=uuid();S.matchStartedAt=Date.now();S.endsAt=S.settings.timeLimit?S.matchStartedAt+S.settings.timeLimit*1000:0;S.teamScores={A:0,B:0,coop:0};S.finishReason="";recordedMatch="";startMusic();clearInterval(tickTimer);tickTimer=setInterval(()=>{if(isHost&&S.status==="playing"&&S.endsAt&&Date.now()>=S.endsAt)finishMatch("time")},200);nextRound()}
function nextRound(){if(!isHost||S.status!=="playing")return;if(S.endsAt&&Date.now()>=S.endsAt)return finishMatch("time");const m=mode();if(!S.endsAt&&S.roundIndex+1>=S.settings.roundCount)return finishMatch("cards");S.roundIndex++;if(S.roundIndex>=S.deck.length){S.cycle++;S.deck=makeDeck(S.settings.content);S.roundIndex=0}const r=resolveDeckItem(S.deck[S.roundIndex]);if(!r)return finishMatch("data");S.currentRound=r;S.options=buildOptions(r,S.settings.optionCount);S.selections={};S.locked=false;S.winnerId=null;S.correctAnswerId=key(r.kind,r.answer);S.roundStartedAt=Date.now();preloadNext();sync()}
function preloadNext(){for(let n=1;n<=3;n++){let idx=S.roundIndex+n;if(idx>=S.deck.length)continue;const r=resolveDeckItem(S.deck[idx]);if(!r)continue;for(const tid of [r.teamA,r.teamB])preloadUrl(window.QF_IMAGES?.teams?.[tid]);const e=entity(r.kind,r.answer);preloadUrl(r.kind==="manager"?window.QF_MANAGER_IMAGES?.[e?.id]:window.QF_IMAGES?.players?.[e?.id])}}
const warmed=new Set();function preloadUrl(u){if(!u||warmed.has(u))return;warmed.add(u);const i=new Image();i.src=u}
function localChoose(k){if(S.status!=="playing"||S.locked||S.players[me]?.spectator||S.players[me]?.eliminated||S.selections[me])return;ensureAudio();isHost?choose(me,k,S.currentRound.id):send(hostConn,"select",{optionId:k,roundId:S.currentRound.id})}
function choose(pid,opt,rid){if(!isHost||S.status!=="playing"||S.locked||S.currentRound?.id!==rid||S.selections[pid]||!S.options.includes(opt))return;const p=S.players[pid];if(!p||p.active===false||p.spectator||p.eliminated)return;const cfg=mode(),good=opt===S.correctAnswerId,ms=Math.max(0,Date.now()-S.roundStartedAt);S.selections[pid]={optionId:opt,correct:good,ms};if(good){p.correct++;p.streak++;p.bestStreak=Math.max(p.bestStreak,p.streak);p.fastest=p.fastest?Math.min(p.fastest,ms):ms;if(S.currentRound.kind==="manager")p.managerCorrect++;const scoring=S.settings.scoring||cfg.scoring,pts=scoring==="streak"?1+Math.min(2,Math.floor((p.streak-1)/3)):1;if(S.settings.rule==="team"){p.score+=pts;S.teamScores[p.team]=(S.teamScores[p.team]||0)+pts}else if(S.settings.rule==="coop"){p.score+=pts;S.teamScores.coop+=pts}else p.score+=pts;S.locked=true;S.winnerId=pid;broadcast("result",{good:true,winnerId:pid,points:pts});sync();okSound();const target=+S.settings.targetScore||+cfg.targetScore||0,hit=target&&(S.settings.rule==="team"?S.teamScores[p.team]>=target:S.settings.rule==="coop"?S.teamScores.coop>=target:p.score>=target);if(hit)return setTimeout(()=>finishMatch("target"),S.settings.chill?900:550);return setTimeout(nextRound,S.settings.chill?1050:650)}p.wrong++;p.streak=0;if(S.settings.rule==="survival")p.eliminated=true;broadcast("result",{good:false,winnerId:null});wrongSound();if(S.settings.rule==="solo"||competitors().length===1){S.locked=true;sync();return setTimeout(nextRound,850)}sync();if(S.settings.rule==="survival"&&eligible().length<=1)return setTimeout(()=>finishMatch("survival"),700);checkSpent()}
function checkSpent(){if(!isHost||S.status!=="playing"||S.locked)return;const a=eligible();if(a.length&&a.every(p=>!!S.selections[p.id])){S.locked=true;sync();setTimeout(nextRound,S.settings.chill?1200:780)}}
function finishMatch(reason="complete"){if(!isHost||S.status==="final")return;clearInterval(tickTimer);S.status="final";S.finishReason=reason;S.locked=true;S.currentRound=null;S.options=[];const list=competitors().sort((a,b)=>b.score-a.score||b.correct-a.correct||a.wrong-b.wrong||a.name.localeCompare(b.name));let place=1,prev=null;list.forEach((p,i)=>{if(prev!==null&&p.score<prev)place=i+1;p.placement=place;prev=p.score});const top=list[0]?.score,topCount=list.filter(p=>p.score===top).length;for(const p of list)p.ratingDelta=ratingDelta(p,list,topCount);S.awards=buildAwards(list);sync();renderFinal()}
function ratingDelta(p,list,topCount){if(!S.settings.rated||list.length<2)return 0;if(topCount>1&&p.score===list[0].score)return 4;if(p.placement===1)return list.length>=4?28:24;if(p.placement===2&&list.length>=3)return 6;return-12}
function buildAwards(list){if(!list.length)return[];const fastest=[...list].filter(p=>p.fastest>0).sort((a,b)=>a.fastest-b.fastest)[0],streak=[...list].sort((a,b)=>b.bestStreak-a.bestStreak)[0],clean=[...list].sort((a,b)=>a.wrong-b.wrong||b.correct-a.correct)[0];return[{icon:"⚡",title:"En Hızlı",value:fastest?`${fastest.name} • ${(fastest.fastest/1000).toFixed(2)} sn`:"—"},{icon:"🔥",title:"En İyi Seri",value:streak?`${streak.name} • ${streak.bestStreak}`:"—"},{icon:"🎯",title:"En Temiz",value:clean?`${clean.name} • ${clean.wrong} yanlış`:"—"}]}
function render(){syncProfileUI();if(S.status==="lobby"){screen("lobby");renderLobby()}else if(S.status==="playing"){screen("game");renderGame()}else if(S.status==="final"){screen("final");renderFinal()}else{screen("home");renderHome()}U.sound.textContent=sound?"🔊":"🔇"}
function renderHome(){U.homeModeCount.textContent=Object.keys(MODES).length;const m=MODES[selectedMode]||MODES.classic25;U.selectedModeName.textContent=m.name;U.selectedModeDesc.textContent=m.desc;updateCloudChip()}
function renderLobby(){const m=mode();U.roomCode.textContent=room||"SOLO";U.lobbyModeTitle.textContent=m.icon+" "+m.name;U.lobbyModeDesc.textContent=m.desc;const all=Object.values(S.players).filter(p=>p.active!==false),players=all.filter(p=>!p.spectator),spec=all.filter(p=>p.spectator);U.lobbyCapacity.textContent=`${players.length} / ${S.settings.maxPlayers}`;U.spectatorInfo.textContent=spec.length?`${spec.length} seyirci bağlı`:"";U.lobbyPlayers.innerHTML=all.map(p=>`<div class="lobby-player ${p.id===me?"me-player":""}"><div class="player-meta"><div class="avatar-dot">${esc(initials(p.name))}</div><div><b>${esc(p.name)}</b><small>${p.spectator?"Seyirci":p.host?"Oda kurucusu":p.ready?"Hazır":"Hazırlanıyor"}</small></div></div><div class="player-side-actions">${p.spectator?'<span class="spectator-badge">SEYİRCİ</span>':`<span class="team-badge team-${p.team.toLowerCase()}">${p.team==="A"?"MAVİ":"ALTIN"}</span>${p.ready?'<span class="ready-badge">HAZIR</span>':""}`}<span class="ping-badge">${p.ping?Math.round(p.ping)+"ms":"●"}</span>${isHost&&!p.host?`<button class="kick-btn" data-kick="${esc(p.id)}">×</button>`:""}</div></div>`).join("");U.lobbyPlayers.querySelectorAll("[data-kick]").forEach(b=>b.onclick=()=>kick(b.dataset.kick));U.modeSelect.value=S.settings.modeId;U.choiceSelect.value=String(S.settings.optionCount);U.maxPlayers.value=String(S.settings.maxPlayers);U.contentSelect.value=S.settings.content;for(const e of [U.modeSelect,U.choiceSelect,U.maxPlayers,U.contentSelect])e.disabled=!isHost;U.start.style.display=isHost?"":"none";U.start.disabled=!isHost||players.length<1;U.ready.style.display=S.players[me]?.spectator?"none":"";U.ready.textContent=S.players[me]?.ready?"Hazırım ✓":"Hazırım";U.hostControl.textContent=isHost?"Kurucu kontrolü":"Kurucu belirliyor";U.format.textContent=formatText(S.settings);U.teamTools.classList.toggle("hidden",S.settings.rule!=="team");U.hostHint.textContent=isHost?`${players.length} oyuncu bağlı. Tek oyuncuyla da başlatabilirsin.`:"Kurucunun maçı başlatmasını bekliyorsun.";U.modeRules.innerHTML=ruleHtml({...m,...S.settings});syncCustomControls();connectionUI(isHost||hostConn?.open,S.players[me]?.ping||0)}
function formatText(s){const end=s.targetScore?`${s.targetScore} hedef puan`:s.timeLimit?`${Math.round(s.timeLimit/60)} dakika`:`${s.roundCount} kart`,score=s.scoring==="streak"?"seri bonusu":"normal puan";return`${end} • ${s.optionCount} seçenek • ${s.content==="manager"?"teknik direktör":s.content==="mixed"?"karma":"futbolcu"} • ${score}`}
function ruleHtml(m){const end=m.targetScore?`${m.targetScore} puana ilk ulaşan taraf maçı anında bitirir.`:m.timeLimit?`Maç ${Math.round(m.timeLimit/60)} dakika sonunda kart sayısından bağımsız biter.`:`Maç ${m.roundCount} kart sonunda biter.`,score=m.scoring==="streak"?"Seri uzadıkça doğru cevap 2–3 puana kadar çıkar.":m.rule==="survival"?"Yanlış seçim oyuncuyu eler.":m.rule==="team"?"İlk doğru cevap takım puanını artırır.":m.rule==="coop"?"Herkes ortak hedef için oynar.":"Competitive akışta ilk doğru cevap turu kazanır.";const arr=[m.rated?"Global rating bu maçtan etkilenir.":"Bu mod rating kaybettirmez.",end,score];return arr.map((x,i)=>`<div class="rule-row"><i>${["◈","⏱","⚡"][i]}</i><span>${esc(x)}</span></div>`).join("")}
function renderGame(){const r=S.currentRound;if(!r)return;const m=mode(),a=D.teams[r.teamA],b=D.teams[r.teamB],count=S.settings.optionCount,spent=!!S.selections[me],mine=S.players[me];U.gameModeIcon.textContent=m.icon;U.gameModeName.textContent=m.name;U.gameContent.textContent=r.kind==="manager"?"TEKNİK DİREKTÖR BAĞLANTISI":"FUTBOLCU BAĞLANTISI";U.questionType.textContent=r.kind==="manager"?"TEKNİK DİREKTÖR":"FUTBOLCU";U.optionChip.textContent=`${count} SEÇENEK`;U.relation.textContent=r.kind==="manager"?"İKİ KULÜBÜ DE ÇALIŞTIRDI":"İKİ KULÜPTE DE OYNADI";U.teamAName.textContent=a.short;U.teamBName.textContent=b.short;teamImage(U.teamALogo,r.teamA);teamImage(U.teamBLogo,r.teamB);U.roundProgress.textContent=S.endsAt?`#${S.roundIndex+1}`:`${S.roundIndex+1} / ${S.settings.roundCount}`;const progress=S.endsAt?Math.min(1,(Date.now()-S.matchStartedAt)/(S.settings.timeLimit*1000)):Math.min(1,(S.roundIndex+1)/S.settings.roundCount);U.progressBar.style.width=progress*100+"%";U.finalChip.classList.toggle("show",progress>=.82);U.roundStatus.textContent=S.locked?"Yeni soru hazırlanıyor":mine?.spectator?"Seyirci modundasın":mine?.eliminated?"Bu maçta elendin":spent?"Seçimini yaptın":r.kind==="manager"?"İki kulübü de çalıştırmış teknik direktörü seç":"İki kulüpte de oynamış futbolcuyu seç";renderAnswers(r,spent||mine?.spectator||mine?.eliminated);renderScores();renderFeed();renderPersonal();renderTimerUI()}
function renderAnswers(r,disabled){U.answerGrid.dataset.count=String(S.settings.optionCount);U.answerGrid.innerHTML=S.options.map((k,i)=>{const f=fromKey(k),e=entity(f.kind,f.id),mine=S.selections[me]?.optionId===k,correct=S.locked&&S.correctAnswerId===k,wrong=mine&&S.selections[me]&&!S.selections[me].correct;return`<button class="answer-card ${mine?"selected":""} ${correct?"correct revealed-correct":""} ${wrong?"wrong revealed-wrong":""}" data-answer="${k}" ${S.locked||disabled?"disabled":""}><span class="answer-index">${i+1}</span><div class="player-photo image-shell" data-kind="${f.kind}" data-id="${f.id}"><span>${esc(initials(e?.name))}</span></div><div class="answer-copy"><div class="answer-name">${esc(e?.name||"Bilinmiyor")}</div><div class="answer-sub">${f.kind==="manager"?"Teknik Direktör":"Futbolcu"}</div></div></button>`}).join("");U.answerGrid.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>localChoose(b.dataset.answer));U.answerGrid.querySelectorAll(".player-photo").forEach(x=>personImage(x,x.dataset.kind,x.dataset.id));const answer=S.correctAnswerId?entity(fromKey(S.correctAnswerId).kind,fromKey(S.correctAnswerId).id):null;if(S.locked)U.result.textContent=S.winnerId?`${S.players[S.winnerId]?.name||"Oyuncu"} turu aldı • ${answer?.name||""}`:`Doğru cevap: ${answer?.name||""}`;else U.result.textContent=""}
function renderScores(){const list=competitors().sort((a,b)=>b.score-a.score||b.correct-a.correct);U.teamScoreText.textContent=S.settings.rule==="team"?`MAVİ ${S.teamScores.A} • ${S.teamScores.B} ALTIN`:S.settings.rule==="coop"?`ORTAK ${S.teamScores.coop}`:"";U.scorePlayers.innerHTML=list.map((p,i)=>`<div class="player-row ${p.eliminated?"eliminated":""} ${S.settings.rule==="team"?`score-player-team-${p.team.toLowerCase()}`:""}"><span class="rank">${i+1}</span><div class="score-name"><b>${esc(p.name)}</b><small>${p.eliminated?"ELENDİ":p.id===me?"SEN":p.team==="A"?"MAVİ":"ALTIN"}</small></div><div class="score-right">${p.streak>=2?`<span class="streak-chip">🔥${p.streak}</span>`:""}<strong>${p.score}</strong></div></div>`).join("")}
function renderFeed(){const rows=Object.entries(S.selections).map(([id,s])=>{const p=S.players[id],f=fromKey(s.optionId),e=entity(f.kind,f.id);return`<div class="feed-item ${s.correct?"correct-feed":""}"><span>${s.correct?"✓":"×"}</span><div><b>${esc(p?.name||"Oyuncu")}</b><small>${esc(e?.name||"")} • ${(s.ms/1000).toFixed(2)} sn</small></div></div>`});U.feed.innerHTML=rows.length?rows.join(""):'<div class="empty-feed">Henüz seçim yok.</div>'}
function renderPersonal(){const p=S.players[me];if(!p)return U.personalStats.innerHTML="";U.personalStats.innerHTML=`<div class="mini-stat"><b>${p.correct}</b><small>DOĞRU</small></div><div class="mini-stat"><b>${p.wrong}</b><small>YANLIŞ</small></div><div class="mini-stat"><b>${p.bestStreak}</b><small>EN İYİ SERİ</small></div><div class="mini-stat"><b>${p.fastest?`${(p.fastest/1000).toFixed(2)}s`:"—"}</b><small>EN HIZLI</small></div>`}
function renderTimerUI(){if(!S.endsAt){U.timerText.textContent="∞";U.timerBar.style.width="100%";U.matchClock.classList.remove("danger");return}const left=Math.max(0,S.endsAt-Date.now()),sec=Math.ceil(left/1000),m=Math.floor(sec/60),s=sec%60;U.timerText.textContent=`${m}:${String(s).padStart(2,"0")}`;const pct=Math.max(0,left/(S.settings.timeLimit*1000))*100;U.timerBar.style.width=pct+"%";U.matchClock.classList.toggle("danger",left<30000)}
function renderFinal(){screen("final");stopMusic();const list=competitors().sort((a,b)=>a.placement-b.placement||b.score-a.score),mine=S.players[me],m=mode();if(S.settings.rule==="team"){const win=S.teamScores.A===S.teamScores.B?"Beraberlik":S.teamScores.A>S.teamScores.B?"Mavi Takım Kazandı":"Altın Takım Kazandı";U.winnerTitle.textContent=win;U.winnerSubtitle.textContent=`Mavi ${S.teamScores.A} • ${S.teamScores.B} Altın`}else if(S.settings.rule==="coop"){U.winnerTitle.textContent="Ortak Görev Tamamlandı";U.winnerSubtitle.textContent=`Takımınız ${S.teamScores.coop} bağlantı buldu.`}else{U.winnerTitle.textContent=list.length===1?"Kişisel Sonucun":`${list[0]?.name||"Oyuncu"} Kazandı`;U.winnerSubtitle.textContent=`${m.name} • ${S.finishReason==="time"?"Süre tamamlandı":S.finishReason==="survival"?"Son oyuncu kaldı":"Maç tamamlandı"}`}U.finalScores.innerHTML=list.map(p=>`<div class="final-score-row"><span>#${p.placement}</span><b>${esc(p.name)}</b><small>${p.correct} doğru • ${p.wrong} yanlış • seri ${p.bestStreak}</small><strong>${p.score}</strong></div>`).join("");U.ratingResult.innerHTML=mine?`<div class="rating-chip ${mine.ratingDelta>0?"positive":mine.ratingDelta<0?"negative":""}"><small>RATING</small><b>${mine.ratingDelta>0?"+":""}${mine.ratingDelta}</b></div><div class="rating-chip"><small>MAÇ SKORU</small><b>${mine.score}</b></div>`:"";U.awards.innerHTML=(S.awards||[]).map(a=>`<div class="award-card"><span>${a.icon}</span><b>${esc(a.title)}</b><small>${esc(a.value)}</small></div>`).join("");recordMyResult()}
async function recordMyResult(){if(!S.matchId||recordedMatch===S.matchId)return;const p=S.players[me];if(!p||p.spectator)return;recordedMatch=S.matchId;const list=competitors(),top=list[0]?.score||0,tie=list.filter(x=>x.score===top).length>1,won=p.placement===1&&!tie,draw=p.placement===1&&tie,wasSolo=list.length===1,old={...profile};profile.games++;if(won)profile.wins++;else if(draw)profile.draws++;else profile.losses++;profile.correct+=p.correct;profile.wrong+=p.wrong;profile.bestStreak=Math.max(profile.bestStreak,p.bestStreak);profile.managerCorrect+=p.managerCorrect;if(S.settings.timeLimit)profile.timedBest=Math.max(profile.timedBest,p.score);if(wasSolo)profile.soloBest=Math.max(profile.soloBest,p.score);if(S.settings.rated&&won)profile.rankedWins++;if(S.settings.chill)profile.chillGames++;profile.rating=Math.max(100,profile.rating+p.ratingDelta);const xpGain=p.correct*10+(won?30:0)+Math.max(0,p.bestStreak-2)*3;profile.xp+=xpGain;profile.level=Math.max(1,Math.floor(Math.sqrt(profile.xp/120))+1);profile.badges=unlockBadges(profile,p,won,wasSolo);saveProfileLocal();const duration=Math.round(((S.endsAt?Math.min(Date.now(),S.endsAt):Date.now())-S.matchStartedAt)/1000);const h={at:Date.now(),mode:S.settings.modeId,modeName:mode().name,score:p.score,correct:p.correct,wrong:p.wrong,placement:p.placement,ratingDelta:p.ratingDelta};history.unshift(h);saveHistory();try{await window.QFCloud?.recordMatch?.({match_id:S.matchId,profile_key:profile.profileKey,username:profile.username,mode:S.settings.modeId,content_type:S.settings.content,placement:p.placement,score:p.score,correct:p.correct,wrong:p.wrong,best_streak:p.bestStreak,duration_sec:duration,rating_delta:p.ratingDelta,room_code:room,profile:{profile_key:profile.profileKey,username:profile.username,rating:profile.rating,xp:profile.xp,level:profile.level,games:profile.games,wins:profile.wins,losses:profile.losses,draws:profile.draws,correct:profile.correct,wrong:profile.wrong,best_streak:profile.bestStreak,timed_best:profile.timedBest,solo_best:profile.soloBest,ranked_wins:profile.rankedWins,chill_games:profile.chillGames,manager_correct:profile.managerCorrect,badges:profile.badges}})}catch{}if(old.rating!==profile.rating)syncProfileUI()}
function unlockBadges(p,s,won,solo){const b=new Set(p.badges||[]);if(p.games>=1)b.add("İlk Maç");if(won)b.add("Maç Galibi");if(p.wins>=10)b.add("10 Galibiyet");if(s.bestStreak>=5)b.add("Seri 5");if(s.bestStreak>=10)b.add("Seri 10");if(s.fastest&&s.fastest<1500)b.add("Şimşek");if(s.managerCorrect>=5)b.add("Taktik Dehası");if(solo&&s.score>=20)b.add("Solo 20");if(p.rating>=1200)b.add("1200 Kulübü");if(p.rating>=1500)b.add("Elite");return[...b]}
function kick(id){if(!isHost||!S.players[id])return;send(conns.get(id),"kick",{});try{conns.get(id)?.close()}catch{};delete S.players[id];conns.delete(id);sync()}
function toggleReady(){const p=S.players[me];if(!p||p.spectator)return;p.ready=!p.ready;if(isHost)sync();else send(hostConn,"ready",{ready:p.ready});renderLobby()}
function installCustomControls(){if(document.getElementById("customMatchControls")||!U.format)return;U.format.insertAdjacentHTML("beforebegin",`<div id="customMatchControls" class="custom-match-controls hidden"><div class="panel-label"><span>ÖZEL MAÇ LABORATUVARI</span><small>Yüzlerce kombinasyon</small></div><div class="custom-grid"><label>Bitiş<select id="customEnd"><option value="cards25">25 kart</option><option value="cards50">50 kart</option><option value="cards100">100 kart</option><option value="time180">3 dakika</option><option value="time300">5 dakika</option><option value="time600">10 dakika</option><option value="target10">10 hedef puan</option><option value="target20">20 hedef puan</option></select></label><label>Puanlama<select id="customScoring"><option value="normal">Normal +1</option><option value="streak">Seri bonusu +1/+2/+3</option></select></label><label>Kural<select id="customRule"><option value="first">Herkes tek</option><option value="team">Mavi vs Altın</option><option value="coop">Co-op ortak skor</option><option value="survival">Survival</option></select></label></div></div>`);for(const id of ["customEnd","customScoring","customRule"])document.getElementById(id).onchange=applyCustomControls}
function customEndValue(){if(S.settings.targetScore)return`target${S.settings.targetScore}`;if(S.settings.timeLimit)return`time${S.settings.timeLimit}`;return`cards${S.settings.roundCount}`}
function syncCustomControls(){const box=document.getElementById("customMatchControls");if(!box)return;const on=S.settings.modeId==="custom";box.classList.toggle("hidden",!on);for(const id of ["customEnd","customScoring","customRule"])if(document.getElementById(id))document.getElementById(id).disabled=!isHost;if(!on)return;document.getElementById("customEnd").value=customEndValue();document.getElementById("customScoring").value=S.settings.scoring||"normal";document.getElementById("customRule").value=S.settings.rule||"first"}
function applyCustomControls(){if(!isHost||S.settings.modeId!=="custom")return;const end=document.getElementById("customEnd")?.value||"cards25";S.settings.timeLimit=0;S.settings.targetScore=0;S.settings.roundCount=100;if(end.startsWith("cards"))S.settings.roundCount=+end.slice(5)||25;else if(end.startsWith("time"))S.settings.timeLimit=+end.slice(4)||180;else if(end.startsWith("target"))S.settings.targetScore=+end.slice(6)||10;S.settings.scoring=document.getElementById("customScoring")?.value==="streak"?"streak":"normal";const rule=document.getElementById("customRule")?.value;S.settings.rule=["first","team","coop","survival"].includes(rule)?rule:"first";S.settings.rated=false;sync()}
function changeSetting(e){if(!isHost)return;const id=U.modeSelect.value;if(id!==S.settings.modeId){const max=+U.maxPlayers.value||8;S.settings={...settingsFor(id),maxPlayers:max};U.choiceSelect.value=String(S.settings.optionCount);U.contentSelect.value=S.settings.content}else{S.settings.optionCount=[4,6,8].includes(+U.choiceSelect.value)?+U.choiceSelect.value:S.settings.optionCount;S.settings.content=["player","manager","mixed"].includes(U.contentSelect.value)?U.contentSelect.value:S.settings.content}S.settings.maxPlayers=Math.max(2,Math.min(8,+U.maxPlayers.value||8));sync()}
function rematch(){if(!isHost)return toast("Rövanşı kurucu başlatabilir");S.status="lobby";S.matchId="";S.deck=[];S.currentRound=null;S.selections={};S.locked=false;S.endsAt=0;for(const p of Object.values(S.players)){p.ready=p.host;p.score=0;p.correct=0;p.wrong=0;p.eliminated=false}sync()}
function home(){clearInterval(tickTimer);clearInterval(renderTimer);stopMusic();destroyNet();S=blank();isHost=false;room=me="";window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.window.history.replaceState({},"",location.pathname);applyTheme("home");screen("home");renderHome()}
function teamImage(el,id){const url=window.QF_IMAGES?.teams?.[id];setImage(el,url,D.teams[id]?.short||id,"team-img")}
function personImage(el,kind,id){const url=kind==="manager"?window.QF_MANAGER_IMAGES?.[id]:window.QF_IMAGES?.players?.[id];const e=entity(kind,id);setImage(el,url,e?.name||id,kind==="manager"?"manager-img":"person-img")}
function setImage(el,url,alt,cls){if(!el)return;if(!url){el.innerHTML=`<span>${esc(initials(alt))}</span>`;return}const img=new Image();img.alt=alt;img.decoding="async";img.loading="eager";img.className=cls;img.onload=()=>{el.innerHTML="";el.appendChild(img)};img.onerror=()=>{el.innerHTML=`<span>${esc(initials(alt))}</span>`};img.src=url}
function ensureAudio(){if(!sound)return null;if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume();return audio}
function tone(freq=.5,dur=.15,type="sine",gain=.025){const a=ensureAudio();if(!a)return;const o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,a.currentTime);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+dur)}
function okSound(){tone(660,.13,"sine",.025);setTimeout(()=>tone(880,.16,"sine",.02),70)}function wrongSound(){tone(170,.14,"triangle",.018)}
function startMusic(){if(!sound||music)return;const a=ensureAudio();if(!a)return;let step=0;const chords=[[110,164.81,220],[98,146.83,196],[123.47,185,246.94],[87.31,130.81,174.61]];const play=()=>{const now=a.currentTime;for(const f of chords[step++%chords.length]){const o=a.createOscillator(),g=a.createGain();o.type="sine";o.frequency.value=f;g.gain.setValueAtTime(.0001,now);g.gain.linearRampToValueAtTime(.009,now+.35);g.gain.exponentialRampToValueAtTime(.0001,now+3.4);o.connect(g);g.connect(a.destination);o.start(now);o.stop(now+3.5)}};play();music=setInterval(play,3300)}function stopMusic(){if(music)clearInterval(music);music=null}
function toggleSound(){sound=!sound;localStorage.setItem(SOUND_LS,sound?"1":"0");U.sound.textContent=sound?"🔊":"🔇";if(!sound)stopMusic();else if(S.status==="playing")startMusic()}
function toggleFullscreen(){document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.()}
function openModal(which){U.backdrop.classList.remove("hidden");for(const m of [U.leaderModal,U.profileModal,U.qrModal])m.classList.add("hidden");which.classList.remove("hidden")}
function closeModal(){U.backdrop.classList.add("hidden");for(const m of [U.leaderModal,U.profileModal,U.qrModal])m.classList.add("hidden")}
async function showLeaderboard(sort="rating"){openModal(U.leaderModal);U.leaderStatus.textContent="Global sıralama yükleniyor...";let rows=[];try{rows=await window.QFCloud?.leaderboard?.(100)||[]}catch{};rows=[...rows].sort((a,b)=>(Number(b[sort])||0)-(Number(a[sort])||0)||String(a.username).localeCompare(String(b.username))).slice(0,50);U.leaderList.innerHTML=rows.length?rows.map((p,i)=>`<div class="leader-row ${p.profile_key===profile.profileKey?"me":""}"><span class="leader-rank">#${i+1}</span><div class="leader-user"><b>${esc(p.username||"Oyuncu")}</b><small>Lv.${p.level||1} • ${p.games||0} maç</small></div><div class="leader-value"><b>${sort==="rating"?Math.round(p.rating||1000):p[sort]||0}</b><small>${sort.toUpperCase()}</small></div><div class="leader-extra">${p.wins||0} W</div></div>`).join(""):'<div class="empty-feed">Henüz global skor bulunamadı veya bulut bağlantısı kullanılamıyor.</div>';U.leaderStatus.textContent=window.QFCloud?.statusText?.()||"Yerel görünüm"}
function showProfile(){openModal(U.profileModal);U.profileModalName.textContent=profile.username||"Oyuncu";const acc=profile.correct+profile.wrong?Math.round(profile.correct/(profile.correct+profile.wrong)*100):0;const stats=[["Rating",Math.round(profile.rating)],["Seviye",profile.level],["Maç",profile.games],["Galibiyet",profile.wins],["Doğruluk",acc+"%"],["En iyi seri",profile.bestStreak],["Solo rekor",profile.soloBest],["Süreli rekor",profile.timedBest]];U.profileStats.innerHTML=stats.map(([a,b])=>`<div class="profile-stat"><b>${b}</b><small>${a.toUpperCase()}</small></div>`).join("");U.badgeGrid.innerHTML=profile.badges.length?profile.badges.map(b=>`<span class="profile-badge">✦ ${esc(b)}</span>`).join(""):'<small>Rozet kazanmak için maç oyna.</small>';U.historyList.innerHTML=history.length?history.slice(0,12).map(h=>`<div class="history-row"><span><b>${esc(h.modeName||h.mode)}</b><small> ${new Date(h.at).toLocaleDateString("tr-TR")}</small></span><span>#${h.placement} • ${h.score} puan</span><span>${h.ratingDelta>0?"+":""}${h.ratingDelta} RP</span></div>`).join(""):'<div class="empty-feed">Henüz maç geçmişi yok.</div>'}
function showQR(){openModal(U.qrModal);const url=`${location.origin}${location.pathname}?room=${encodeURIComponent(room)}`;U.qrCanvas.innerHTML=`<img alt="Oda QR kodu" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(url)}">`;U.qrCodeText.textContent=room}
function updateCloudChip(){if(!U.cloudChip)return;const s=window.QFCloud?.status||"loading";U.cloudChip.textContent=s==="online"?"● GLOBAL SKOR ONLINE":s==="degraded"?"◐ GLOBAL SKOR YEDEK MOD":"○ GLOBAL SKOR BAĞLANIYOR"}
function copyInvite(){const url=`${location.origin}${location.pathname}?room=${room}`;navigator.clipboard?.writeText(url).then(()=>toast("Davet linki kopyalandı")).catch(()=>toast(room))}
function wire(){installCustomControls();if(!document.getElementById("reactionBar")){const panel=document.querySelector(".activity-panel");if(panel){panel.insertAdjacentHTML("beforeend",`<div id="reactionBar" class="reaction-bar"><small>TEPKİ</small>${["🔥","👏","⚽","🤯","😂","👍"].map(e=>`<button type="button" data-react="${e}">${e}</button>`).join("")}</div>`);panel.querySelectorAll("[data-react]").forEach(b=>b.onclick=()=>sendReaction(b.dataset.react))}}syncProfileUI();populateModeSelect();renderModeTabs((MODES[selectedMode]||MODES.classic25).group);selectMode(selectedMode);U.saveProfile.onclick=saveName;U.profileNameInput.onkeydown=e=>{if(e.key==="Enter")saveName()};U.createRoom.onclick=hostRoom;U.soloStart.onclick=startSolo;U.joinRoom.onclick=joinRoom;U.joinCode.onkeydown=e=>{if(e.key==="Enter")joinRoom()};document.querySelectorAll(".mode-tab").forEach(b=>b.onclick=()=>renderModeTabs(b.dataset.group));U.modeSelect.onchange=changeSetting;U.choiceSelect.onchange=changeSetting;U.maxPlayers.onchange=changeSetting;U.contentSelect.onchange=changeSetting;U.start.onclick=startMatch;U.ready.onclick=toggleReady;U.copyRoom.onclick=copyInvite;U.qrRoom.onclick=showQR;U.sound.onclick=toggleSound;U.fullscreen.onclick=toggleFullscreen;U.brand.onclick=home;U.back.onclick=home;U.again.onclick=rematch;U.leaderboardBtn.onclick=()=>showLeaderboard("rating");U.leaderboardFinalBtn.onclick=()=>showLeaderboard("rating");U.profileBtn.onclick=showProfile;U.profilePill.onclick=showProfile;document.querySelectorAll("[data-close-modal]").forEach(b=>b.onclick=closeModal);U.backdrop.onclick=e=>{if(e.target===U.backdrop)closeModal()};document.querySelectorAll("[data-board]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-board]").forEach(x=>x.classList.toggle("active",x===b));showLeaderboard(b.dataset.board)});document.addEventListener("keydown",e=>{if(S.status==="playing"&&/^[1-8]$/.test(e.key)){const i=+e.key-1;if(S.options[i])localChoose(S.options[i])}if(e.key==="Escape")closeModal()});window.addEventListener("beforeunload",()=>{try{destroyNet()}catch{}});renderTimer=setInterval(()=>{if(S.status==="playing")renderTimerUI();updateCloudChip()},250);const q=new URLSearchParams(location.search).get("room");if(q){U.joinCode.value=code(q);if(profile.username)setTimeout(()=>joinRoom(),250)}if(profile.username)window.QFCloud?.ensureProfile?.({profile_key:profile.profileKey,username:profile.username,rating:profile.rating,xp:profile.xp,level:profile.level,games:profile.games,wins:profile.wins,losses:profile.losses,draws:profile.draws,correct:profile.correct,wrong:profile.wrong,best_streak:profile.bestStreak,timed_best:profile.timedBest,solo_best:profile.soloBest,ranked_wins:profile.rankedWins,chill_games:profile.chillGames,manager_correct:profile.managerCorrect,badges:profile.badges});renderHome()}
if(location.hostname==="127.0.0.1"||location.hostname==="localhost")window.QFTest={getState:()=>structuredClone(snap()),setEndsIn:ms=>{if(isHost&&S.status==="playing"){S.endsAt=Date.now()+Math.max(50,+ms||50);sync()}},setMyScore:v=>{if(isHost&&S.players[me]){S.players[me].score=Math.max(0,+v||0);sync()}},setMyStreak:v=>{if(isHost&&S.players[me]){S.players[me].streak=Math.max(0,+v||0);sync()}},chooseCorrect:()=>isHost&&S.currentRound&&choose(me,S.correctAnswerId,S.currentRound.id),finish:()=>isHost&&finishMatch("qa"),profile:()=>({...profile}),isHost:()=>isHost,me:()=>me};
window.QFSocial={react:sendReaction};
wire();
})();
