(()=>{"use strict";
const KEY="qf-v13-audio",CROWD="https://upload.wikimedia.org/wikipedia/commons/1/15/Festival_concert_people_crowd.ogg",CHEER="https://upload.wikimedia.org/wikipedia/commons/e/e8/Hurray.ogg",REACT="https://upload.wikimedia.org/wikipedia/commons/0/0f/Ohhh_ahhh.ogg";
const defaults={enabled:true,commentary:true,effects:true,crowd:true,captions:true,master:.84,commentator:.78,effectVolume:.70,crowdVolume:.20,rate:.74,pitch:.94},clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let settings=load(),ctx=null,fxBus=null,masterBus=null,unlocked=false,crowd=null,cheer=null,react=null,active=false,mode="",stats={unlocks:0,effects:0,crowdStarts:0,lastType:""};
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}"),rate:.74,pitch:.94}}catch{return{...defaults}}}function save(){localStorage.setItem(KEY,JSON.stringify(settings));sync();renderControls()}
function ensureContext(){if(ctx)return ctx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;ctx=new AC();masterBus=ctx.createGain();fxBus=ctx.createGain();fxBus.connect(masterBus);masterBus.connect(ctx.destination);sync();return ctx}
function makeAudio(src,loop=false){const a=new Audio(src);a.preload="metadata";a.loop=loop;a.playsInline=true;return a}
function ensureMedia(){if(crowd)return;crowd=makeAudio(CROWD,true);cheer=makeAudio(CHEER);react=makeAudio(REACT);crowd.volume=.001;cheer.volume=.56;react.volume=.34}
function unlock(){ensureContext();ensureMedia();ctx?.resume?.();if(unlocked){sync();return true}unlocked=true;stats.unlocks++;crowd.preload="auto";cheer.preload="auto";react.preload="auto";crowd.play().then(()=>{stats.crowdStarts++;sync()}).catch(()=>{});sync();return true}
function matchActive(){return!!document.querySelector("#v7-match.active,#v7-online-match.active")}
function sync(){const on=settings.enabled!==false;if(masterBus&&ctx)masterBus.gain.setTargetAtTime(on?settings.master:0,ctx.currentTime,.05);if(crowd&&unlocked){const should=on&&settings.crowd!==false&&matchActive();crowd.volume=should?clamp(settings.crowdVolume*.85,.04,.28):.001;if(should&&crowd.paused)crowd.play().catch(()=>{})}}
function noise(dur=.12,gain=.08,freq=800){if(!ctx||!unlocked||!settings.effects||!settings.enabled)return;const n=Math.max(64,Math.floor(ctx.sampleRate*dur)),b=ctx.createBuffer(1,n,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),t=ctx.currentTime;src.buffer=b;f.type="bandpass";f.frequency.value=freq;f.Q.value=.7;g.gain.value=gain*settings.effectVolume;src.connect(f);f.connect(g);g.connect(fxBus);src.start(t)}
function tone(freq,dur=.12,gain=.07,end=null){if(!ctx||!unlocked||!settings.effects||!settings.enabled)return;const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime;o.type="sine";o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain*settings.effectVolume,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(fxBus);o.start(t);o.stop(t+dur+.03)}
function playMedia(a,vol){if(!a||!unlocked||!settings.enabled)return;try{a.pause();a.currentTime=0;a.volume=clamp(vol*settings.master,0,1);a.play().catch(()=>{})}catch{}}
function effect(type){stats.effects++;stats.lastType=type;if(type==="goal"){playMedia(cheer,.72);noise(.18,.12,520);tone(240,.22,.06,360)}else if(type==="save"){playMedia(react,.34);noise(.1,.08,680)}else if(type==="post"){playMedia(react,.42);tone(1320,.25,.08,820)}else if(type==="miss"){playMedia(react,.28);noise(.12,.05,480)}else if(type==="kickoff"||type==="half"||type==="final"){tone(1750,.18,.07,2250)}else if(type==="card"){tone(1500,.12,.05,1900)}}
function ensureControls(){let dock=document.getElementById("qfAudioDock");if(dock)dock.innerHTML="";else{dock=document.createElement("div");dock.id="qfAudioDock";dock.className="qf-audio-dock v13-audio-dock";document.body.appendChild(dock)}dock.innerHTML=`<button id="qfAudioToggle" class="qf-audio-toggle" type="button">🎙️ SPİKER</button><div id="qfAudioPanel" class="qf-audio-panel v13-audio-panel" hidden><div class="v13-audio-head"><b>Maç Spikeri</b><small>Canlı yayın</small></div><label class="v13-spiker-switch"><input id="v13CommentaryToggle" type="checkbox"> <span>Spiker sesi</span></label><div class="qf-audio-range v13-volume"><span>Ses seviyesi</span><input id="v13CommentaryVolume" type="range" min="0" max="1" step="0.05"><b id="v13CommentaryValue"></b></div></div>`;dock.querySelector("#qfAudioToggle").onclick=()=>{unlock();const p=dock.querySelector("#qfAudioPanel");p.hidden=!p.hidden;renderControls()};dock.querySelector("#v13CommentaryToggle").onchange=e=>{settings.commentary=e.target.checked;save();if(!settings.commentary)window.speechSynthesis?.cancel?.()};dock.querySelector("#v13CommentaryVolume").oninput=e=>{settings.commentator=+e.target.value;save()};renderControls()}
function renderControls(){const dock=document.getElementById("qfAudioDock");if(!dock)return;const t=dock.querySelector("#v13CommentaryToggle"),r=dock.querySelector("#v13CommentaryVolume"),v=dock.querySelector("#v13CommentaryValue"),b=dock.querySelector("#qfAudioToggle");if(t)t.checked=!!settings.commentary;if(r)r.value=settings.commentator;if(v)v.textContent=`${Math.round(settings.commentator*100)}%`;if(b)b.textContent=settings.commentary?"🎙️ SPİKER":"🔇 SPİKER"}
function setSetting(k,v){if(!(k in defaults))return false;if(k==="rate"){settings.rate=.74;save();return true}if(k==="pitch"){settings.pitch=.94;save();return true}if(typeof defaults[k]==="boolean")settings[k]=!!v;else settings[k]=clamp(+v,0,1.5);save();return true}
function classify(text){const t=String(text||"").toLocaleLowerCase("tr-TR");if(/gol/.test(t))return"goal";if(/direk/.test(t))return"post";if(/kurtar/.test(t))return"save";if(/auta|dışarı/.test(t))return"miss";if(/kart/.test(t))return"card";return"event"}
function processText(text){const type=classify(text);if(["goal","post","save","miss","card"].includes(type))effect(type);return type}
function poll(){const on=matchActive();if(on&&!active){active=true;mode=document.getElementById("v7OnlineCanvas")?"online":"solo";unlock();effect("kickoff")}else if(!on&&active){active=false;mode="";effect("final")}sync()}
window.addEventListener("qf:v11-commentary",e=>{const d=e.detail||{};if(d.final&&["goal","save","post","miss"].includes(d.type))effect(d.type)});
window.addEventListener("qf:v9-event",e=>{const d=e.detail||{};if(["card","half"].includes(d.type))effect(d.type)});
document.addEventListener("pointerdown",()=>unlock(),{once:true,capture:true});document.addEventListener("keydown",e=>{if(!unlocked)unlock();if(e.key?.toLowerCase()==="m"&&!/input|textarea|select/i.test(document.activeElement?.tagName||"")){settings.commentary=!settings.commentary;save();if(!settings.commentary)window.speechSynthesis?.cancel?.()}},{capture:true});
function boot(){settings.rate=.74;settings.pitch=.94;ensureMedia();ensureControls();setInterval(poll,1000);poll()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
const api={unlock,processText,testEvent:type=>effect(type),classify,getSettings:()=>({...settings}),setSetting,state:()=>({...stats,active,mode,unlocked}),effect,renderControls};window.QF_AUDIO_V13=api;window.QF_AUDIO_V8=api;
})();
