(()=>{"use strict";
const KEY="qf-v8-audio";
const defaults={enabled:true,commentary:true,effects:true,crowd:true,captions:true,master:.78,commentator:.9,effectVolume:.78,crowdVolume:.18,rate:1.08,pitch:.9};
let settings=load(),ctx=null,master=null,fxBus=null,crowdBus=null,crowdSource=null,unlocked=false,active=false,mode="",seen=new Set(),halfSaid=false,lateSaid=false,lastSpeechAt=0,speechQueue=[],speaking=false,lastScore=null,lastMatchSnapshot=null,pollTimer=0,captionTimer=0,voice=null;
const stats={events:0,sfx:0,speechAttempts:0,lastType:"",lastCaption:"",unlocks:0};
const $=s=>document.querySelector(s),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=a=>a[Math.floor(Math.random()*a.length)];
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(settings));applyVolumes();renderControls()}
function ensureContext(){if(ctx)return ctx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;ctx=new AC();master=ctx.createGain();fxBus=ctx.createGain();crowdBus=ctx.createGain();fxBus.connect(master);crowdBus.connect(master);master.connect(ctx.destination);startCrowd();applyVolumes();return ctx}
function unlock(){const c=ensureContext();if(!c)return false;c.resume?.();unlocked=true;stats.unlocks++;applyVolumes();return true}
function applyVolumes(){if(!ctx||!master)return;const now=ctx.currentTime;master.gain.setTargetAtTime(settings.enabled?settings.master:0,now,.04);fxBus.gain.setTargetAtTime(settings.effects?settings.effectVolume:0,now,.04);const crowdTarget=active&&settings.crowd?settings.crowdVolume*crowdIntensity():0;crowdBus.gain.setTargetAtTime(crowdTarget,now,.16)}
function crowdIntensity(){const snap=getSnapshot(),minute=snap.minute||0,diff=Math.abs((snap.own||0)-(snap.opp||0));return clamp(.58+(minute/90)*.15+(diff<=1?.13:0)+(snap.momentum||0)/700,.45,1)}
function startCrowd(){if(!ctx||crowdSource)return;const len=Math.floor(ctx.sampleRate*2),b=ctx.createBuffer(1,len,ctx.sampleRate),d=b.getChannelData(0);let v=0;for(let i=0;i<len;i++){v=v*.975+(Math.random()*2-1)*.12;d[i]=v*.42}const src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=b;src.loop=true;filter.type="lowpass";filter.frequency.value=950;filter.Q.value=.5;g.gain.value=.48;src.connect(filter);filter.connect(g);g.connect(crowdBus);src.start();crowdSource=src}
function tone(freq,dur=.12,gain=.15,type="sine",delay=0,endFreq=null){if(!ctx||!settings.effects||!settings.enabled)return;const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(Math.max(20,endFreq),t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain),t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(fxBus);o.start(t);o.stop(t+dur+.02)}
function noise(dur=.12,gain=.12,freq=1200,delay=0){if(!ctx||!settings.effects||!settings.enabled)return;const len=Math.max(64,Math.floor(ctx.sampleRate*dur)),b=ctx.createBuffer(1,len,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*(1-i/len);const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),t=ctx.currentTime+delay;src.buffer=b;f.type="bandpass";f.frequency.value=freq;f.Q.value=.8;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);src.connect(f);f.connect(g);g.connect(fxBus);src.start(t);src.stop(t+dur+.02)}
function swell(kind="cheer",power=1){if(!ctx||!settings.effects||!settings.enabled)return;const dur=kind==="cheer"?1.8:1.05,len=Math.floor(ctx.sampleRate*dur),b=ctx.createBuffer(1,len,ctx.sampleRate),d=b.getChannelData(0);let low=0;for(let i=0;i<len;i++){low=low*.94+(Math.random()*2-1)*.18;const env=Math.sin(Math.PI*i/len);d[i]=low*env*.7}const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),t=ctx.currentTime;src.buffer=b;f.type="bandpass";f.frequency.value=kind==="cheer"?720:330;f.Q.value=.55;g.gain.value=.18*power;src.connect(f);f.connect(g);g.connect(fxBus);src.start(t)}
function effect(type,intensity=1){if(!unlocked)ensureContext();stats.sfx++;switch(type){case"kickoff":tone(1850,.22,.11,"sine",0,2450);tone(1650,.16,.08,"sine",.28,2200);break;case"kick":noise(.09,.16*intensity,520);tone(92,.12,.13*intensity,"sine",0,55);break;case"correct":tone(660,.09,.08,"sine");tone(880,.13,.07,"sine",.08);break;case"wrong":tone(190,.18,.09,"square",0,120);break;case"miss":effect("kick",.8);noise(.26,.08,1650,.08);swell("groan",.65);break;case"save":effect("kick",.65);noise(.08,.15,650,.1);tone(145,.12,.08,"sine",.08,85);break;case"post":effect("kick",.75);tone(1180,.34,.12,"triangle",.1,760);tone(1770,.23,.06,"sine",.12,1120);swell("groan",.75);break;case"goal":effect("kick",1);swell("cheer",1.35);tone(330,.2,.09,"sawtooth",.12,440);tone(440,.27,.08,"sawtooth",.22,660);tone(660,.32,.07,"sawtooth",.33,880);break;case"concede":tone(135,.45,.12,"triangle",0,70);swell("groan",1.05);break;case"halftime":tone(1800,.2,.09,"sine",0,2350);tone(1800,.2,.09,"sine",.3,2350);break;case"final":tone(1950,.2,.1,"sine",0,2500);tone(1950,.2,.1,"sine",.28,2500);tone(2050,.3,.11,"sine",.57,2700);break;}}
function findVoice(){const voices=window.speechSynthesis?.getVoices?.()||[];voice=voices.find(v=>/^tr([-_]|$)/i.test(v.lang))||voices.find(v=>/turk|türk/i.test(v.name))||null;return voice}
if(window.speechSynthesis){findVoice();window.speechSynthesis.onvoiceschanged=findVoice}
function caption(text){stats.lastCaption=text;if(!settings.captions)return;let el=$("#qfCommentaryCaption");if(!el){el=document.createElement("div");el.id="qfCommentaryCaption";el.className="qf-commentary-caption";document.body.appendChild(el)}el.textContent=text;el.classList.add("show");clearTimeout(captionTimer);captionTimer=setTimeout(()=>el.classList.remove("show"),4200)}
function say(text,{priority=4,interrupt=false}={}){caption(text);if(!settings.enabled||!settings.commentary||window.QF_COMMENTARY_V10_SUPPRESS_V8||!window.speechSynthesis)return;stats.speechAttempts++;const now=Date.now();if(priority<7&&now-lastSpeechAt<1900)return;if(interrupt||priority>=9){speechQueue.length=0;window.speechSynthesis.cancel();speaking=false}speechQueue.push({text,priority});speechQueue.sort((a,b)=>b.priority-a.priority);if(speechQueue.length>3)speechQueue.length=3;drainSpeech()}
function drainSpeech(){if(speaking||!speechQueue.length||!settings.commentary)return;const item=speechQueue.shift(),u=new SpeechSynthesisUtterance(item.text);u.lang="tr-TR";u.rate=settings.rate;u.pitch=settings.pitch;u.volume=clamp(settings.master*settings.commentator,0,1);if(voice)u.voice=voice;speaking=true;lastSpeechAt=Date.now();u.onend=u.onerror=()=>{speaking=false;setTimeout(drainSpeech,70)};window.speechSynthesis.speak(u)}
const lines={
kickoff:["Hakemin düdüğüyle maç başladı. İki takım da ilk dakikadan itibaren oyunun içinde.","Maç başladı. Başkan locasında gözler sahada, şimdi söz futbolcularda.","İlk düdük geldi. Doksan dakikalık futbol, iki dakikalık yüksek tempoya sığacak."],
correct:["Doğru cevap! Hücum momentumu yükseliyor.","Harika bildin. Takım şimdi daha cesur hücum edecek.","Doğru seçim. Baskı artıyor, rakip savunma geri çekiliyor."],
wrong:["Yanlış cevap. Hücum temposu biraz düştü.","Bu kez olmadı. Rakip nefes aldı.","Yanlış seçim; momentum kaybı var ama maç devam ediyor."],
miss:["Şut geldi... dışarıda! Çok önemli bir fırsat kaçtı.","Ceza alanında fırsat vardı ama vuruş kaleyi bulmadı.","Tehlikeli geldiler, son vuruş isabetsiz."],
save:["Şut geldi, kaleci çıkardı! Çok kritik bir kurtarış.","Kaleci gole izin vermiyor. Refleksleri mükemmel.","Net fırsat! Kaleci son anda uzandı ve kurtardı."],
post:["Direk! Top direkten geri geliyor, inanılmaz bir an.","Vuruş direkte patladı! Gol birkaç santimetreyle kaçtı.","Kaleci bakakaldı ama direk gole izin vermedi."],
defense:["Savunma zamanında araya girdi ve tehlikeyi uzaklaştırdı.","Rakip geldi ama savunma çizgisi bozulmadı.","Kritik müdahale. Hücum daha şuta dönüşmeden kesildi."],
late:["Son on dakikaya giriyoruz. Bundan sonra her doğru cevap, her hücum çok daha değerli.","Maçın son bölümü. Tek bir an bütün sonucu değiştirebilir."],
half:["Kırk beşinci dakika geride kaldı. Oyun hız kesmeden ikinci yarıya geçiyor.","İlk yarının sonu. Skor hâlâ değişebilir; ikinci bölüm hemen başlıyor."],
final:["Ve son düdük geldi. Maç tamamlandı.","Hakem maçı bitirdi. İki dakikalık yoğun mücadele sona erdi."]};
function getSnapshot(){const online=!!$("#v7OnlineCanvas"),solo=!!$("#v7MatchCanvas"),mine=window.QF_V7_CORE?.clubSnapshot?.()||{};let leftName=$("#v7-match .v7-scoreboard .v7-team-name:first-child b")?.textContent?.trim()||"",rightName=$("#v7-match .v7-scoreboard .v7-team-name:last-child b")?.textContent?.trim()||"",home=+(online?$("#v7OnH")?.textContent:$("#v7HomeScore")?.textContent)||0,away=+(online?$("#v7OnA")?.textContent:$("#v7AwayScore")?.textContent)||0,minute=parseInt((online?$("#v7OnMin")?.textContent:$("#v7Minute")?.textContent)||"0",10)||0,momentum=0;if(online){const leftMine=leftName===mine.name;momentum=parseInt((leftMine?$("#v7OnHM"):$("#v7OnAM"))?.textContent||"0",10)||0;return{online,solo,minute,own:leftMine?home:away,opp:leftMine?away:home,ownName:mine.name||"Takımımız",ownShort:mine.short||"QF",leftName,rightName,momentum}}momentum=parseInt($("#v7MomentumText")?.textContent||"0",10)||0;return{online,solo,minute,own:home,opp:away,ownName:mine.name||leftName||"Takımımız",ownShort:mine.short||"QF",leftName,rightName,momentum}}
function goalLine(against=false){const s=getSnapshot(),score=`Skor ${s.own}-${s.opp}.`;if(against){if(s.own===s.opp)return`Golü yedik. Rakip eşitliği sağladı. ${score}`;if(s.opp>s.own&&s.minute>=80)return`Çok kritik bir gol yedik. Son dakikalarda rakip öne geçti. ${score}`;return`${pick(["Rakip golü buldu.","Maalesef top ağlarımızda.","Rakip bu fırsatı affetmedi."])} ${score}`}
if(s.own===s.opp)return`GOL! ${s.ownName} eşitliği yakalıyor. ${score}`;if(s.own>s.opp&&s.own-s.opp===1)return`GOL! ${s.ownName} öne geçiyor! ${score}`;if(s.minute>=80)return`GOL! Son dakikalarda çok değerli bir gol! ${score}`;return`${pick(["GOL! Müthiş bir bitiriş!","GOL! Baskının karşılığı geldi!","GOL! Top ağlarda, tribünler ayağa kalktı!"])} ${score}`}
function isMineEvent(text){const t=(text||"").toLocaleLowerCase("tr-TR"),own=(window.QF_V7_CORE?.clubSnapshot?.().short||"").toLocaleLowerCase("tr-TR");if(/rakibin|kalecimiz|savunma rakip/.test(t))return false;if(own&&(t.includes(`${own} şut`)||t.includes(`${own} dire`)))return true;return mode!=="online"}
function classify(text){const t=(text||"").toLocaleLowerCase("tr-TR");const ownShort=(window.QF_V7_CORE?.clubSnapshot?.().short||"").toLocaleLowerCase("tr-TR");if(/doğru cevap/.test(t))return"correct";if(/yanlış cevap/.test(t))return"wrong";if(/rakip golü/.test(t))return"goal_against";if(/\bgol\b/.test(t)){if(/gol! quiz/.test(t))return"goal_for";const m=t.match(/gol\s+([^!]+)!/);if(m&&ownShort)return m[1].trim()===ownShort?"goal_for":"goal_against";return"goal_for"}if(/direk/.test(t))return"post";if(/kaleci.*kurtar|kurtardı/.test(t))return"save";if(/şut.*dışarı|şut.*auta|vuruş.*dışarı/.test(t))return"miss";if(/savunma.*durdur|savunma.*araya|müdahale/.test(t))return"defense";return"generic"}
function dispatch(type,text=""){stats.events++;stats.lastType=type;switch(type){case"correct":effect("correct");say(pick(lines.correct),{priority:3});break;case"wrong":effect("wrong");say(pick(lines.wrong),{priority:2});break;case"miss":effect("miss");say(isMineEvent(text)?pick(lines.miss):pick(["Rakibin şutu dışarıda. Tehlikeyi atlattık.","Rakip önemli fırsattan yararlanamadı; top kaleyi bulmadı."]),{priority:4});break;case"save":effect("save");say(isMineEvent(text)?pick(["Şutumuz geldi ama rakip kaleci kurtardı.","Net fırsatta rakip kaleci gole izin vermedi."]):pick(lines.save),{priority:5});break;case"post":effect("post");say(isMineEvent(text)?pick(lines.post):pick(["Rakip direkte takıldı! Büyük tehlike atlattık.","Rakibin vuruşu direkten geri geldi; şans bizim yanımızda."]),{priority:7});break;case"defense":effect("save",.7);say(pick(lines.defense),{priority:3});break;case"goal_for":effect("goal");say(goalLine(false),{priority:10,interrupt:true});break;case"goal_against":effect("concede");say(goalLine(true),{priority:10,interrupt:true});break;case"kickoff":effect("kickoff");say(pick(lines.kickoff),{priority:8,interrupt:true});break;case"half":effect("halftime");say(pick(lines.half),{priority:7});break;case"late":say(pick(lines.late),{priority:7});break;case"final":effect("final");say(`${pick(lines.final)} ${lastMatchSnapshot?`Son skor ${lastMatchSnapshot.own}-${lastMatchSnapshot.opp}.`:""}`,{priority:9,interrupt:true});break;default:if(text&&Math.random()<.18)say(text.replace(/^\d+'\s*/,""),{priority:1})}}
function processText(text){if(!text)return;const key=`${mode}:${text}`;if(seen.has(key))return;seen.add(key);if(seen.size>120){const arr=[...seen].slice(-80);seen=new Set(arr)}dispatch(classify(text),text)}
function currentLogTexts(){const root=$("#v7OnLog")||$("#v7EventLog");return root?[...root.children].map(x=>x.textContent.trim()).filter(Boolean):[]}
function isMatchActive(){const m=$("#v7-match");return!!(m?.classList.contains("active")&&($("#v7MatchCanvas")||$("#v7OnlineCanvas")))}
function enterMatch(){active=true;mode=$("#v7OnlineCanvas")?"online":"solo";seen=new Set(currentLogTexts().map(x=>`${mode}:${x}`));halfSaid=false;lateSaid=false;lastScore=getSnapshot();lastMatchSnapshot=lastScore;ensureControls();applyVolumes();setTimeout(()=>dispatch("kickoff"),180)}
function leaveMatch(){if(!active)return;lastMatchSnapshot=lastScore||lastMatchSnapshot;active=false;applyVolumes();dispatch("final");mode=""}
function poll(){const nowActive=isMatchActive();if(nowActive&&!active)enterMatch();else if(!nowActive&&active)leaveMatch();if(!active)return;ensureControls();const texts=currentLogTexts();for(let i=texts.length-1;i>=0;i--)processText(texts[i]);const s=getSnapshot();lastMatchSnapshot=s;lastScore=s;if(!halfSaid&&s.minute>=45){halfSaid=true;dispatch("half")}if(!lateSaid&&s.minute>=80){lateSaid=true;dispatch("late")}applyVolumes()}
function ensureControls(){if($("#qfAudioDock"))return;const dock=document.createElement("div");dock.id="qfAudioDock";dock.className="qf-audio-dock";dock.innerHTML=`<button id="qfAudioToggle" class="qf-audio-toggle" type="button">SES</button><div id="qfAudioPanel" class="qf-audio-panel" hidden><div class="qf-audio-title"><b>Maç Sesi</b><small>Türkçe spiker + stadyum</small></div><label class="qf-audio-check"><input type="checkbox" data-audio-bool="enabled"> Tüm sesler</label><label class="qf-audio-check"><input type="checkbox" data-audio-bool="commentary"> Türkçe spiker</label><label class="qf-audio-check"><input type="checkbox" data-audio-bool="effects"> Maç efektleri</label><label class="qf-audio-check"><input type="checkbox" data-audio-bool="crowd"> Tribün ambiyansı</label><label class="qf-audio-check"><input type="checkbox" data-audio-bool="captions"> Spiker altyazısı</label><div class="qf-audio-range"><span>Ana ses</span><input type="range" min="0" max="1" step="0.05" data-audio-range="master"><b data-audio-value="master"></b></div><div class="qf-audio-range"><span>Spiker</span><input type="range" min="0" max="1" step="0.05" data-audio-range="commentator"><b data-audio-value="commentator"></b></div><div class="qf-audio-range"><span>Efekt</span><input type="range" min="0" max="1" step="0.05" data-audio-range="effectVolume"><b data-audio-value="effectVolume"></b></div><div class="qf-audio-range"><span>Tribün</span><input type="range" min="0" max="0.5" step="0.025" data-audio-range="crowdVolume"><b data-audio-value="crowdVolume"></b></div><button class="qf-audio-test" id="qfAudioTest" type="button">Sesi Test Et</button><small class="qf-audio-note">İlk tıklamadan sonra ses etkinleşir. M tuşu tüm sesi açar/kapatır.</small></div>`;document.body.appendChild(dock);$("#qfAudioToggle").onclick=()=>{unlock();const p=$("#qfAudioPanel");p.hidden=!p.hidden;renderControls()};$("#qfAudioTest").onclick=()=>{unlock();effect("goal");say("Gol! Ses sistemi hazır. Türkçe spiker ve stadyum efektleri aktif.",{priority:10,interrupt:true})};dock.querySelectorAll("[data-audio-bool]").forEach(i=>i.onchange=()=>{settings[i.dataset.audioBool]=i.checked;save()});dock.querySelectorAll("[data-audio-range]").forEach(i=>i.oninput=()=>{settings[i.dataset.audioRange]=+i.value;save()});renderControls()}
function renderControls(){const dock=$("#qfAudioDock");if(!dock)return;dock.querySelectorAll("[data-audio-bool]").forEach(i=>i.checked=!!settings[i.dataset.audioBool]);dock.querySelectorAll("[data-audio-range]").forEach(i=>{i.value=settings[i.dataset.audioRange];const b=dock.querySelector(`[data-audio-value="${i.dataset.audioRange}"]`);if(b)b.textContent=`${Math.round(settings[i.dataset.audioRange]*100)}%`});const t=$("#qfAudioToggle");if(t)t.textContent=settings.enabled?"SES":"SESSİZ"}
function setSetting(k,v){if(!(k in defaults))return false;settings[k]=typeof defaults[k]==="boolean"?!!v:clamp(+v,0,1.5);save();return true}
function testEvent(type){dispatch(type,`QA ${type}`)}
document.addEventListener("pointerdown",unlock,{once:true,capture:true});document.addEventListener("keydown",e=>{if(!unlocked)unlock();if(e.key?.toLowerCase()==="m"&&!/input|textarea|select/i.test(document.activeElement?.tagName||"")){settings.enabled=!settings.enabled;save()}},{capture:true});
pollTimer=setInterval(poll,260);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(poll,50),{once:true});else setTimeout(poll,50);
window.addEventListener("qf:v9-event",e=>{const d=e.detail||{};if(!active)return;if(d.type==="card"){effect("wrong",.45);say(d.text,{priority:5})}else if(d.type==="corner"){effect("kick",.45);say(d.text,{priority:4})}else if(d.type==="offside"){tone(1750,.15,.06,"sine",0,2250);say(d.text,{priority:4})}else if(d.type==="injury"){tone(220,.24,.06,"triangle",0,150);say(d.text,{priority:5})}else if(d.type==="sub"){tone(720,.08,.04,"sine");say(d.text,{priority:4})}else if(d.type==="half"){effect("halftime");say(d.text,{priority:8,interrupt:true})}});
window.QF_AUDIO_V8={unlock,processText,testEvent,classify,getSettings:()=>({...settings}),setSetting,state:()=>({...stats,active,mode,unlocked,voice:voice?.name||"",snapshot:getSnapshot()})};
})();