(()=>{"use strict";
const KEY="qf-v15-simulator",clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let mode=(localStorage.getItem(KEY)==="2d"?"2d":"3d"),lastUi=0,lastAmbient=0,phase=0,wrapped=false,controlHost=null;
const state={mode,ambientTicks:0,paceWraps:0,lastEventType:"",eventHoldMs:0,controls:0};
function source(){const on=document.getElementById("v7OnlineCanvas");if(on){const n=window.QF_V7_ONLINE_TEST?.net?.();if(n?.match?.running&&n.match.v9)return{canvas:on,v:n.match.v9,match:n.match,online:true}}const solo=document.getElementById("v7MatchCanvas");if(solo){const m=window.QF_V7_TEST?.match?.();if(m?.running&&m.v9)return{canvas:solo,v:m.v9,match:m,online:false}}return null}
function applyMode(next=mode){mode=next==="2d"?"2d":"3d";state.mode=mode;localStorage.setItem(KEY,mode);try{window.QF_MATCH_3D_V13?.setSetting?.("enabled",mode==="3d");if(mode==="2d")window.QF_MATCH_3D_V13?.detach?.()}catch{}updateControl()}
function ensureControl(src){if(!src?.canvas?.parentElement)return;const host=src.canvas.parentElement;if(controlHost===host&&document.getElementById("v15SimulatorSwitch"))return;document.getElementById("v15SimulatorSwitch")?.remove();controlHost=host;host.style.position="relative";const el=document.createElement("div");el.id="v15SimulatorSwitch";el.className="v15-sim-switch";el.innerHTML='<span class="v15-sim-label">SİMÜLATÖR</span><button type="button" data-v15-mode="3d">3D</button><button type="button" data-v15-mode="2d">2D</button><span class="v15-live">● CANLI</span>';el.addEventListener("click",e=>{const b=e.target.closest("button[data-v15-mode]");if(!b)return;applyMode(b.dataset.v15Mode)});host.appendChild(el);state.controls++;updateControl()}
function updateControl(){const el=document.getElementById("v15SimulatorSwitch");if(!el)return;el.querySelectorAll("button[data-v15-mode]").forEach(b=>b.classList.toggle("active",b.dataset.v15Mode===mode));const live=el.querySelector(".v15-live"),m=source()?.match;if(live)live.textContent=m?`● ${Math.min(90,Math.round(m.minute||0))}' • ${mode.toUpperCase()}`:`● ${mode.toUpperCase()}`}
function flowBusy(){try{return!!window.QF_MATCH_FLOW_V11?.state?.().busy}catch{return false}}
function ambient(src,t){if(!src?.v?.visual||flowBusy())return;const v=src.v,vis=v.visual,ball=vis.ball;if(!ball)return;phase++;state.ambientTicks++;const ownHome=(v.possessionHome??50)>=48+(phase%3-1)*2;const active=ownHome?vis.home:vis.away,other=ownHome?vis.away:vis.home;if(!active?.length||!other?.length)return;const holders=[5,6,7,8,10,9],hi=holders[phase%holders.length]%active.length,holder=active[hi];const sidePush=ownHome?.018:-.018,tempo=Math.sin(phase*.63)*.012;for(const [team,dir] of [[vis.home,1],[vis.away,-1]])team.forEach((p,i)=>{const bx=p.baseX??p.x,by=p.baseY??p.y,lane=Math.sin(phase*.47+i*1.13)*.014,shape=(ball.x-.5)*.035;p.tx=clamp(bx+shape+dir*.008+tempo*(i%2?1:-1),.035,.965);p.ty=clamp(by+lane+(ball.y-.5)*.045,.035,.965)});if(holder){holder.tx=clamp((holder.baseX??holder.x)+sidePush+.025*Math.sin(phase*.71),.06,.94);holder.ty=clamp((holder.baseY??holder.y)+.035*Math.sin(phase*.41),.08,.92);ball.tx=clamp(holder.tx+(ownHome?.018:-.018),.04,.96);ball.ty=holder.ty}const f=vis.focus;if(f){f.targetX=ball.tx;f.targetY=ball.ty}}
function eventHold(type){return["goal","save","post","miss","penalty"].includes(type)?1900:["corner","free","card","red","injury","sub","half"].includes(type)?1150:800}
function wrapPace(){if(wrapped||!window.QF_MATCH_V9)return;for(const k of["stepSolo","stepOnline"]){const old=window.QF_MATCH_V9[k];if(typeof old!=="function")continue;window.QF_MATCH_V9[k]=function(match,ctx){const ev=old.call(this,match,ctx);if(ev){const hold=eventHold(ev.type),base=ctx?.now||performance.now();match.lastEvent=Math.max(match.lastEvent||0,base+hold);state.paceWraps++;state.lastEventType=ev.type||"";state.eventHoldMs=hold}return ev}}
wrapped=true}
function loop(t){wrapPace();const src=source();if(src){ensureControl(src);if(t-lastUi>280){lastUi=t;applyMode(mode);updateControl()}if(t-lastAmbient>760){lastAmbient=t;ambient(src,t)}}else{document.getElementById("v15SimulatorSwitch")?.remove();controlHost=null}requestAnimationFrame(loop)}
window.addEventListener("storage",e=>{if(e.key===KEY)applyMode(e.newValue)});
window.QF_BROADCAST_V15={state:()=>({...state,mode}),setMode:applyMode,ambientNow:()=>{const s=source();if(s)ambient(s,performance.now())}};
applyMode(mode);requestAnimationFrame(loop);
})();
