(()=>{"use strict";
const CORE=()=>window.QF_V7_CORE,X=()=>window.QF_V7,D=()=>window.QF_DATA||{},clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),fmt=n=>`€${(+n||0).toFixed(n<10?1:0)}M`,pick=a=>a[Math.floor(Math.random()*a.length)];
const first=["Arda","Kerem","Mert","Emir","Can","Eren","Baran","Deniz","Luka","Mateo","Noah","Leo","Milan","Nico","Alex","Theo","Jonas","Hugo"],last=["Kaya","Demir","Yılmaz","Aydın","Koç","Costa","Silva","Martin","Lopez","Meyer","Rossi","Nielsen","Santos","Vega","Moretti","Kovac","Petrov","Larsen"];
const positions=["GK","CB","CB","LB","RB","CM","CM","CAM","LW","RW","ST"];
function state(){return CORE()?.state?.()||null}
function ensure(){const S=state();if(!S)return null;S.v9 ||= {version:9,clubOffice:true,lastProcessedWeek:0,contracts:{},academy:[],shortlist:[],worldNews:[],seasonAwards:[],records:{bestWin:null,longestRun:0,currentRun:0},sponsorOfferWeek:0,sponsorOffers:[],scoutReports:[],aiMarket:[],seasonHistory:[]};for(const id of S.squad||[]){const p=X()?.playerMeta?.[id];S.v9.contracts[id]||={years:2+((hash(id)%4)),wageM:p?.wageM||.5,happiness:68+(hash(id+"h")%25),status:"active"};if(p&&S.v9.contracts[id].wageM)p.wageM=S.v9.contracts[id].wageM}registerAcademy(S);generateOffers(S);CORE()?.save?.();return S.v9}
function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function registerAcademy(S){for(const p of S.v9?.academy||[]){X().playerMeta[p.id] ||= {...p};D().players[p.id] ||= {id:p.id,name:p.name,clubs:[],academy:true}}}
function generateOffers(S,force=false){const v=S.v9;if(!force&&v.sponsorOffers.length&&v.sponsorOfferWeek===S.week)return;const rep=S.boardRep||50,base=1.1+rep/75;v.sponsorOffers=[{id:"nova",name:"Nova Sports",weeklyM:+(base*.92).toFixed(2),signM:+(4+rep*.05).toFixed(1),bonus:"Lig şampiyonluğu +€8M"},{id:"atlas",name:"Atlas Air",weeklyM:+(base*1.05).toFixed(2),signM:+(2.5+rep*.04).toFixed(1),bonus:"Her 5 galibiyet +€2M"},{id:"titan",name:"Titan Tech",weeklyM:+(base*.82).toFixed(2),signM:+(6+rep*.03).toFixed(1),bonus:"Kupa kazanımı +€5M"}];v.sponsorOfferWeek=S.week}
function youthName(seed){return`${first[seed%first.length]} ${last[Math.floor(seed/7)%last.length]}`}
function generateYouth(S,count=3){const v=S.v9;for(let i=0;i<count;i++){const seed=hash(`${S.season}-${S.week}-${Date.now()}-${i}`),pos=positions[seed%positions.length],ovr=52+(seed%16),pot=Math.min(95,ovr+12+(seed%18)),id=`YA${S.season}${S.week}${seed.toString(36).slice(-5)}`;v.academy.push({id,name:youthName(seed),pos,ovr,potential:pot,age:15+(seed%4),pace:55+(seed%25),shot:pos==="ST"||pos==="RW"||pos==="LW"?58+(seed%24):45+(seed%20),pass:50+(seed%26),dribble:50+(seed%27),defense:["CB","LB","RB"].includes(pos)?60+(seed%22):38+(seed%18),physical:50+(seed%29),finish:pos==="ST"?62+(seed%23):48+(seed%20),valueM:+(.4+(pot-70)*.08+(ovr-52)*.05).toFixed(1),wageM:+(.08+(ovr-50)*.008).toFixed(2),academy:true})}registerAcademy(S)}
function promote(id){const S=state(),v=ensure(),p=v.academy.find(x=>x.id===id);if(!p||S.squad.includes(id))return false;if((S.squad||[]).length>=30)return toast("Kadro 30 oyuncu sınırında.");S.squad.push(id);v.contracts[id]={years:3,wageM:p.wageM,happiness:82,status:"academy"};v.academy=v.academy.filter(x=>x.id!==id);registerAcademy(S);CORE().clubSnapshot();CORE().save();renderOffice("academy");toast(`${p.name} A takıma yükseltildi.`);return true}
function renew(id){const S=state(),v=ensure(),c=v.contracts[id],p=X().playerMeta[id];if(!c||!p)return;const years=3,newWage=+(Math.max(c.wageM*1.12,p.wageM||0).toFixed(2)),bonus=+(Math.max(.3,(p.valueM||3)*.035).toFixed(1));if(S.cashM<bonus)return toast("İmza bonusu için kasa yetersiz.");S.cashM-=bonus;c.years=years;c.wageM=newWage;c.happiness=clamp(c.happiness+10,0,100);p.wageM=newWage;CORE().save();renderOffice("contracts");toast(`${p.name} ile ${years} yıllık sözleşme yenilendi.`)}
function shortlist(id){const S=state(),v=ensure();if(!v.shortlist.includes(id))v.shortlist.push(id);CORE().save();renderOffice("scout");toast("Oyuncu kısa listeye eklendi.")}
function signScouted(id){const S=state(),v=ensure(),p=X().playerMeta[id];if(!p||S.squad.includes(id))return false;if((p.valueM||0)>S.budgetM)return toast("Transfer bütçesi yetersiz.");const wageUsed=(S.squad||[]).reduce((s,x)=>s+(v.contracts[x]?.wageM||X().playerMeta[x]?.wageM||0),0)+(X().managerMeta?.[S.managerId]?.wageM||0);if(wageUsed+(p.wageM||0)>S.wageBudgetM)return toast("Maaş bütçesi yetersiz.");S.budgetM-=p.valueM;S.squad.push(id);v.contracts[id]={years:3,wageM:p.wageM,happiness:76,status:"signed"};v.shortlist=v.shortlist.filter(x=>x!==id);CORE().clubSnapshot();CORE().save();renderOffice("scout");toast(`${p.name} transfer edildi.`);return true}
function scouting(S){const v=ensure(),owned=new Set(S.squad||[]),all=Object.values(X().playerMeta||{}).filter(p=>!owned.has(p.id)&&!p.academy),scout=S.facilities?.scouting||1;const rows=all.map(p=>{const value=(p.ovr||65)*.55+(p.potential||p.ovr||65)*.3-(p.valueM||5)*.15+(hash(p.id+S.week)%10)+scout*2;return{...p,scoutScore:value,grade:value>80?"A":value>70?"B":value>60?"C":"D"}}).sort((a,b)=>b.scoutScore-a.scoutScore).slice(0,10);v.scoutReports=rows.map(x=>x.id);return rows}
function chooseSponsor(id){const S=state(),v=ensure(),o=v.sponsorOffers.find(x=>x.id===id);if(!o)return;v.sponsor={...o,season:S.season};S.cashM+=o.signM;CORE().save();renderOffice("finance");toast(`${o.name} ile sponsorluk anlaşması imzalandı.`)}
function schedule(ids){const a=[...ids];if(a.length%2)a.push("bye");const rounds=[];for(let r=0;r<a.length-1;r++){const f=[];for(let i=0;i<a.length/2;i++){const h=a[i],g=a[a.length-1-i];if(h!=="bye"&&g!=="bye")f.push(r%2?[g,h]:[h,g])}rounds.push(f);a.splice(1,0,a.pop())}return [...rounds,...rounds.map(r=>r.map(([x,y])=>[y,x]))]}
function endSeason(S){const v=ensure(),table=[...(S.table||[])].sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)),rank=table.findIndex(x=>x.id==="me")+1;v.seasonHistory.unshift({season:S.season,rank,wins:S.stats?.w||0,losses:S.stats?.l||0,trophies:S.stats?.trophies||0});v.seasonAwards.unshift({season:S.season,title:rank===1?"Lig Şampiyonu":rank<=3?"Podyum Sezonu":"Sezon Tamamlandı",rank});for(const c of Object.values(v.contracts)){c.years=Math.max(0,(c.years||1)-1);c.happiness=clamp(c.happiness+(rank<=4?4:-3),25,100);if(c.years===0)c.status="expiring"}for(const p of Object.values(X().playerMeta||{})){if(v.contracts[p.id])p.age=(p.age||24)+1}S.season++;S.week=1;for(const r of S.table||[]){Object.assign(r,{p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0})}S.schedule=schedule((S.table||[]).map(r=>r.id));S.cup={round:0,alive:true,trophy:false};generateYouth(S,3);generateOffers(S,true);v.worldNews.unshift({at:Date.now(),text:`Sezon ${S.season} başladı. Transfer piyasası yeniden hareketlendi.`})}
function worldTick(S){const v=ensure(),clubs=X().aiClubs||[],players=Object.values(X().playerMeta||{}).filter(p=>!p.academy);if(Math.random()<.7&&clubs.length&&players.length){const p=pick(players),a=pick(clubs),b=pick(clubs.filter(x=>x.id!==a.id));v.worldNews.unshift({at:Date.now(),text:`${p.name} için ${a?.name||"bir kulüp"} ile ${b?.name||"başka bir kulüp"} arasında transfer yarışı başladı.`})}if(Math.random()<.45&&clubs.length){const c=pick(clubs),delta=(Math.random()-.5)*2;c.strength=clamp(Math.round((c.strength||78)+delta),68,94);v.worldNews.unshift({at:Date.now(),text:`${c.name} form grafiğini ${delta>=0?"yukarı":"aşağı"} taşıdı; yeni güç seviyesi ${c.strength}.`})}v.worldNews=v.worldNews.slice(0,30)}
function onWeek(S,match){const v=ensure();if(v.lastProcessedWeek===`${S.season}-${S.week}`)return;v.lastProcessedWeek=`${S.season}-${S.week}`;for(const [id,c] of Object.entries(v.contracts)){const st=S.playerState?.[id];if(st?.injuryWeeks)st.injuryWeeks=Math.max(0,st.injuryWeeks-1);c.happiness=clamp(c.happiness+((S.xi||[]).includes(id)?1:-.5),20,100)}if(v.sponsor){S.cashM+=v.sponsor.weeklyM;S.finances.incomeM+=v.sponsor.weeklyM}if(match?.home>match?.away){v.records.currentRun++;v.records.longestRun=Math.max(v.records.longestRun,v.records.currentRun)}else v.records.currentRun=0;if(match&&(!v.records.bestWin||match.home-match.away>v.records.bestWin.diff))v.records.bestWin={diff:match.home-match.away,score:`${match.home}-${match.away}`,opponent:match.opponent?.name||"Rakip"};worldTick(S);if(S.week>S.schedule.length)endSeason(S);CORE().save()}
function toast(t){CORE()?.toast?.(t)}
function officeButton(){if(document.getElementById("v9OfficeBtn")||!document.querySelector(".v7-nav"))return;const b=document.createElement("button");b.id="v9OfficeBtn";b.className="v9-office-nav";b.innerHTML="<i>◆</i><span>Kulüp Ofisi</span>";const bottom=document.querySelector(".v7-nav-bottom");(bottom?.parentNode||document.querySelector(".v7-nav")).insertBefore(b,bottom||null);b.onclick=()=>openOffice("overview")}
function openOffice(tab="overview"){ensure();let el=document.getElementById("v9Office");if(!el){el=document.createElement("div");el.id="v9Office";el.className="v9-office";document.body.appendChild(el)}el.classList.add("open");renderOffice(tab)}
function closeOffice(){document.getElementById("v9Office")?.classList.remove("open")}
function rowPlayer(p,extra="",action=""){return`<div class="v9-row"><div class="v9-player-dot">${p.pos||"?"}</div><div><b>${p.name}</b><small>${p.pos||""} • OVR ${p.ovr||"-"} • POT ${p.potential||p.ovr||"-"}${extra?` • ${extra}`:""}</small></div>${action}</div>`}
function renderOffice(tab="overview"){const S=state(),v=ensure(),el=document.getElementById("v9Office");if(!el||!S)return;const tabs=[["overview","Genel"],["contracts","Sözleşmeler"],["academy","Akademi"],["scout","Scout"],["finance","Finans"],["world","Futbol Dünyası"]];el.innerHTML=`<div class="v9-office-shell"><header><div><span>CHAIRMAN OFFICE • V9</span><h2>${S.clubName}</h2></div><button id="v9OfficeClose">×</button></header><nav>${tabs.map(x=>`<button data-v9tab="${x[0]}" class="${tab===x[0]?"active":""}">${x[1]}</button>`).join("")}</nav><main id="v9OfficeBody"></main></div>`;document.getElementById("v9OfficeClose").onclick=closeOffice;el.querySelectorAll("[data-v9tab]").forEach(b=>b.onclick=()=>renderOffice(b.dataset.v9tab));const body=document.getElementById("v9OfficeBody");if(tab==="overview")body.innerHTML=overview(S,v);if(tab==="contracts")body.innerHTML=contracts(S,v);if(tab==="academy")body.innerHTML=academy(S,v);if(tab==="scout")body.innerHTML=scout(S,v);if(tab==="finance")body.innerHTML=finance(S,v);if(tab==="world")body.innerHTML=world(S,v);bindOffice(tab)}
function overview(S,v){const rank=[...(S.table||[])].sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)).findIndex(x=>x.id==="me")+1;return`<section class="v9-metrics"><div><b>${fmt(S.budgetM)}</b><span>TRANSFER</span></div><div><b>${fmt(S.cashM)}</b><span>KASA</span></div><div><b>#${rank||1}</b><span>LİG</span></div><div><b>${S.boardRep}/100</b><span>İTİBAR</span></div></section><div class="v9-grid"><section class="v9-panel"><h3>Başkan Ajandası</h3><p>Teknik direktör futbol kararlarını verir; sen bütçe, sözleşme, yatırım ve transfer politikasını yönetirsin.</p><div class="v9-list"><div><b>En uzun galibiyet serisi</b><span>${v.records.longestRun}</span></div><div><b>En farklı galibiyet</b><span>${v.records.bestWin?.score||"-"}</span></div><div><b>Akademi oyuncuları</b><span>${v.academy.length}</span></div><div><b>Scout kısa listesi</b><span>${v.shortlist.length}</span></div></div></section><section class="v9-panel"><h3>Sezon Hafızası</h3>${v.seasonHistory.slice(0,5).map(x=>`<div class="v9-history"><b>Sezon ${x.season}</b><span>Lig #${x.rank} • ${x.wins} galibiyet</span></div>`).join("")||"<p>İlk sezon devam ediyor.</p>"}</section></div>`}
function contracts(S,v){return`<section class="v9-panel"><h3>Oyuncu Sözleşmeleri</h3><p>Sözleşmesi azalan oyuncular daha yüksek maaş isteyebilir. Başkan olarak yenileme kararını sen verirsin.</p>${(S.squad||[]).map(id=>{const p=X().playerMeta[id],c=v.contracts[id];if(!p||!c)return"";return rowPlayer(p,`${c.years} yıl • ${fmt(c.wageM)}/yıl • Mutluluk ${Math.round(c.happiness)}`,`<button data-renew="${id}">Yenile</button>`)}).join("")}</section>`}
function academy(S,v){if(!v.academy.length)generateYouth(S,3);return`<section class="v9-panel"><div class="v9-panel-head"><div><h3>Gençlik Akademisi</h3><p>Yüksek akademi seviyesi daha iyi potansiyel üretir.</p></div><button id="v9YouthRefresh">Yeni İzleme</button></div>${v.academy.map(p=>rowPlayer(p,`${p.age} yaş • Değer ${fmt(p.valueM)}`,`<button data-promote="${p.id}">A Takım</button>`)).join("")}</section>`}
function scout(S,v){const rows=scouting(S);return`<section class="v9-panel"><h3>Scout Merkezi</h3><p>Scout seviyesi ${S.facilities?.scouting||1}. Raporlar OVR, potansiyel ve maliyeti birlikte değerlendirir.</p>${rows.map(p=>rowPlayer(p,`Scout ${p.grade} • ${fmt(p.valueM)} • Maaş ${fmt(p.wageM)}`,`<div class="v9-actions"><button data-short="${p.id}">Takibe Al</button><button class="primary" data-sign="${p.id}">Transfer</button></div>`)).join("")}</section>`}
function finance(S,v){return`<div class="v9-grid"><section class="v9-panel"><h3>Sponsor Teklifleri</h3>${v.sponsor?`<div class="v9-callout"><b>Aktif: ${v.sponsor.name}</b><span>${fmt(v.sponsor.weeklyM)}/hafta • ${v.sponsor.bonus}</span></div>`:""}${v.sponsorOffers.map(o=>`<div class="v9-offer"><div><b>${o.name}</b><small>${fmt(o.weeklyM)}/hafta • İmza ${fmt(o.signM)} • ${o.bonus}</small></div><button data-sponsor="${o.id}">Seç</button></div>`).join("")}</section><section class="v9-panel"><h3>Finans Özeti</h3><div class="v9-list"><div><b>Toplam gelir</b><span>${fmt(S.finances?.incomeM||0)}</span></div><div><b>Toplam gider</b><span>${fmt(S.finances?.expenseM||0)}</span></div><div><b>Transfer net</b><span>${fmt(S.finances?.transferNetM||0)}</span></div><div><b>Kasa</b><span>${fmt(S.cashM)}</span></div></div></section></div>`}
function world(S,v){return`<div class="v9-grid"><section class="v9-panel"><h3>Futbol Dünyası</h3>${v.worldNews.slice(0,12).map(n=>`<div class="v9-news"><span>●</span><p>${n.text}</p></div>`).join("")||"<p>Yeni haber yok.</p>"}</section><section class="v9-panel"><h3>Sezon Ödülleri</h3>${v.seasonAwards.slice(0,8).map(a=>`<div class="v9-history"><b>Sezon ${a.season}</b><span>${a.title} • #${a.rank}</span></div>`).join("")||"<p>İlk ödül töreni sezon sonunda.</p>"}</section></div>`}
function bindOffice(tab){const el=document.getElementById("v9Office");el?.querySelectorAll("[data-renew]").forEach(b=>b.onclick=()=>renew(b.dataset.renew));el?.querySelectorAll("[data-promote]").forEach(b=>b.onclick=()=>promote(b.dataset.promote));el?.querySelectorAll("[data-short]").forEach(b=>b.onclick=()=>shortlist(b.dataset.short));el?.querySelectorAll("[data-sign]").forEach(b=>b.onclick=()=>signScouted(b.dataset.sign));el?.querySelectorAll("[data-sponsor]").forEach(b=>b.onclick=()=>chooseSponsor(b.dataset.sponsor));const y=document.getElementById("v9YouthRefresh");if(y)y.onclick=()=>{const S=state();if((S.facilities?.academy||1)<2&&S.v9.academy.length>=3)return toast("Daha fazla izleme için akademi tesisini geliştir.");generateYouth(S,2);CORE().save();renderOffice("academy")}}
function observe(){const mo=new MutationObserver(()=>{if(document.querySelector(".v7-nav")){officeButton();ensure()}});mo.observe(document.documentElement,{childList:true,subtree:true});officeButton();ensure()}
window.QF_CAREER_V9={ensure,onWeek,openOffice,closeOffice,generateYouth,promote,renew,shortlist,signScouted,chooseSponsor,state:()=>state()?.v9||null};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(observe,0));else setTimeout(observe,0);
})();