(()=>{"use strict";
const APP_ID="6a7a33fd2bae90444c321e7e",LS="qf-v5-cloud-cache",today=()=>new Date().toISOString().slice(0,10);
const cache=()=>{try{return JSON.parse(localStorage.getItem(LS)||"{}")||{}}catch{return{}}};const save=x=>{try{localStorage.setItem(LS,JSON.stringify(x))}catch{}};
const api={status:"loading",lastError:"",client:null,ready:null};window.QFCloud=api;let client=null;
api.ready=(async()=>{try{const mod=await import("https://esm.sh/@base44/sdk");client=mod.createClient({appId:APP_ID});api.client=client;api.status="online";return true}catch(e){api.status="offline";api.lastError=String(e?.message||e);return false}})();async function online(){await api.ready;return api.status==="online"&&client}
function cleanName(v){return String(v||"").trim().replace(/[<>]/g,"").slice(0,18)}const seasonFor=k=>String(k||"").startsWith("qa-")?"QA":"S1";
function cleanProfile(p){const key=String(p.profile_key||"").slice(0,80);return{profile_key:key,username:cleanName(p.username),rating:Number(p.rating)||1000,xp:Number(p.xp)||0,level:Number(p.level)||1,games:Number(p.games)||0,wins:Number(p.wins)||0,losses:Number(p.losses)||0,draws:Number(p.draws)||0,correct:Number(p.correct)||0,wrong:Number(p.wrong)||0,best_streak:Number(p.best_streak)||0,timed_best:Number(p.timed_best)||0,solo_best:Number(p.solo_best)||0,ranked_wins:Number(p.ranked_wins)||0,chill_games:Number(p.chill_games)||0,manager_correct:Number(p.manager_correct)||0,badges:Array.isArray(p.badges)?p.badges.slice(0,30):[],last_seen:new Date().toISOString(),season:seasonFor(key)}}
api.ensureProfile=async p=>{p=cleanProfile(p);const c=cache();c.me=p;save(c);if(!(await online()))return p;try{const rows=await client.entities.PlayerProfile.filter({profile_key:p.profile_key},"-updated_date",1,0);if(rows?.[0]){await client.entities.PlayerProfile.update(rows[0].id,{username:p.username,last_seen:p.last_seen,season:p.season});return{...rows[0],username:p.username,season:p.season}}return await client.entities.PlayerProfile.create(p)}catch(e){api.status="degraded";api.lastError=String(e?.message||e);return p}};
api.getProfile=async key=>{if(await online())try{const rows=await client.entities.PlayerProfile.filter({profile_key:key},"-updated_date",1,0);if(rows?.[0])return rows[0]}catch(e){api.lastError=String(e?.message||e)}return cache().me||null};
api.leaderboard=async(limit=50)=>{limit=Math.max(5,Math.min(100,+limit||50));if(await online())try{const raw=await client.entities.PlayerProfile.filter({season:"S1"},"-rating",Math.min(200,limit+30),0),rows=(raw||[]).filter(p=>!String(p.profile_key||"").startsWith("qa-")).slice(0,limit);api.status="online";const c=cache();c.board=rows;c.boardAt=Date.now();save(c);return rows}catch(e){api.status="degraded";api.lastError=String(e?.message||e)}return(cache().board||[]).filter(p=>!String(p.profile_key||"").startsWith("qa-"))};
api.dailyLeaderboard=async(mode="daily5",date=today(),limit=50)=>{limit=Math.max(5,Math.min(100,+limit||50));if(await online())try{return(await client.entities.DailyScore.filter({date,mode,season:"S1"},"-score",limit,0)||[]).filter(x=>!String(x.profile_key||"").startsWith("qa-"))}catch(e){api.status="degraded";api.lastError=String(e?.message||e)}return[]};
async function recordDaily(summary){const key=String(summary.profile_key||""),m=String(summary.mode||"");if(!key||!/^daily/i.test(m))return;const date=today(),scoreKey=`${date}:${m}:${key}`,season=seasonFor(key),score=Number(summary.score)||0,base={score_key:scoreKey,date,profile_key:key,username:cleanName(summary.username),mode:m,score,correct:Number(summary.correct)||0,wrong:Number(summary.wrong)||0,best_streak:Number(summary.best_streak)||0,duration_sec:Number(summary.duration_sec)||0,attempts:1,season,updated_at:new Date().toISOString()};const rows=await client.entities.DailyScore.filter({score_key:scoreKey},"-updated_date",1,0);if(rows?.[0]){const r=rows[0],data={attempts:(Number(r.attempts)||0)+1,username:base.username,season,updated_at:base.updated_at};if(score>Number(r.score||0))Object.assign(data,{score,correct:base.correct,wrong:base.wrong,best_streak:base.best_streak,duration_sec:base.duration_sec});await client.entities.DailyScore.update(r.id,data)}else await client.entities.DailyScore.create(base)}
api.recordMatch=async summary=>{const c=cache(),key=String(summary.profile_key||"");if(!key)return null;const base=cleanProfile(c.me||summary),next=cleanProfile({...base,...summary.profile,profile_key:key,username:summary.username||base.username});c.me=next;save(c);if(!(await online()))return next;try{let rows=await client.entities.PlayerProfile.filter({profile_key:key},"-updated_date",1,0),saved;if(rows?.[0])saved=await client.entities.PlayerProfile.update(rows[0].id,next);else saved=await client.entities.PlayerProfile.create(next);await client.entities.MatchResult.create({match_id:String(summary.match_id||crypto.randomUUID()),profile_key:key,username:cleanName(summary.username),mode:String(summary.mode||"unknown").slice(0,40),content_type:String(summary.content_type||"player").slice(0,30),placement:Number(summary.placement)||1,score:Number(summary.score)||0,correct:Number(summary.correct)||0,wrong:Number(summary.wrong)||0,best_streak:Number(summary.best_streak)||0,duration_sec:Number(summary.duration_sec)||0,rating_delta:Number(summary.rating_delta)||0,played_at:new Date().toISOString(),room_code:String(summary.room_code||"").slice(0,12)});await recordDaily(summary);api.status="online";c.me=saved;save(c);return saved}catch(e){api.status="degraded";api.lastError=String(e?.message||e);return next}};
api.statusText=()=>api.status==="online"?"Global skor bağlı":api.status==="loading"?"Global skor bağlanıyor":"Global skor çevrimdışı";api.today=today;
})();
