(()=>{"use strict";
const APP_ID="6a7a33fd2bae90444c321e7e",LS="qf-v5-cloud-cache";
const cache=()=>{try{return JSON.parse(localStorage.getItem(LS)||"{}")||{}}catch{return{}}};
const save=x=>{try{localStorage.setItem(LS,JSON.stringify(x))}catch{}};
const api={status:"loading",lastError:"",client:null,ready:null};window.QFCloud=api;
let client=null;
api.ready=(async()=>{try{const mod=await import("https://esm.sh/@base44/sdk");client=mod.createClient({appId:APP_ID});api.client=client;api.status="online";return true}catch(e){api.status="offline";api.lastError=String(e?.message||e);return false}})();
async function online(){await api.ready;return api.status==="online"&&client}
function cleanName(v){return String(v||"").trim().replace(/[<>]/g,"").slice(0,18)}
function cleanProfile(p){return{profile_key:String(p.profile_key||"").slice(0,80),username:cleanName(p.username),rating:Number(p.rating)||1000,xp:Number(p.xp)||0,level:Number(p.level)||1,games:Number(p.games)||0,wins:Number(p.wins)||0,losses:Number(p.losses)||0,draws:Number(p.draws)||0,correct:Number(p.correct)||0,wrong:Number(p.wrong)||0,best_streak:Number(p.best_streak)||0,timed_best:Number(p.timed_best)||0,solo_best:Number(p.solo_best)||0,ranked_wins:Number(p.ranked_wins)||0,chill_games:Number(p.chill_games)||0,manager_correct:Number(p.manager_correct)||0,badges:Array.isArray(p.badges)?p.badges.slice(0,30):[],last_seen:new Date().toISOString(),season:"S1"}}
api.ensureProfile=async p=>{p=cleanProfile(p);const c=cache();c.me=p;save(c);if(!(await online()))return p;try{const rows=await client.entities.PlayerProfile.filter({profile_key:p.profile_key},"-updated_date",1,0);if(rows?.[0]){await client.entities.PlayerProfile.update(rows[0].id,{username:p.username,last_seen:p.last_seen,season:p.season});return{...rows[0],username:p.username}}const r=await client.entities.PlayerProfile.create(p);return r}catch(e){api.status="degraded";api.lastError=String(e?.message||e);return p}};
api.getProfile=async key=>{if(await online())try{const rows=await client.entities.PlayerProfile.filter({profile_key:key},"-updated_date",1,0);if(rows?.[0])return rows[0]}catch(e){api.lastError=String(e?.message||e)}return cache().me||null};
api.leaderboard=async(limit=50)=>{limit=Math.max(5,Math.min(100,+limit||50));if(await online())try{const rows=await client.entities.PlayerProfile.filter({season:"S1"},"-rating",limit,0);api.status="online";const c=cache();c.board=rows;c.boardAt=Date.now();save(c);return rows}catch(e){api.status="degraded";api.lastError=String(e?.message||e)}return cache().board||[]};
api.recordMatch=async summary=>{const c=cache(),key=String(summary.profile_key||"");if(!key)return null;const base=cleanProfile(c.me||summary);const next=cleanProfile({...base,...summary.profile,profile_key:key,username:summary.username||base.username});c.me=next;save(c);if(!(await online()))return next;try{let rows=await client.entities.PlayerProfile.filter({profile_key:key},"-updated_date",1,0),saved;if(rows?.[0])saved=await client.entities.PlayerProfile.update(rows[0].id,next);else saved=await client.entities.PlayerProfile.create(next);await client.entities.MatchResult.create({match_id:String(summary.match_id||crypto.randomUUID()),profile_key:key,username:cleanName(summary.username),mode:String(summary.mode||"unknown").slice(0,40),content_type:String(summary.content_type||"player").slice(0,30),placement:Number(summary.placement)||1,score:Number(summary.score)||0,correct:Number(summary.correct)||0,wrong:Number(summary.wrong)||0,best_streak:Number(summary.best_streak)||0,duration_sec:Number(summary.duration_sec)||0,rating_delta:Number(summary.rating_delta)||0,played_at:new Date().toISOString(),room_code:String(summary.room_code||"").slice(0,12)});api.status="online";c.me=saved;save(c);return saved}catch(e){api.status="degraded";api.lastError=String(e?.message||e);return next}};
api.statusText=()=>api.status==="online"?"Global skor bağlı":api.status==="loading"?"Global skor bağlanıyor":"Global skor çevrimdışı";
})();
