(()=>{"use strict";
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=a=>a[Math.floor(Math.random()*a.length)];
let voice=null,speaking=false,pending=null,lastCaptionTimer=0,lastIntroMatch=null,lastSpokenAt=0,lastFinalAt=0;
const seen=new Map(),recentLines=[],stats={speeches:0,skipped:0,cancelled:0,deduped:0,lastText:"",voice:"",queue:0,lastType:"",lastPhase:"",sequences:0};
function audio(){return window.QF_AUDIO_V13?.getSettings?.()||{enabled:true,commentary:true,commentator:.78,rate:.74,pitch:.93,captions:true,master:.84}}
function chooseVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];const score=v=>{let s=0;if(/^tr([-_]|$)/i.test(v.lang||""))s+=120;if(/natural|neural|online|tolga|ahmet|emel|filiz|male|erkek/i.test(v.name||""))s+=35;if(v.localService)s+=3;return s};voice=[...vs].sort((a,b)=>score(b)-score(a))[0]||null;stats.voice=voice?.name||"";return voice}
if(window.speechSynthesis){chooseVoice();window.speechSynthesis.onvoiceschanged=chooseVoice}
function clean(t){return String(t||"").replace(/\s+/g," ").replace(/GO{7,}L/gi,"GOOOOOL").trim()}
function caption(text){if(audio().captions===false)return;let el=document.getElementById("qfCommentaryCaption");if(!el){el=document.createElement("div");el.id="qfCommentaryCaption";el.className="qf-commentary-caption v13-commentary-caption";document.body.appendChild(el)}el.textContent=text;el.classList.add("show");clearTimeout(lastCaptionTimer);lastCaptionTimer=setTimeout(()=>el.classList.remove("show"),Math.min(6500,2600+text.length*32))}
function canSpeak(){const s=audio();return s.enabled!==false&&s.commentary!==false&&!!window.speechSynthesis}
function now(){return performance.now()}
function pruneSeen(){const t=now();for(const[k,v]of seen)if(t-v>14000)seen.delete(k);while(recentLines.length&&t-recentLines[0].at>26000)recentLines.shift()}
function fingerprint(d){const min=Math.round(+d.minute||0),actor=(d.actorId||d.actorName||"").toLowerCase(),side=d.side||"";return`${d.type||d.phase}:${d.phase||""}:${min}:${actor}:${side}`}
function duplicateEvent(d){pruneSeen();const k=fingerprint(d),t=now(),prev=seen.get(k);if(prev&&t-prev<9000){stats.deduped++;return true}seen.set(k,t);return false}
function lineRecently(text){pruneSeen();const n=clean(text).toLocaleLowerCase("tr-TR").replace(/\d+/g,"#");if(recentLines.some(x=>x.key===n)){stats.deduped++;return true}recentLines.push({key:n,at:now()});return false}
function stopSpeech(){if(!window.speechSynthesis)return;try{window.speechSynthesis.cancel();stats.cancelled++}catch{}speaking=false;stats.queue=0}
function speak(text,{type="event",interrupt=false,minGap=2200}={}){text=clean(text);if(!text||lineRecently(text))return;caption(text);if(!canSpeak()){stats.skipped++;return}const t=Date.now();if(!interrupt&&t-lastSpokenAt<minGap){stats.skipped++;return}if(interrupt&&speaking)stopSpeech();else if(speaking){stats.skipped++;return}const s=audio(),u=new SpeechSynthesisUtterance(text);u.lang="tr-TR";u.rate=.74;u.pitch=.94;u.volume=clamp((s.master??.84)*(s.commentator??.78),0,1);if(voice)u.voice=voice;speaking=true;stats.queue=1;lastSpokenAt=t;stats.speeches++;stats.lastText=text;stats.lastType=type;u.onend=u.onerror=()=>{speaking=false;stats.queue=0};try{window.speechSynthesis.speak(u)}catch{speaking=false;stats.queue=0}}
function niceName(n){n=clean(n);if(!n||/^(oyuncu|forvet|rakip forvet|hücum oyuncusu|kanat oyuncusu|rakip oyuncu)$/i.test(n))return"";return n}
function laneLead(lane){return lane==="left"?pick(["sol kanattan hızlandı","sol çizgiden bindirdi","sol tarafta boşluğu buldu"]):lane==="right"?pick(["sağ kanattan ilerledi","sağ çizgide boşluğu yakaladı","sağdan savunmanın üstüne gitti"]):pick(["merkezden hızla çıktı","iki hat arasına girdi","orta alandan yüzünü kaleye döndü"])}
function delivery(lane){return lane==="center"?pick(["savunma arasına bıraktı","ince bir ara pası çıkardı","tek pasla savunmayı açtı"]):pick(["ortasını ceza alanına gönderdi","yerden içeri çevirdi","başını kaldırıp ortasını yaptı"])}
function result(type){if(type==="goal")return pick(["Vuruş geliyor... GOOOOOL! Top ağlarda!","Son dokunuş... GOOOOOL! Müthiş bitiriş!","Vurdu... GOOOOOL! Tribünler ayağa kalktı!"]);if(type==="save")return pick(["Vuruş geldi... kaleci çıkardı! Çok iyi kurtarış.","Şut geliyor... kaleci uzandı ve gole izin vermedi."]);if(type==="post")return pick(["Vurdu... DİREK! Top oyuna geri döndü.","Şut geldi... direkten döndü! Gol çok yakındı."]);return pick(["Vuruş geldi ama top dışarıda.","Son vuruş kaleyi bulmadı. Büyük fırsat kaçtı."])}
function composeFinal(d){const p=pending&&now()-pending.at<8500?pending:null;pending=null;const creator=niceName(p?.creator||""),scorer=niceName(d.actorName||p?.scorer||""),lane=d.lane||p?.lane||"center",parts=[];if(creator){parts.push(`${creator} ${laneLead(lane)}.`);parts.push(delivery(lane)+".")}else parts.push(`${laneLead(lane)}. ${delivery(lane)}.`);if(scorer&&scorer!==creator)parts.push(`${scorer} ceza alanında.`);parts.push(result(d.type));return parts.join(" ")}
function remember(d){pending ||= {at:now(),creator:"",scorer:"",lane:"center"};pending.at=now();if(d.lane)pending.lane=d.lane;if(d.phase==="build"||d.phase==="delivery"){const n=niceName(d.actorName);if(n)pending.creator=n}else if(d.phase==="finish"){const n=niceName(d.actorName);if(n)pending.scorer=n}}
function onFlow(e){const d=e.detail||{};stats.lastPhase=d.phase||"";stats.lastType=d.type||"";if(duplicateEvent(d))return;if(["build","delivery","finish"].includes(d.phase)&&!d.final){remember(d);if(d.phase==="build")caption(`${niceName(d.actorName)||"Hücum oyuncusu"} ${laneLead(d.lane||"center")}.`);return}if(d.final){lastFinalAt=Date.now();stats.sequences++;speak(composeFinal(d),{type:d.type||"result",interrupt:d.type==="goal",minGap:d.type==="goal"?0:1400});return}if(["penalty","setpiece","discipline","half","sub","injury"].includes(d.phase)){pending=null;const txt=clean(d.text);if(txt)speak(txt,{type:d.phase,interrupt:d.phase==="penalty",minGap:2600})}}
function onRaw(e){const d=e.detail||{};if(Date.now()-lastFinalAt<900)return;if(["goal","save","post","miss","corner","free","penalty","card","injury","half","sub"].includes(d.type))return;if(d.type==="red"&&!duplicateEvent({...d,phase:"raw"}))speak(clean(d.text||"Kırmızı kart. Maçın dengesi değişiyor."),{type:"red",interrupt:true,minGap:0})}
function matchSnapshot(){const m=window.QF_V7_TEST?.match?.();if(m?.running)return{key:`solo:${m.start}`,home:window.QF_V7_CORE?.clubSnapshot?.()?.name||"Ev sahibi",away:m.opponent?.name||"Rakip"};const n=window.QF_V7_ONLINE_TEST?.net?.();if(n?.match?.running)return{key:`online:${n.match.start}`,home:n.hostClub?.name||"Ev sahibi",away:n.guestClub?.name||"Deplasman"};return null}
function poll(){const s=matchSnapshot();if(s&&lastIntroMatch!==s.key){lastIntroMatch=s.key;pending=null;speak(`${s.home} ile ${s.away} karşı karşıya. Maç başladı.`,{type:"intro",interrupt:true,minGap:0})}else if(!s&&lastIntroMatch){lastIntroMatch=null;pending=null;setTimeout(()=>speak("Son düdük geldi. Maç sona erdi.",{type:"final",interrupt:true,minGap:0}),300)}stats.queue=speaking?1:0}
window.addEventListener("qf:v11-commentary",onFlow);window.addEventListener("qf:v9-event",onRaw);setInterval(poll,900);
function test(type="goal"){const base={type,minute:88,actorName:"Forvet",actorId:"qa",side:"home",lane:"right"};onFlow({detail:{...base,phase:"build"}});setTimeout(()=>onFlow({detail:{...base,phase:"delivery"}}),70);setTimeout(()=>onFlow({detail:{...base,phase:"finish"}}),140);setTimeout(()=>onFlow({detail:{...base,phase:"result",final:true,text:"QA"}}),220)}
const api={unlock:()=>window.QF_AUDIO_V13?.unlock?.(),getSettings:()=>({...audio(),style:"broadcast",importantOnly:true}),setSetting:(k,v)=>window.QF_AUDIO_V13?.setSetting?.(k,v)??false,state:()=>({...stats,speaking,queue:speaking?1:0,voice:voice?.name||""}),test,resetDedupe:()=>{seen.clear();recentLines.length=0}};
window.QF_COMMENTARY_V14=api;window.QF_COMMENTARY_V13=api;window.QF_COMMENTARY_V11=api;window.QF_COMMENTARY_V10=api;
})();
