(()=>{"use strict";
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=a=>a[Math.floor(Math.random()*a.length)];
let voice=null,speaking=false,current=null,queue=[],lastSpokenAt=0,lastCaptionTimer=0,lastEventKey="",lastIntroMatch=null;
const stats={speeches:0,skipped:0,cancelled:0,lastText:"",voice:"",queue:0,lastType:"",lastPhase:""};
function audio(){return window.QF_AUDIO_V13?.getSettings?.()||window.QF_AUDIO_V8?.getSettings?.()||{enabled:true,commentary:true,commentator:.78,rate:.84,pitch:.94,captions:true}}
function chooseVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];const score=v=>{let s=0;if(/^tr([-_]|$)/i.test(v.lang||""))s+=100;if(/natural|neural|online|tolga|ahmet|emel|filiz|male|erkek/i.test(v.name||""))s+=35;if(v.localService)s+=5;return s};voice=[...vs].sort((a,b)=>score(b)-score(a))[0]||null;stats.voice=voice?.name||"";return voice}
if(window.speechSynthesis){chooseVoice();window.speechSynthesis.onvoiceschanged=chooseVoice}
function caption(text){const s=audio();if(s.captions===false)return;let el=document.getElementById("qfCommentaryCaption");if(!el){el=document.createElement("div");el.id="qfCommentaryCaption";el.className="qf-commentary-caption v13-commentary-caption";document.body.appendChild(el)}el.textContent=text;el.classList.add("show");clearTimeout(lastCaptionTimer);lastCaptionTimer=setTimeout(()=>el.classList.remove("show"),Math.min(6200,2600+text.length*38))}
function canSpeak(){const s=audio();return s.enabled!==false&&s.commentary!==false&&!!window.speechSynthesis}
function cleanText(t){return String(t||"").replace(/\s+/g," ").replace(/GO{7,}L/gi,"GOOOOOL").trim()}
function say(text,{priority=50,type="event",interrupt=false,minGap=1600}={}){text=cleanText(text);if(!text)return;caption(text);if(!canSpeak()){stats.skipped++;return}const now=Date.now(),item={text,priority,type,created:now,minGap};if(priority<90&&now-lastSpokenAt<minGap){if(queue.some(x=>x.type===type)){stats.skipped++;return}queue.push(item);queue=queue.sort((a,b)=>b.priority-a.priority).slice(0,2);stats.queue=queue.length;return}if(interrupt&&speaking&&current?.type!=="goal"){try{window.speechSynthesis.cancel();stats.cancelled++}catch{}speaking=false;current=null;queue=[];setTimeout(()=>{queue.unshift(item);drain()},180);return}queue.push(item);queue=queue.sort((a,b)=>b.priority-a.priority).slice(0,2);stats.queue=queue.length;drain()}
function drain(){if(speaking||!queue.length||!canSpeak())return;const now=Date.now();queue=queue.filter(x=>now-x.created<5500);if(!queue.length){stats.queue=0;return}const item=queue.shift(),s=audio(),u=new SpeechSynthesisUtterance(item.text);u.lang="tr-TR";u.rate=clamp(s.rate??.84,.76,.90);u.pitch=clamp(s.pitch??.94,.88,1.02);u.volume=clamp((s.master??.82)*(s.commentator??.78),0,1);if(voice)u.voice=voice;speaking=true;current=item;lastSpokenAt=Date.now();stats.speeches++;stats.lastText=item.text;stats.lastType=item.type;u.onend=u.onerror=()=>{speaking=false;current=null;setTimeout(drain,320)};try{window.speechSynthesis.speak(u)}catch{speaking=false;current=null}}
function minutePrefix(d){const m=Math.round(+d.minute||0);return m>0?`${m}. dakika. `:""}
function finalLine(d){const a=d.actorName&&d.actorName!=="Oyuncu"?d.actorName:"";if(d.type==="goal")return pick([`${minutePrefix(d)}GOOOOOL! ${a?`${a}! `:""}Top ağlarda! Tribün ayağa kalktı!`,`${minutePrefix(d)}GOOOOOL! ${a?`${a} bitiriyor! `:""}Müthiş bir hücum, müthiş bir gol!`,`${minutePrefix(d)}GOL! GOL! GOL! ${a?`${a}! `:""}Kaleci çaresiz, top filelerde!`]);if(d.type==="save")return pick([`${minutePrefix(d)}Şut geldi... kaleci çıkardı! Çok büyük kurtarış!`,`${minutePrefix(d)}Vurdu! Kaleci uzandı ve gole izin vermedi!`]);if(d.type==="post")return pick([`${minutePrefix(d)}Vurdu... DİREK! Top geri geldi!`,`${minutePrefix(d)}DİREKTEN DÖNDÜ! Gol santimlerle kaçtı!`]);return pick([`${minutePrefix(d)}Vuruş dışarıda! Çok önemli fırsat kaçtı!`,`${minutePrefix(d)}Şut geldi... olmadı! Tribünlerden büyük bir ah sesi yükseldi!`])}
function phaseLine(d){const actor=d.actorName&&d.actorName!=="Oyuncu"?d.actorName:"Oyuncu";if(d.phase==="build")return d.lane==="left"?`${actor} sol kanattan hızlandı, savunma geri koşuyor.`:d.lane==="right"?`${actor} sağ kanattan geliyor, önünde alan var.`:`${actor} merkezden topu taşıyor, savunmanın üstüne gidiyor.`;if(d.phase==="delivery")return d.lane==="center"?`${actor} savunma arasına bıraktı... tehlike büyüyor.`:`${actor} başını kaldırdı... orta geliyor.`;if(d.phase==="finish")return `${actor} vuruş için hazırlanıyor...`;return cleanText(d.text)}
function onFlow(e){const d=e.detail||{};stats.lastPhase=d.phase||"";stats.lastType=d.type||"";const key=`${d.type}:${d.phase}:${Math.round(+d.minute||0)}:${d.actorId||""}`;if(key===lastEventKey)return;lastEventKey=key;if(d.final){say(finalLine(d),{priority:d.type==="goal"?120:100,type:d.type||"result",interrupt:d.type==="goal",minGap:0});return}if(d.phase==="build"){if(Date.now()-lastSpokenAt>3600&&!speaking)say(phaseLine(d),{priority:45,type:"build",minGap:3000});else caption(phaseLine(d));return}if(d.phase==="delivery"){if(!speaking&&Date.now()-lastSpokenAt>2600)say(phaseLine(d),{priority:56,type:"delivery",minGap:2400});else caption(phaseLine(d));return}if(d.phase==="finish"){caption(phaseLine(d));return}if(["penalty","setpiece","discipline","half","sub","injury"].includes(d.phase))say(cleanText(d.text),{priority:d.phase==="penalty"?95:66,type:d.phase,interrupt:d.phase==="penalty",minGap:2600})}
function onRaw(e){const d=e.detail||{};if(window.QF_MATCH_FLOW_V11&&["goal","save","post","miss","corner","free","penalty","card","injury","half","sub"].includes(d.type))return;if(d.type==="red")say(cleanText(d.text||"Kırmızı kart! Maçın dengesi değişiyor."),{priority:96,type:"red",interrupt:true,minGap:0})}
function matchSnapshot(){const m=window.QF_V7_TEST?.match?.();if(m?.running)return{key:`solo:${m.start}`,home:window.QF_V7_CORE?.clubSnapshot?.()?.name||"Ev sahibi",away:m.opponent?.name||"Rakip"};const n=window.QF_V7_ONLINE_TEST?.net?.();if(n?.match?.running)return{key:`online:${n.match.start}`,home:n.hostClub?.name||"Ev sahibi",away:n.guestClub?.name||"Deplasman"};return null}
function poll(){const s=matchSnapshot();if(s&&lastIntroMatch!==s.key){lastIntroMatch=s.key;say(`${s.home} ile ${s.away} karşı karşıya. Hakemin düdüğüyle maç başladı.`,{priority:82,type:"intro",interrupt:true,minGap:0})}else if(!s&&lastIntroMatch){lastIntroMatch=null;if(speaking||queue.length){setTimeout(()=>say("Ve son düdük. Maç sona erdi.",{priority:80,type:"final",minGap:0}),500)}else say("Ve son düdük. Maç sona erdi.",{priority:80,type:"final",minGap:0})}stats.queue=queue.length}
window.addEventListener("qf:v11-commentary",onFlow);window.addEventListener("qf:v9-event",onRaw);setInterval(poll,650);
function setSetting(k,v){const a=window.QF_AUDIO_V13||window.QF_AUDIO_V8;if(["enabled","commentary","commentator","master","rate","pitch","captions"].includes(k))return a?.setSetting?.(k,v)??false;if(k==="style"||k==="importantOnly"||k==="slang"||k==="analysis"||k==="chantWords"||k==="crowdLevel")return true;return false}
function test(type="goal"){onFlow({detail:{type,phase:"result",final:true,minute:88,actorName:"Forvet",actorId:"qa",text:"QA",importance:100,excitement:100}})}
const api={unlock:()=>window.QF_AUDIO_V13?.unlock?.(),getSettings:()=>({...audio(),style:"broadcast",importantOnly:true}),setSetting,state:()=>({...stats,speaking,queue:queue.length,voice:voice?.name||""}),test};window.QF_COMMENTARY_V13=api;window.QF_COMMENTARY_V10=api;window.QF_COMMENTARY_V11=api;
})();
