(()=>{"use strict";
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=a=>a[Math.floor(Math.random()*a.length)];
let voice=null,speaking=false,current=null,pending=null,lastSpokenAt=0,lastCaptionTimer=0,lastEventKey="",lastIntroMatch=null,lastFinalAt=0;
const stats={speeches:0,skipped:0,cancelled:0,lastText:"",voice:"",queue:0,lastType:"",lastPhase:"",sequences:0};
function audio(){return window.QF_AUDIO_V13?.getSettings?.()||window.QF_AUDIO_V8?.getSettings?.()||{enabled:true,commentary:true,commentator:.78,rate:.78,pitch:.93,captions:true,master:.84}}
function chooseVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];const score=v=>{let s=0;if(/^tr([-_]|$)/i.test(v.lang||""))s+=100;if(/natural|neural|online|tolga|ahmet|emel|filiz|male|erkek/i.test(v.name||""))s+=40;if(v.localService)s+=3;return s};voice=[...vs].sort((a,b)=>score(b)-score(a))[0]||null;stats.voice=voice?.name||"";return voice}
if(window.speechSynthesis){chooseVoice();window.speechSynthesis.onvoiceschanged=chooseVoice}
function caption(text){const s=audio();if(s.captions===false)return;let el=document.getElementById("qfCommentaryCaption");if(!el){el=document.createElement("div");el.id="qfCommentaryCaption";el.className="qf-commentary-caption v13-commentary-caption";document.body.appendChild(el)}el.textContent=text;el.classList.add("show");clearTimeout(lastCaptionTimer);lastCaptionTimer=setTimeout(()=>el.classList.remove("show"),Math.min(6500,2800+text.length*34))}
function canSpeak(){const s=audio();return s.enabled!==false&&s.commentary!==false&&!!window.speechSynthesis}
function cleanText(t){return String(t||"").replace(/\s+/g," ").replace(/GO{7,}L/gi,"GOOOOOL").trim()}
function stopSpeech(){if(!window.speechSynthesis)return;try{window.speechSynthesis.cancel();stats.cancelled++}catch{}speaking=false;current=null}
function speakNow(text,{type="event",priority=50,interrupt=false,minGap=1250}={}){text=cleanText(text);if(!text)return;caption(text);if(!canSpeak()){stats.skipped++;return}const now=Date.now();if(!interrupt&&now-lastSpokenAt<minGap){stats.skipped++;return}if(interrupt&&speaking)stopSpeech();if(speaking){stats.skipped++;return}const s=audio(),u=new SpeechSynthesisUtterance(text);u.lang="tr-TR";u.rate=.78;u.pitch=.93;u.volume=clamp((s.master??.84)*(s.commentator??.78),0,1);if(voice)u.voice=voice;speaking=true;current={type,priority};lastSpokenAt=now;stats.speeches++;stats.lastText=text;stats.lastType=type;u.onend=u.onerror=()=>{speaking=false;current=null};try{window.speechSynthesis.speak(u)}catch{speaking=false;current=null}}
function minute(d){const m=Math.round(+d.minute||0);return m>0?`${m}. dakikada `:""}
function actor(d){return d.actorName&&d.actorName!=="Oyuncu"?d.actorName:""}
function resultLine(d){const a=actor(d),m=minute(d);if(d.type==="goal")return pick([`${m}${a?`${a} vurdu... `:""}GOOOOOL! Top ağlarda, tribün ayağa kalktı!`,`${m}${a?`${a} son dokunuşu yaptı... `:""}GOOOOOL! Müthiş bir bitiriş!`,`${m}${a?`${a}! `:""}GOL! GOL! GOL! Kaleci çaresiz, top filelerde!`]);if(d.type==="save")return pick([`${m}${a?`${a} vurdu... `:""}kaleci çıkardı! Çok büyük kurtarış!`,`${m}şut geldi... kaleci uzandı ve gole izin vermedi!`]);if(d.type==="post")return pick([`${m}${a?`${a} vurdu... `:""}DİREK! Top geri geldi!`,`${m}DİREKTEN DÖNDÜ! Gol santimlerle kaçtı!`]);return pick([`${m}vuruş dışarıda! Çok önemli fırsat kaçtı!`,`${m}şut geldi... olmadı! Tribünlerden büyük bir ah sesi yükseldi!`])}
function phaseCaption(d){const a=actor(d)||"Oyuncu";if(d.phase==="build")return d.lane==="left"?`${a} sol kanattan geliyor.`:d.lane==="right"?`${a} sağ kanattan geliyor.`:`${a} merkezden topu taşıyor.`;if(d.phase==="delivery")return d.lane==="center"?`${a} savunma arasına bıraktı.`:`${a} başını kaldırdı, orta geliyor.`;if(d.phase==="finish")return `${a} vuruşunu hazırlıyor.`;return cleanText(d.text)}
function rememberPhase(d){pending ||= {started:Date.now(),actor:"",lane:"",build:"",delivery:"",finish:""};if(actor(d))pending.actor=actor(d);if(d.lane)pending.lane=d.lane;if(d.phase==="build")pending.build=phaseCaption(d);if(d.phase==="delivery")pending.delivery=phaseCaption(d);if(d.phase==="finish")pending.finish=phaseCaption(d)}
function sequenceResult(d){const res=resultLine(d);const p=pending;pending=null;stats.sequences++;if(!p||Date.now()-p.started>7000)return res;const lead=p.build||p.delivery||"";if(!lead)return res;return `${lead} ${res}`}
function onFlow(e){const d=e.detail||{};stats.lastPhase=d.phase||"";stats.lastType=d.type||"";const key=`${d.type}:${d.phase}:${Math.round(+d.minute||0)}:${d.actorId||""}`;if(key===lastEventKey)return;lastEventKey=key;if(d.final){lastFinalAt=Date.now();speakNow(sequenceResult(d),{type:d.type||"result",priority:d.type==="goal"?120:100,interrupt:true,minGap:0});return}if(["build","delivery","finish"].includes(d.phase)){rememberPhase(d);caption(phaseCaption(d));return}if(["penalty","setpiece","discipline","half","sub","injury"].includes(d.phase)){pending=null;speakNow(cleanText(d.text),{type:d.phase,priority:d.phase==="penalty"?95:70,interrupt:d.phase==="penalty",minGap:1800})}}
function onRaw(e){const d=e.detail||{};if(Date.now()-lastFinalAt<700)return;if(window.QF_MATCH_FLOW_V11&&["goal","save","post","miss","corner","free","penalty","card","injury","half","sub"].includes(d.type))return;if(d.type==="red")speakNow(cleanText(d.text||"Kırmızı kart! Maçın dengesi değişiyor."),{type:"red",priority:96,interrupt:true,minGap:0})}
function matchSnapshot(){const m=window.QF_V7_TEST?.match?.();if(m?.running)return{key:`solo:${m.start}`,home:window.QF_V7_CORE?.clubSnapshot?.()?.name||"Ev sahibi",away:m.opponent?.name||"Rakip"};const n=window.QF_V7_ONLINE_TEST?.net?.();if(n?.match?.running)return{key:`online:${n.match.start}`,home:n.hostClub?.name||"Ev sahibi",away:n.guestClub?.name||"Deplasman"};return null}
function poll(){const s=matchSnapshot();if(s&&lastIntroMatch!==s.key){lastIntroMatch=s.key;pending=null;speakNow(`${s.home} ile ${s.away} karşı karşıya. Hakemin düdüğüyle maç başladı.`,{type:"intro",priority:82,interrupt:true,minGap:0})}else if(!s&&lastIntroMatch){lastIntroMatch=null;pending=null;setTimeout(()=>speakNow("Ve son düdük. Maç sona erdi.",{type:"final",priority:80,interrupt:true,minGap:0}),350)}stats.queue=0}
window.addEventListener("qf:v11-commentary",onFlow);window.addEventListener("qf:v9-event",onRaw);setInterval(poll,1000);
function setSetting(k,v){const a=window.QF_AUDIO_V13||window.QF_AUDIO_V8;if(["enabled","commentary","commentator","master","captions"].includes(k))return a?.setSetting?.(k,v)??false;if(k==="rate"||k==="pitch")return true;if(k==="style"||k==="importantOnly"||k==="slang"||k==="analysis"||k==="chantWords"||k==="crowdLevel")return true;return false}
function test(type="goal"){onFlow({detail:{type,phase:"build",minute:88,actorName:"Forvet",actorId:"qa",lane:"right"}});setTimeout(()=>onFlow({detail:{type,phase:"result",final:true,minute:88,actorName:"Forvet",actorId:"qa",text:"QA",importance:100,excitement:100}}),120)}
const api={unlock:()=>window.QF_AUDIO_V13?.unlock?.(),getSettings:()=>({...audio(),style:"broadcast",importantOnly:true}),setSetting,state:()=>({...stats,speaking,queue:0,voice:voice?.name||""}),test};window.QF_COMMENTARY_V13=api;window.QF_COMMENTARY_V10=api;window.QF_COMMENTARY_V11=api;
})();
