(()=>{"use strict";
const KEY="qf-v10-commentary",defaults={enabled:true,style:"natural",slang:true,crowd:true,crowdLevel:.44,analysis:true,importantOnly:true,chantWords:true,rate:.98,pitch:.92};
let cfg=load(),ctx=null,master=null,crowdBus=null,fxBus=null,crowdSrc=null,unlocked=false,voice=null,active=false,chantTimer=0,lastEventAt=0,lastAnalysis=0,lastSpeech=0,lastChant=0,speaking=false,currentKind="",queue=[],used=new Map();
const stats={events:0,speeches:0,chants:0,leaderChants:0,lastText:"",lastExcitement:0,lastType:"",lastPhase:"",unlocks:0,skipped:0,variants:0};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=a=>a[Math.floor(Math.random()*a.length)];
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(cfg));applyVolumes();renderControls()}
function v8(){return window.QF_AUDIO_V8?.getSettings?.()||{enabled:true,commentary:true,crowd:true}}
function audioAllowed(){const s=v8();return cfg.enabled&&s.enabled!==false}
function ensureAudio(){if(ctx)return ctx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;ctx=new AC();master=ctx.createGain();crowdBus=ctx.createGain();fxBus=ctx.createGain();crowdBus.connect(master);fxBus.connect(master);master.connect(ctx.destination);master.gain.value=.72;startCrowd();applyVolumes();return ctx}
function unlock(){const c=ensureAudio();if(!c)return false;c.resume?.();unlocked=true;stats.unlocks++;return true}
function applyVolumes(){if(!ctx||!master)return;const s=v8(),t=ctx.currentTime,on=cfg.enabled&&s.enabled!==false;master.gain.setTargetAtTime(on?.72:0,t,.05);crowdBus.gain.setTargetAtTime(on&&cfg.crowd&&s.crowd!==false?cfg.crowdLevel:0,t,.12);fxBus.gain.setTargetAtTime(on?.70:0,t,.05)}
function startCrowd(){if(!ctx||crowdSrc)return;const len=Math.floor(ctx.sampleRate*4),buf=ctx.createBuffer(2,len,ctx.sampleRate);for(let ch=0;ch<2;ch++){const d=buf.getChannelData(ch);let low=0,mid=0;for(let i=0;i<len;i++){low=low*.989+(Math.random()*2-1)*.065;mid=mid*.945+(Math.random()*2-1)*.05;const wave=.78+.22*Math.sin(i/ctx.sampleRate*(1.2+ch*.09));d[i]=(low*.38+mid*.18)*wave}}const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();src.buffer=buf;src.loop=true;f.type="lowpass";f.frequency.value=1450;g.gain.value=.82;src.connect(f);f.connect(g);g.connect(crowdBus);src.start();crowdSrc=src}
function noise(dur=.2,gain=.12,freq=650,delay=0){if(!ctx||!audioAllowed())return;const n=Math.max(64,Math.floor(ctx.sampleRate*dur)),b=ctx.createBuffer(1,n,ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),t=ctx.currentTime+delay;src.buffer=b;f.type="bandpass";f.frequency.value=freq;f.Q.value=.65;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+dur);src.connect(f);f.connect(g);g.connect(fxBus);src.start(t)}
function tone(freq,dur=.16,gain=.08,type="sine",delay=0,end=null){if(!ctx||!audioAllowed())return;const o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(30,end),t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain),t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(fxBus);o.start(t);o.stop(t+dur+.03)}
function roar(power=1,dur=2){if(!ctx||!audioAllowed()||!cfg.crowd)return;const n=Math.floor(ctx.sampleRate*dur),b=ctx.createBuffer(2,n,ctx.sampleRate);for(let ch=0;ch<2;ch++){const d=b.getChannelData(ch);let v=0;for(let i=0;i<n;i++){v=v*.958+(Math.random()*2-1)*.23;const env=Math.sin(Math.PI*i/n);d[i]=v*env*.52*power}}const src=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),t=ctx.currentTime;src.buffer=b;f.type="bandpass";f.frequency.value=760;f.Q.value=.42;g.gain.value=.3;src.connect(f);f.connect(g);g.connect(fxBus);src.start(t);for(let i=0;i<5;i++)tone(155+31*i,.42,.03*power,"sawtooth",.08+i*.075,220+42*i)}
function chantBed(power=.65){if(!ctx||!cfg.crowd||!audioAllowed()||!active)return;stats.chants++;for(let beat=0;beat<8;beat++){const d=beat*.31;noise(.14,.032*power,390+(beat%2)*120,d);tone(125+(beat%3)*16,.17,.018*power,"triangle",d,110)}}
function findVoice(){const vs=window.speechSynthesis?.getVoices?.()||[];voice=vs.find(v=>/^tr([-_]|$)/i.test(v.lang)&&/natural|online|neural|tolga|emel|ahmet|filiz|male|erkek/i.test(v.name))||vs.find(v=>/^tr([-_]|$)/i.test(v.lang))||vs.find(v=>/turk|türk/i.test(v.name))||null;return voice}
if(window.speechSynthesis){findVoice();window.speechSynthesis.onvoiceschanged=findVoice}
function snapshot(){const online=!!document.querySelector("#v7OnlineCanvas"),core=window.QF_V7_CORE?.clubSnapshot?.()||{},net=window.QF_V7_ONLINE_TEST?.net?.(),sm=window.QF_V7_TEST?.match?.();let m=online?net?.match:sm;if(!m)return{active:false,excitement:0};let home=+m.home||0,away=+m.away||0,minute=Math.round(+m.minute||0),own=home,opp=away,ownName=core.name||"Takımımız",oppName="Rakip",momentum=+m.momentum||0;if(online&&net){const leftMine=net.hostClub?.name===core.name;if(!leftMine){own=away;opp=home}oppName=(leftMine?net.guestClub:net.hostClub)?.name||"Rakip";momentum=leftMine?(m.momentumHome||0):(m.momentumAway||0)}else oppName=m.opponent?.name||"Rakip";const v=m.v9||{},close=Math.abs(own-opp)<=1,excitement=clamp(18+(close?18:0)+(minute>=75?24:minute>=45?9:0)+Math.min(24,momentum/4)+(v.visual?.eventType==="goal"?20:0),8,100);return{active:true,online,minute,own,opp,home,away,ownName,oppName,momentum,excitement,v,match:m}}
function noRepeat(key,arr){const prev=used.get(key)||[],pool=arr.filter(x=>!prev.includes(x)),x=pick(pool.length?pool:arr);used.set(key,[...prev.slice(-3),x]);stats.variants++;return x}
function caption(text,kind="commentary"){let el=document.getElementById(kind==="chant"?"v11ChantCaption":"qfCommentaryCaption");if(!el){el=document.createElement("div");el.id=kind==="chant"?"v11ChantCaption":"qfCommentaryCaption";el.className=kind==="chant"?"v11-chant-caption":"qf-commentary-caption";document.body.appendChild(el)}el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),kind==="chant"?2200:4200)}
function rateFor(exc){return clamp(cfg.rate+(exc/100)*.17+(cfg.style==="excited"?.08:cfg.style==="calm"?-.09:0),.80,1.28)}
function pitchFor(exc){return clamp(cfg.pitch+(exc/100)*.13+(cfg.style==="excited"?.04:0),.76,1.2)}
function canSpeak(){const s=v8();return audioAllowed()&&s.commentary!==false&&!!window.speechSynthesis}
function enqueue(text,exc=50,{priority=50,interrupt=false,kind="commentary",captionOnly=false}={}){if(!text)return;caption(text,kind==="chant"?"chant":"commentary");if(captionOnly||!canSpeak()){stats.skipped++;return}const item={text,exc,priority,kind};if(interrupt&&speaking&&currentKind!=="moment"){window.speechSynthesis.cancel();speaking=false;queue=[]}queue.push(item);queue.sort((a,b)=>b.priority-a.priority);if(queue.length>5)queue=queue.slice(0,5);drain()}
function drain(){if(speaking||!queue.length||!canSpeak())return;const item=queue.shift(),u=new SpeechSynthesisUtterance(item.text);u.lang="tr-TR";u.rate=item.kind==="chant"?.80:rateFor(item.exc);u.pitch=item.kind==="chant"?.70:pitchFor(item.exc);u.volume=item.kind==="chant"?.25:.96;if(voice)u.voice=voice;speaking=true;currentKind=item.kind;lastSpeech=Date.now();stats.speeches++;stats.lastText=item.text;stats.lastExcitement=item.exc;u.onend=u.onerror=()=>{speaking=false;currentKind="";setTimeout(drain,55)};window.speechSynthesis.speak(u)}
const raw={var:["VAR odası pozisyonu inceliyor. Birkaç saniye boyunca herkes beklemede.","VAR kontrolü başladı. Stadyumda ses bir anda düştü."],var_clear:["Kontrol tamamlandı. Karar kesinleşti ve oyun devam ediyor.","VAR incelemesi bitti. Hakemin kararı geçerli."],red:["KIRMIZI KART! Takım artık on kişi.","Kırmızı kart çıktı! Maçın dengesi tamamen değişebilir."],added:["Dördüncü hakem tabelayı kaldırdı. Uzatma dakikalarındayız.","Doksanın sonuna geldik, hakem kayıp zamanı ekliyor."],injury_detail:["Sağlık ekibi oyuncuyla ilgileniyor. Oyunun ritmi kısa süreliğine düştü.","Oyuncu yerde. Kulübe endişeli, sağlık ekibi kontrol ediyor."],card:["Hakem cebine gitti. Sarı kart çıktı.","Sert müdahale sonrası sarı kart kaçınılmaz oldu."],half:["İlk yarının son düdüğü. Skor ve oyun dengesi ikinci yarıya taşınıyor.","Devre arası. Teknik ekiplerin şimdi yapacağı ayarlar çok önemli."],sub:["Oyuncu değişikliği geliyor. Teknik direktör oyuna taze enerji ekliyor.","Kulübeden hamle geldi; yeni oyuncu sahada."]};
function fx(type){if(type==="goal"){roar(1.55,2.7);noise(.16,.14,430);tone(88,.2,.09,"sine",0,52)}else if(type==="save"){roar(.42,.72);noise(.08,.1,700)}else if(type==="post"){roar(.58,1.1);tone(1240,.27,.07,"triangle",0,810)}else if(type==="red"||type==="card")tone(1760,.18,.055,"sine",0,2250);else if(type==="half"){tone(1820,.18,.06,"sine");tone(1820,.18,.06,"sine",.28)}}
function onMoment(e){const d=e.detail||{},s=snapshot();if(!s.active)return;active=true;lastEventAt=Date.now();stats.events++;stats.lastType=d.type||"moment";stats.lastPhase=d.phase||"";let text=String(d.text||"");const exc=clamp(+d.excitement||+d.importance||60,20,100),importance=+d.importance||60;if(cfg.importantOnly&&importance<52){stats.skipped++;return}if(d.final&&cfg.slang&&exc>=82&&Math.random()<.24){const addon=d.type==="goal"?noRepeat("slang-goal",["Ne gol ama!","Yok artık!","Vay be!","Bu nasıl bitiriş!"]):d.type==="post"?noRepeat("slang-post",["Yok artık, direk!","Ne vurdu be!","Vay be, santimlerle!"]):d.type==="save"?noRepeat("slang-save",["Kaleci ne çıkardı be!","Yok artık, bu nasıl kurtarış!"]):"";if(addon)text=`${addon} ${text}`}
 if(d.final)fx(d.type);const priority=d.final?110:Math.round(importance);enqueue(text,exc,{priority,interrupt:d.final&&d.type==="goal",kind:"moment"})}
function onRaw(e){const d=e.detail||{},s=snapshot();if(!s.active)return;const flow=!!window.QF_MATCH_FLOW_V11;if(flow&&["goal","save","post","miss","corner","free","penalty","card","injury","half","sub"].includes(d.type))return;const type=d.type||"";if(cfg.importantOnly&&!raw[type])return;stats.events++;stats.lastType=type;lastEventAt=Date.now();fx(type);const text=raw[type]?noRepeat(`raw-${type}`,raw[type]):String(d.text||"").replace(/^\d+'\s*/,"");enqueue(text,type==="red"?92:type==="card"?62:58,{priority:type==="red"?100:64,interrupt:type==="red",kind:"event"})}
function analysis(){if(!cfg.analysis||!active)return;const s=snapshot(),now=Date.now();if(!s.active)return;if(now-lastEventAt<6500||now-lastSpeech<6000||now-lastAnalysis<11000||speaking)return;lastAnalysis=now;const v=s.v||{},lines=[];if(s.minute<22)lines.push(`${s.minute}. dakika. İki takım da henüz savunma dengesini bozmadan oynuyor.`);if(s.momentum>=65)lines.push(`${s.ownName} baskıyı yükseltti. Rakip artık kendi ceza alanına daha yakın savunuyor.`);if(v.possessionHome>=58)lines.push(`Topun kontrolü belirgin biçimde bir tarafta. Yüzde ${Math.round(v.possessionHome)} topa sahip olma oyunun yönünü gösteriyor.`);if(s.minute>=70&&Math.abs(s.own-s.opp)<=1)lines.push(`Son bölüme girdik. Skor bıçak sırtında; bundan sonraki tek bir büyük şans maçı çözebilir.`);if(s.own>s.opp&&s.minute>=68)lines.push(`${s.ownName} önde. Şimdi mesele yalnız hücum etmek değil, oyunun temposunu doğru yönetmek.`);if(s.own<s.opp&&s.minute>=68)lines.push(`${s.ownName} geri dönüş için daha fazla oyuncuyla öne çıkmak zorunda.`);if(!lines.length)return;enqueue(noRepeat("analysis",lines),36,{priority:20,kind:"analysis"})}
function chantLeader(){if(!cfg.chantWords||!cfg.crowd||!active||!canSpeak()||speaking)return;const s=snapshot(),now=Date.now();if(now-lastSpeech<5200||now-lastChant<10000)return;lastChant=now;const team=(s.ownName||"Takım").replace(/\s+(Futbol|Football|FC|SK|Spor).*$/i,"").slice(0,20),phrases=[`Haydi ${team}! Haydi ${team}!`,`Bastır ${team}! Bastır ${team}!`,`${team}! ${team}! Haydi!`,`Haydi takım, haydi!`],text=noRepeat("chant",phrases);stats.leaderChants++;chantBed(.72);caption(`TRİBÜN: ${text}`,"chant");enqueue(text,28,{priority:5,kind:"chant"})}
function scheduleChant(){clearTimeout(chantTimer);if(!active)return;chantTimer=setTimeout(()=>{if(active){chantBed(.58+Math.min(.35,(snapshot().excitement||0)/180));chantLeader();scheduleChant()}},5600+Math.random()*4800)}
function renderControls(){const panel=document.getElementById("qfAudioPanel");if(!panel)return;let box=document.getElementById("v10CommentaryControls");if(!box){box=document.createElement("div");box.id="v10CommentaryControls";box.className="v10-commentary-controls";box.innerHTML=`<details><summary>🎙️ Spiker ve Tribün</summary><div class="v10-commentary-grid"><label>Spiker tarzı <select data-v10="style"><option value="natural">Doğal</option><option value="excited">Çok coşkulu</option><option value="calm">Sakin</option></select></label><label class="v10-check"><input type="checkbox" data-v10="importantOnly"> Yalnız önemli anları anlat</label><label class="v10-check"><input type="checkbox" data-v10="slang"> Hafif maç argosu</label><label class="v10-check"><input type="checkbox" data-v10="analysis"> Boşluklarda maç analizi</label><label class="v10-check"><input type="checkbox" data-v10="chantWords"> Anlaşılır tezahürat lideri</label><label>Tribün yoğunluğu <input type="range" min="0" max="0.8" step="0.05" data-v10="crowdLevel"></label></div></details>`;panel.appendChild(box);box.querySelectorAll("[data-v10]").forEach(i=>{i.onchange=()=>{const k=i.dataset.v10;cfg[k]=i.type==="checkbox"?i.checked:i.type==="range"?+i.value:i.value;save()}})}box.querySelector('[data-v10="style"]').value=cfg.style;for(const k of["importantOnly","slang","analysis","chantWords"])box.querySelector(`[data-v10="${k}"]`).checked=!!cfg[k];box.querySelector('[data-v10="crowdLevel"]').value=cfg.crowdLevel}
function poll(){const s=snapshot();if(s.active&&!active){active=true;window.QF_COMMENTARY_V10_SUPPRESS_V8=true;ensureAudio();scheduleChant();enqueue(`${s.ownName} ile ${s.oppName} karşı karşıya. Maç saati hızla akacak ama önemli pozisyonları yayın kamerasından ayrıntılı izleyeceğiz.`,64,{priority:80,interrupt:true,kind:"intro"})}else if(!s.active&&active){active=false;window.QF_COMMENTARY_V10_SUPPRESS_V8=false;clearTimeout(chantTimer);enqueue(`Ve son düdük. Maç ${s.own||0}-${s.opp||0} sona erdi.`,70,{priority:90,interrupt:true,kind:"final"})}if(active){analysis();chantLeader()}renderControls();applyVolumes()}
document.addEventListener("pointerdown",unlock,{once:true,capture:true});document.addEventListener("keydown",()=>{if(!unlocked)unlock()},{once:true,capture:true});window.addEventListener("qf:v11-commentary",onMoment);window.addEventListener("qf:v9-event",onRaw);window.addEventListener("qf:v10-event",onRaw);setInterval(poll,650);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(poll,150),{once:true});else setTimeout(poll,150);
window.QF_COMMENTARY_V10={unlock,getSettings:()=>({...cfg}),setSetting:(k,v)=>{if(k in cfg){cfg[k]=v;save();return true}return false},state:()=>({...stats,active,unlocked,voice:voice?.name||"",queue:queue.length,speaking}),test:(type="goal")=>onMoment({detail:{type,phase:"result",text:type==="goal"?"GOOOOOOOLLL! Test golü!":`QA ${type}`,importance:100,excitement:100,final:true,side:"home",minute:88}})};
window.QF_COMMENTARY_V11=window.QF_COMMENTARY_V10;
})();
