(()=>{"use strict";const V=window.QF_V5;if(!V)return;V.pools={ENG:["ARS","CHE","MCI","MUN","LIV","EVE","TOT","SOU"],ESP:["BAR","RMA","ATM","SEV","VAL"],ITA:["JUV","INT","ACM","ROM"],GER:["BAY","BVB","SCH"],POR:["POR","BEN"],ELITE:["BAR","RMA","MCI","MUN","LIV","ARS","CHE","BAY","BVB","JUV","INT","ACM","PSG","ATM"]};
Object.assign(V.modes,{
 premier3:{id:"premier3",group:"competitive",name:"Premier Rush 3",icon:"🏴",desc:"İngiltere kulüplerinden 3 dakikalık hızlı bağlantı savaşı.",roundCount:100,optionCount:4,timeLimit:180,content:"player",rule:"first",rated:false,pool:"ENG"},
 premier5:{id:"premier5",group:"competitive",name:"Premier Masters 5",icon:"🦁",desc:"Premier kulüpleri, futbolcu ve hoca karması, 5 dakika.",roundCount:100,optionCount:6,timeLimit:300,content:"mixed",rule:"first",rated:true,pool:"ENG"},
 laliga3:{id:"laliga3",group:"competitive",name:"La Liga Rush",icon:"🇪🇸",desc:"İspanya kulüplerinde 3 dakikalık bağlantı yarışı.",roundCount:100,optionCount:6,timeLimit:180,content:"player",rule:"first",rated:false,pool:"ESP"},
 laliga5:{id:"laliga5",group:"competitive",name:"La Liga Masters",icon:"☀",desc:"Oyuncu ve teknik direktörlerle 5 dakikalık İspanya gecesi.",roundCount:100,optionCount:8,timeLimit:300,content:"mixed",rule:"first",rated:true,pool:"ESP"},
 seriea3:{id:"seriea3",group:"competitive",name:"Serie A Rush",icon:"🇮🇹",desc:"İtalya kulüplerinde 3 dakikalık hızlı maç.",roundCount:100,optionCount:6,timeLimit:180,content:"player",rule:"first",rated:false,pool:"ITA"},
 bundes3:{id:"bundes3",group:"competitive",name:"Bundes Rush",icon:"🇩🇪",desc:"Almanya kulüplerinde hızlı bağlantı düellosu.",roundCount:100,optionCount:4,timeLimit:180,content:"player",rule:"first",rated:false,pool:"GER"},
 elite5:{id:"elite5",group:"competitive",name:"Elite Europe 5",icon:"💎",desc:"Avrupa'nın büyük kulüplerinden 8 seçenekli rated maç.",roundCount:100,optionCount:8,timeLimit:300,content:"mixed",rule:"first",rated:true,pool:"ELITE"},
 managerBlitz3:{id:"managerBlitz3",group:"competitive",name:"Hoca Blitz 3",icon:"🧥",desc:"Teknik direktör bağlantıları, 4 seçenek, 3 dakika.",roundCount:100,optionCount:4,timeLimit:180,content:"manager",rule:"first",rated:false},
 managerExpert5:{id:"managerExpert5",group:"competitive",name:"Hoca Expert 5",icon:"🧩",desc:"8 seçenekli 5 dakikalık teknik direktör uzman modu.",roundCount:100,optionCount:8,timeLimit:300,content:"manager",rule:"first",rated:true},
 mixedChaos3:{id:"mixedChaos3",group:"competitive",name:"Chaos 3",icon:"🌪",desc:"8 seçenek, oyuncu+hoca, yalnız 3 dakika.",roundCount:100,optionCount:8,timeLimit:180,content:"mixed",rule:"first",rated:true},
 chillManagers:{id:"chillManagers",group:"chill",name:"Hoca Sohbeti",icon:"☕",desc:"Teknik direktör sorularını ratingsiz ve sakin tempoda çöz.",roundCount:100,optionCount:6,timeLimit:600,content:"manager",rule:"first",rated:false,chill:true},
 chillPremier:{id:"chillPremier",group:"chill",name:"Premier Chill",icon:"🌧",desc:"İngiltere kulüpleriyle 10 dakikalık rahat oyun.",roundCount:100,optionCount:4,timeLimit:600,content:"mixed",rule:"first",rated:false,chill:true,pool:"ENG"},
 soloPremier3:{id:"soloPremier3",group:"solo",name:"Solo Premier 3",icon:"🎯",desc:"Premier League havuzunda 3 dakikalık kişisel rekor.",roundCount:100,optionCount:6,timeLimit:180,content:"player",rule:"solo",rated:false,solo:true,pool:"ENG"},
 soloLaLiga3:{id:"soloLaLiga3",group:"solo",name:"Solo La Liga 3",icon:"🌞",desc:"İspanya kulüplerinde 3 dakikalık solo hız testi.",roundCount:100,optionCount:6,timeLimit:180,content:"player",rule:"solo",rated:false,solo:true,pool:"ESP"},
 soloExpert3:{id:"soloExpert3",group:"solo",name:"Solo Expert 3",icon:"🧠",desc:"8 seçenekli karma havuzda 3 dakikalık uzman testi.",roundCount:100,optionCount:8,timeLimit:180,content:"mixed",rule:"solo",rated:false,solo:true},
 soloManagerZen:{id:"soloManagerZen",group:"solo",name:"Hoca Zen",icon:"📚",desc:"Süre baskısı olmadan 50 teknik direktör bağlantısı.",roundCount:50,optionCount:6,timeLimit:0,content:"manager",rule:"solo",rated:false,solo:true}
});V.version="5.2.0";})();
