(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=s=>String(s||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
function svgFallback(text){const t=initials(text);return`data:image/svg+xml,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='320' height='400'><defs><linearGradient id='g' x1='0' x2='1'><stop stop-color='#102544'/><stop offset='1' stop-color='#07101f'/></linearGradient></defs><rect width='100%' height='100%' rx='28' fill='url(#g)'/><circle cx='160' cy='155' r='76' fill='#72dfff' fill-opacity='.09'/><text x='160' y='230' text-anchor='middle' font-size='72' font-weight='700' fill='#cceeff' font-family='Arial'>${t}</text></svg>`)}`}
function setPlaceholders(){const a=$('#createName'),b=$('#joinName');if(a)a.placeholder='Kullanıcı adını yaz';if(b)b.placeholder='Kullanıcı adını yaz'}
function connectionBadge(){let b=$('#connectionBadgeV4');if(!b){b=document.createElement('span');b.id='connectionBadgeV4';b.className='connection-badge';const actions=$('.top-actions');if(actions)actions.prepend(b)}const active=$('#gameScreen.active')||$('#lobbyScreen.active');b.textContent=navigator.onLine?(active?'● ODA AKTİF':'● HAZIR'):'○ ÇEVRİMDIŞI';b.classList.toggle('bad',!navigator.onLine)}
function buildSegments(select,id,values,label){if(!select||document.getElementById(id))return;const wrap=document.createElement('div');wrap.className='setting-block v4-setting';wrap.innerHTML=`<div class="setting-title"><span>${label}</span><b class="v4-setting-value">${esc(select.value)}</b></div><div class="choice-segments v4-segments">${values.map(v=>`<button type="button" data-value="${v}"><strong>${v}</strong><span>${v==4?'Hızlı':v==6?'Dengeli':v==8?'Zor':v==25?'Hızlı':v==50?'Uzun':'Tam gece'}</span></button>`).join('')}</div>`;select.insertAdjacentElement('afterend',wrap);select.classList.add('v4-native-select');wrap.querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{if(select.disabled)return;select.value=btn.dataset.value;select.dispatchEvent(new Event('change',{bubbles:true}));syncSegments()}))}
function syncSegments(){[['choiceCountSelect','choiceSegmentsV4'],['roundCountSelect','roundSegmentsV4']].forEach(([sid,wid])=>{const s=document.getElementById(sid),w=document.getElementById(wid);if(!s||!w)return;w.querySelector('.v4-setting-value').textContent=s.value;w.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b.dataset.value===s.value);b.disabled=s.disabled})})}
function setupLobbyControls(){const c=$('#choiceCountSelect'),r=$('#roundCountSelect');if(c){buildSegments(c,'choiceSegmentsV4',[4,6,8],'Seçenek sayısı');const w=c.nextElementSibling;if(w)w.id='choiceSegmentsV4'}if(r){buildSegments(r,'roundSegmentsV4',[25,50,100],'Kart sayısı');const w=r.nextElementSibling;if(w)w.id='roundSegmentsV4'}const card=$('.settings-card');if(card&&!$('#v4Volume')){const x=document.createElement('div');x.id='v4Volume';x.className='setting-block local-setting';const val=Math.round((window.QFV4Music?.volume??.52)*100);x.innerHTML=`<div class="setting-title"><span>Maç müziği</span><b id="v4VolumeLabel">${val}%</b></div><input id="v4VolumeInput" type="range" min="0" max="100" value="${val}" aria-label="Maç müziği seviyesi"><small>Özgün European Night stadyum müziği maç boyunca çalar.</small>`;card.insertBefore(x,card.querySelector('.primary-btn'));x.querySelector('input').addEventListener('input',e=>{const v=+e.target.value;$('#v4VolumeLabel').textContent=v+'%';window.QFV4Music?.setVolume(v/100)})}syncSegments()}
function themeFromRoom(){const code=$('#roomCodeText')?.textContent?.trim()||new URLSearchParams(location.search).get('room')||'';if(!code||code==='------')return;let h=0;for(const c of code)h=(h*31+c.charCodeAt(0))>>>0;document.body.dataset.theme=['royal','aurora','midnight','emerald'][h%4]}
function fitImage(img){if(img.dataset.v4fit)return;img.dataset.v4fit='1';const shell=img.closest('.image-shell');const player=img.closest('.player-photo');const team=img.closest('.team-logo');const apply=()=>{if(team){img.style.objectFit='contain';img.style.objectPosition='center';img.style.maxWidth='100%';img.style.maxHeight='100%'}else if(player){img.style.objectFit='cover';img.style.objectPosition='50% 18%';const ratio=img.naturalWidth/Math.max(1,img.naturalHeight);player.classList.toggle('wide',ratio>1.2);player.classList.toggle('tall',ratio<.65)}};if(img.complete)apply();else img.addEventListener('load',apply,{once:true});img.addEventListener('error',()=>{const id=player?.dataset.img||'',name=id&&window.QF_DATA?.players?.[id]?.name||$('#teamAName')?.textContent||'Futbol';img.src=svgFallback(name);img.style.objectFit='contain';if(shell)shell.classList.add('loaded')},{once:true})}
function decorateAnswers(){ $$('#answerGrid .answer-card').forEach((b,i)=>{if(!b.querySelector('.number-key')){const n=document.createElement('span');n.className='number-key';n.textContent=String(i+1);b.appendChild(n)}});$$('.image-shell img').forEach(fitImage)}
function preloadManifest(){const M=window.QF_IMAGES||{},urls=[...Object.values(M.teams||{}),...Object.values(M.players||{}).slice(0,28)];let i=0;const run=()=>{for(let n=0;n<4&&i<urls.length;n++,i++){const im=new Image;im.decoding='async';im.referrerPolicy='no-referrer';im.src=urls[i]}if(i<urls.length)setTimeout(run,180)};if('requestIdleCallback'in window)requestIdleCallback(run,{timeout:1200});else setTimeout(run,250)}
function keyboard(e){if(!$('#gameScreen.active')||e.repeat||/INPUT|SELECT|TEXTAREA/.test(document.activeElement?.tagName||''))return;const n=+e.key;if(n>=1&&n<=8){const b=$$('#answerGrid .answer-card')[n-1];if(b&&!b.disabled)b.click()}}
function versionChip(){if($('#v4Chip'))return;const brand=$('.brand');if(!brand)return;const x=document.createElement('span');x.id='v4Chip';x.className='season-chip';x.textContent='V4.2';brand.insertAdjacentElement('afterend',x)}
function tick(){setPlaceholders();connectionBadge();setupLobbyControls();syncSegments();themeFromRoom();decorateAnswers()}
setPlaceholders();versionChip();setupLobbyControls();connectionBadge();preloadManifest();decorateAnswers();
new MutationObserver(()=>requestAnimationFrame(tick)).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class','src','disabled']});
window.addEventListener('online',connectionBadge);window.addEventListener('offline',connectionBadge);document.addEventListener('keydown',keyboard);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw-v4.js?v=4.2.0').catch(()=>{});
setInterval(()=>{syncSegments();connectionBadge()},600);
})();
