(()=>{"use strict";const $=s=>document.querySelector(s),FAV='qf-v5-favorites',PREF='qf-v5-preferences';let fav=new Set(JSON.parse(localStorage.getItem(FAV)||'[]')),pref={contrast:false,large:false,compact:false,reduce:false,theme:'auto',...JSON.parse(localStorage.getItem(PREF)||'{}')},installPrompt=null;
function savePref(){localStorage.setItem(PREF,JSON.stringify(pref));applyPref()}function applyPref(){document.body.classList.toggle('high-contrast',!!pref.contrast);document.body.classList.toggle('large-ui',!!pref.large);document.body.classList.toggle('compact-ui',!!pref.compact);document.body.classList.toggle('force-reduced-motion',!!pref.reduce);if(pref.theme!=='auto')document.body.dataset.theme=pref.theme}
function installToolbar(){const tabs=$('.mode-tabs'),grid=$('#modeGrid');if(!tabs||!grid||$('#modeToolbar'))return;tabs.insertAdjacentHTML('afterend','<div id="modeToolbar" class="mode-toolbar"><label class="mode-search"><span>⌕</span><input id="modeSearch" placeholder="Mod ara: Premier, hoca, solo..." autocomplete="off"></label><button id="favOnlyBtn" class="mode-tool-btn" aria-pressed="false">☆ Favoriler</button><button id="randomModeBtn" class="mode-tool-btn">⤨ Rastgele</button></div>');$('#modeSearch').addEventListener('input',filter);$('#favOnlyBtn').onclick=()=>{const b=$('#favOnlyBtn'),on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));b.textContent=on?'★ Favoriler':'☆ Favoriler';filter()};$('#randomModeBtn').onclick=()=>{const cards=[...grid.querySelectorAll('.mode-card')].filter(x=>x.style.display!=='none');if(cards.length)cards[Math.floor(Math.random()*cards.length)].click()};decorate();new MutationObserver(()=>{decorate();filter()}).observe(grid,{childList:true})}
function decorate(){document.querySelectorAll('.mode-card').forEach(card=>{const id=card.dataset.mode;if(!id||card.querySelector('.mode-fav'))return;const star=document.createElement('span');star.className='mode-fav';star.textContent=fav.has(id)?'★':'☆';star.title='Favori modu değiştir';star.onclick=e=>{e.preventDefault();e.stopPropagation();fav.has(id)?fav.delete(id):fav.add(id);localStorage.setItem(FAV,JSON.stringify([...fav]));star.textContent=fav.has(id)?'★':'☆';filter()};card.appendChild(star)})}
function filter(){const q=($('#modeSearch')?.value||'').trim().toLocaleLowerCase('tr'),only=$('#favOnlyBtn')?.getAttribute('aria-pressed')==='true';document.querySelectorAll('.mode-card').forEach(c=>{const text=c.textContent.toLocaleLowerCase('tr'),ok=(!q||text.includes(q))&&(!only||fav.has(c.dataset.mode));c.style.display=ok?'':'none'})}
function settings(){if($('#extrasSettingsBtn'))return;const top=$('.top-actions');if(!top)return;const btn=document.createElement('button');btn.id='extrasSettingsBtn';btn.className='icon-btn';btn.title='Görünüm ve erişilebilirlik';btn.textContent='⚙';top.insertBefore(btn,$('#soundBtn'));document.body.insertAdjacentHTML('beforeend',`<div id="extrasSettingsBackdrop" class="extras-backdrop hidden"><section class="extras-settings"><button id="extrasClose" class="modal-close">×</button><div class="eyebrow">KİŞİSELLEŞTİR</div><h2>Görünüm & Erişilebilirlik</h2><div class="extras-grid"><label><input type="checkbox" id="prefContrast"> Yüksek kontrast</label><label><input type="checkbox" id="prefLarge"> Büyük yazı ve kontroller</label><label><input type="checkbox" id="prefCompact"> Kompakt mod kartları</label><label><input type="checkbox" id="prefReduce"> Hareketleri azalt</label></div><label class="extras-select">Tema<select id="prefTheme"><option value="auto">Odaya göre otomatik</option><option value="royal">Royal</option><option value="aurora">Aurora</option><option value="midnight">Midnight</option><option value="emerald">Emerald</option></select></label><div class="extras-actions"><button id="installAppBtn" class="secondary-btn">Uygulamayı Yükle</button><button id="exportProfileBtn" class="secondary-btn">Profili Yedekle</button><button id="clearVisualBtn" class="ghost-btn">Görünümü Sıfırla</button></div><small>Bu ayarlar yalnız bu cihazda saklanır. Global skor/profil verisi ayrı tutulur.</small></section></div>`);const back=$('#extrasSettingsBackdrop'),open=()=>{syncControls();back.classList.remove('hidden')},close=()=>back.classList.add('hidden');btn.onclick=open;$('#extrasClose').onclick=close;back.onclick=e=>{if(e.target===back)close()};for(const [id,key] of [['prefContrast','contrast'],['prefLarge','large'],['prefCompact','compact'],['prefReduce','reduce']])$('#'+id).onchange=e=>{pref[key]=e.target.checked;savePref()};$('#prefTheme').onchange=e=>{pref.theme=e.target.value;savePref()};$('#clearVisualBtn').onclick=()=>{pref={contrast:false,large:false,compact:false,reduce:false,theme:'auto'};savePref();syncControls()};$('#installAppBtn').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null}else alert('Tarayıcı uygun olduğunda yükleme seçeneği burada etkinleşir.')};$('#exportProfileBtn').onclick=exportProfile}
function syncControls(){for(const [id,key] of [['prefContrast','contrast'],['prefLarge','large'],['prefCompact','compact'],['prefReduce','reduce']])if($('#'+id))$('#'+id).checked=!!pref[key];if($('#prefTheme'))$('#prefTheme').value=pref.theme}
function exportProfile(){const data={exportedAt:new Date().toISOString(),profile:JSON.parse(localStorage.getItem('qf-v5-profile')||'{}'),history:JSON.parse(localStorage.getItem('qf-v5-history')||'[]'),favorites:[...fav],preferences:pref};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='quiz-football-profile.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function network(){const chip=$('#cloudChip');const paint=()=>{document.body.classList.toggle('is-offline',!navigator.onLine);if(chip&&!navigator.onLine)chip.textContent='○ ÇEVRİMDIŞI • SOLO HAZIR'};addEventListener('online',paint);addEventListener('offline',paint);paint()}
function shortcuts(){document.addEventListener('keydown',e=>{if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||'')){e.preventDefault();$('#modeSearch')?.focus()}if(e.altKey&&e.key.toLowerCase()==='r')$('#randomModeBtn')?.click()})}
function pwa(){addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw-v5.js').catch(()=>{})}
function protectTheme(){new MutationObserver(()=>{if(pref.theme!=='auto'&&document.body.dataset.theme!==pref.theme)document.body.dataset.theme=pref.theme}).observe(document.body,{attributes:true,attributeFilter:['data-theme']})}
applyPref();installToolbar();settings();network();shortcuts();pwa();protectTheme();window.QFExtras={favorites:()=>[...fav],preferences:()=>({...pref})};
})();
