(()=>{"use strict";
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=a=>a[Math.floor(Math.random()*a.length)],now=()=>performance.now();
const POS_HOME=[[.06,.50],[.18,.17],[.19,.39],[.19,.61],[.18,.83],[.38,.22],[.39,.50],[.38,.78],[.63,.20],[.69,.50],[.63,.80]];
const POS_AWAY=POS_HOME.map(([x,y])=>[1-x,y]);
const COLORS={home:"#2ea8ff",away:"#e8c66a",line:"rgba(238,248,244,.78)",grass1:"#12613f",grass2:"#0f5538"};
function ensure(match,ctx={}){if(match.v9)return match.v9;const homeIds=[...(ctx.xi||ctx.homeClub?.xi||[])].slice(0,11),awayIds=[...(ctx.awayClub?.xi||[])].slice(0,11);match.v9={version:9,started:now(),possessionHome:50,possessionAway:50,passesHome:0,passesAway:0,cornersHome:0,cornersAway:0,foulsHome:0,foulsAway:0,yellowHome:0,yellowAway:0,redHome:0,redAway:0,offsidesHome:0,offsidesAway:0,savesHome:0,savesAway:0,freeKicksHome:0,freeKicksAway:0,penaltiesHome:0,penaltiesAway:0,substitutionsHome:0,substitutionsAway:0,injuriesHome:[],injuriesAway:[],homeIds,awayIds,homeStamina:Array(11).fill(100),awayStamina:Array(11).fill(100),visual:{home:makePlayers(POS_HOME,"home",homeIds),away:makePlayers(POS_AWAY,"away",awayIds),ball:{x:.5,y:.5,tx:.5,ty:.5,trail:[]},focus:{x:.5,y:.5,targetX:.5,targetY:.5},event:"Maç başladı",eventType:"kickoff",eventUntil:0,goalUntil:0,camera:.02,lastUi:0},lastStep:now(),half:false};return match.v9}
function makePlayers(pos,team,ids){return pos.map(([x,y],i)=>({x,y,tx:x,ty:y,baseX:x,baseY:y,team,id:ids[i]||"",num:i===0?1:i+1,stamina:100}))}
function nameOf(id,ctx){return ctx.playerMeta?.[id]?.name||ctx.players?.[id]?.name||"Oyuncu"}
function shortName(id,ctx){const n=nameOf(id,ctx).trim().split(/\s+/);return n.length>1?n[n.length-1]:n[0]}
function actorIndex(side,ctx,preferAttack=true){const ids=side==="home"?ctx.xi||ctx.homeClub?.xi||[]:ctx.awayClub?.xi||[];if(!ids.length)return Math.floor(Math.random()*11);const pm=ctx.playerMeta||{};const weights=ids.map((id,i)=>{const p=pm[id]||{};let w=1;if(preferAttack&&["ST","LW","RW","CAM"].includes(p.pos))w+=3;if(!preferAttack&&["GK","CB","LB","RB"].includes(p.pos))w+=2;return{idx:i,w}});let total=weights.reduce((s,x)=>s+x.w,0),r=Math.random()*total;for(const x of weights){r-=x.w;if(r<=0)return x.idx}return weights[0]?.idx||0}
function setScene(v,side,type,actor=9){const own=side==="home"?v.visual.home:v.visual.away,opp=side==="home"?v.visual.away:v.visual.home,dir=side==="home"?1:-1;for(const p of own){p.tx=clamp(p.baseX+dir*.10+.03*(Math.random()-.5),.04,.96);p.ty=clamp(p.baseY+.06*(Math.random()-.5),.04,.96)}for(const p of opp){p.tx=clamp(p.baseX+dir*.055+.025*(Math.random()-.5),.04,.96);p.ty=clamp(p.baseY+.04*(Math.random()-.5),.04,.96)}const a=own[Math.min(actor,own.length-1)]||own[0];if(a){a.tx=side==="home"?.78:.22;a.ty=.3+Math.random()*.4;v.visual.ball.tx=a.tx+dir*.035;v.visual.ball.ty=a.ty;v.visual.focus.targetX=a.tx;v.visual.focus.targetY=a.ty}v.visual.eventType=type;v.visual.eventUntil=now()+1500;v.visual.camera=type==="goal"?.10:type==="shot"||type==="penalty"?.075:.045}
function eventText(v,text,type,side,ctx,actor){v.visual.event=text;v.visual.eventType=type;v.visual.eventUntil=now()+2200;if(type==="goal")v.visual.goalUntil=now()+1500;setScene(v,side,type,actor);try{window.dispatchEvent(new CustomEvent("qf:v9-event",{detail:{type,text,side,minute:ctx.match?.minute||0}}))}catch{}return{text,type,side}}
function decayStamina(v,minute){const drain=.10+(minute/90)*.08;v.homeStamina=v.homeStamina.map((x,i)=>clamp(x-drain*(i===0?.45:1),42,100));v.awayStamina=v.awayStamina.map((x,i)=>clamp(x-drain*(i===0?.45:1),42,100));v.visual.home.forEach((p,i)=>p.stamina=v.homeStamina[i]||100);v.visual.away.forEach((p,i)=>p.stamina=v.awayStamina[i]||100)}
function maybeSub(v,side,minute,ctx){if(minute<55)return null;const arr=side==="home"?v.homeStamina:v.awayStamina,key=side==="home"?"substitutionsHome":"substitutionsAway";if(v[key]>=5)return null;let idx=-1,min=101;arr.forEach((s,i)=>{if(i&&s<min){min=s;idx=i}});if(idx<0||min>64)return null;arr[idx]=91;v[key]++;const ids=side==="home"?v.homeIds:v.awayIds,bench=side==="home"?(ctx.club?.bench||[]):[];let incoming="Taze oyuncu";if(side==="home"&&bench.length){const b=bench.find(id=>!ids.includes(id));if(b){ids[idx]=b;v.visual.home[idx].id=b;incoming=nameOf(b,ctx)}}const outgoing=nameOf(ids[idx],ctx);return`${Math.round(minute)}' Değişiklik: ${incoming} oyunda. Teknik direktör tempoyu tazeliyor.`}
function weightedSide(homeStrength,awayStrength,homeMomentum=0,awayMomentum=0){const h=clamp(.5+(homeStrength-awayStrength)/220+(homeMomentum-awayMomentum)/650,.27,.73);return Math.random()<h?"home":"away"}
function chanceQuality(side,ctx,momentum){const me=side==="home"?ctx.strength:(ctx.opponent?.strength||ctx.awayClub?.strength||78),op=side==="home"?(ctx.opponent?.strength||ctx.awayClub?.strength||78):ctx.strength;const base=.055+Math.random()*.27+(me-op)/380+(momentum||0)/280;return clamp(base,.025,.72)}
function shootSolo(match,v,side,ctx,type="open"){const actor=actorIndex(side,ctx,true),m=side==="home"?match.momentum||0:0,xg=type==="penalty"?.76:type==="free"?clamp(.10+Math.random()*.22,.08,.38):chanceQuality(side,ctx,m);const home=side==="home";if(home){match.xgFor=(match.xgFor||0)+xg;match.shotsFor=(match.shotsFor||0)+1}else{match.xgAgainst=(match.xgAgainst||0)+xg;match.shotsAgainst=(match.shotsAgainst||0)+1}const atk=home?(1+(match.momentum||0)/130):1,goalProb=clamp(xg*(.36+atk*.31),.015,.82),r=Math.random();const player=side==="home"?nameOf(v.homeIds[actor],ctx):"Rakip oyuncu";if(r<goalProb){if(home){match.home++;match.momentum=0;match.streak=0;match.multiplier=1}else match.away++;return eventText(v,`${Math.round(match.minute)}' GOL! ${player} bitirdi. ${home?"Quiz momentumu yeniden 0'a döndü.":"Rakip fırsatı değerlendirdi."}`,"goal",side,{match},actor)}if(r<goalProb+.22){if(home)v.savesAway++;else v.savesHome++;return eventText(v,`${Math.round(match.minute)}' ${player} vurdu, kaleci müthiş çıkardı!`,"save",side,{match},actor)}if(r<goalProb+.34)return eventText(v,`${Math.round(match.minute)}' ${player} vurdu, top direkten döndü!`,"post",side,{match},actor);return eventText(v,`${Math.round(match.minute)}' ${player} şutunu gönderdi, top auta çıktı.`,"miss",side,{match},actor)}
function stepSolo(match,ctx){ctx={...ctx,match};const v=ensure(match,ctx),t=ctx.now||now(),elapsed=ctx.elapsed??(t-match.start);match.minute=clamp(elapsed/match.duration*90,0,90);decayStamina(v,match.minute);if(!v.half&&match.minute>=45){v.half=true;return eventText(v,"45' İlk yarı tamamlandı. Teknik direktör kısa talimatlarla takımı yeniden sahaya gönderiyor.","half","home",{match},6)}if(t-match.lastEvent<1550)return null;match.lastEvent=t;const side=weightedSide(ctx.strength,ctx.opponent?.strength||78,match.momentum||0,0),home=side==="home",roll=Math.random(),minute=Math.round(match.minute);v.possessionHome=clamp(v.possessionHome+(home?1.1:-1.1)+(Math.random()-.5)*1.5,32,68);v.possessionAway=100-v.possessionHome;if(home)v.passesHome+=Math.round(4+Math.random()*8);else v.passesAway+=Math.round(4+Math.random()*8);const sub=maybeSub(v,side,match.minute,ctx);if(sub&&Math.random()<.38)return eventText(v,sub,"sub",side,{match},6);
if(roll<.08){const key=home?"foulsHome":"foulsAway";v[key]++;const card=Math.random()<.28;if(card){v[home?"yellowHome":"yellowAway"]++;return eventText(v,`${minute}' Sert müdahale! Hakem sarı kartını çıkardı.`,"card",side,{match},5)}return eventText(v,`${minute}' Orta sahada faul. Oyun duran topla devam edecek.`,"foul",side,{match},5)}
if(roll<.13){v[home?"offsidesHome":"offsidesAway"]++;return eventText(v,`${minute}' Savunma arkasına koşu fakat bayrak havada: ofsayt.`,"offside",side,{match},9)}
if(roll<.19){v[home?"cornersHome":"cornersAway"]++;setScene(v,side,"corner",9);if(Math.random()<.46)return shootSolo(match,v,side,ctx,"corner");return eventText(v,`${minute}' Korner kullanıldı, savunma ilk topu uzaklaştırdı.`,"corner",side,{match},9)}
if(roll<.24){v[home?"freeKicksHome":"freeKicksAway"]++;if(Math.random()<.42)return shootSolo(match,v,side,ctx,"free");return eventText(v,`${minute}' Tehlikeli serbest vuruş baraja takıldı.`,"free",side,{match},9)}
if(roll<.265){const dangerous=Math.random()<.32;if(dangerous){v[home?"penaltiesHome":"penaltiesAway"]++;return shootSolo(match,v,side,ctx,"penalty")}return eventText(v,`${minute}' Ceza sahası çevresinde temas var, hakem devam diyor.`,"duel",side,{match},8)}
if(roll<.29){const idx=actorIndex(side,ctx,false),ids=home?v.homeIds:v.awayIds,p=nameOf(ids[idx],ctx);v[home?"injuriesHome":"injuriesAway"].push({id:ids[idx]||"",minute});return eventText(v,`${minute}' ${p} kısa süreli sakatlık yaşıyor; sağlık ekibi oyuna devam işareti verdi.`,"injury",side,{match},idx)}
return shootSolo(match,v,side,ctx,"open")}
function stepOnline(match,ctx){ctx={...ctx,match};const v=ensure(match,{...ctx,xi:ctx.homeClub?.xi,homeClub:ctx.homeClub,awayClub:ctx.awayClub}),t=ctx.now||now(),elapsed=ctx.elapsed??(t-match.start);match.minute=clamp(elapsed/match.duration*90,0,90);decayStamina(v,match.minute);if(!v.half&&match.minute>=45){v.half=true;return eventText(v,"45' İlk yarı bitti; iki başkan da ikinci yarı için yeniden quiz savaşına hazırlanıyor.","half","home",{match},6)}if(t-match.lastEvent<1450)return null;match.lastEvent=t;const side=weightedSide(ctx.homeClub?.strength||78,ctx.awayClub?.strength||78,match.momentumHome||0,match.momentumAway||0),home=side==="home",minute=Math.round(match.minute),roll=Math.random();v.possessionHome=clamp(v.possessionHome+(home?1.2:-1.2)+(Math.random()-.5)*1.5,30,70);v.possessionAway=100-v.possessionHome;if(home)v.passesHome+=Math.round(4+Math.random()*8);else v.passesAway+=Math.round(4+Math.random()*8);
if(roll<.07){v[home?"foulsHome":"foulsAway"]++;if(Math.random()<.25){v[home?"yellowHome":"yellowAway"]++;return eventText(v,`${minute}' ${home?ctx.homeClub.short:ctx.awayClub.short} oyuncusuna sarı kart.`,"card",side,{match},5)}return eventText(v,`${minute}' Orta sahada faul; tempo bir anlığına düştü.`,"foul",side,{match},5)}
if(roll<.12){v[home?"offsidesHome":"offsidesAway"]++;return eventText(v,`${minute}' ${home?ctx.homeClub.short:ctx.awayClub.short} hücumunda ofsayt bayrağı kalktı.`,"offside",side,{match},9)}
if(roll<.17){v[home?"cornersHome":"cornersAway"]++;return eventText(v,`${minute}' ${home?ctx.homeClub.short:ctx.awayClub.short} korner kazandı; ceza sahası kalabalık.`,"corner",side,{match},9)}
const mom=home?match.momentumHome:match.momentumAway,xg=chanceQuality(side,{strength:home?ctx.homeClub.strength:ctx.awayClub.strength,opponent:{strength:home?ctx.awayClub.strength:ctx.homeClub.strength}},mom),atk=home?match.multHome:match.multAway,goalProb=clamp(xg*(.31+atk*.24),.015,.75);if(home){match.xgHome+=xg;match.shotsHome++}else{match.xgAway+=xg;match.shotsAway++}const r=Math.random(),club=home?ctx.homeClub:ctx.awayClub,actor=actorIndex(side,{homeClub:ctx.homeClub,awayClub:ctx.awayClub},true);if(r<goalProb){if(home){match.home++;match.momentumHome=0;match.multHome=1}else{match.away++;match.momentumAway=0;match.multAway=1}return eventText(v,`${minute}' GOL ${club.short}! Quiz momentumu sıfırlandı.`,"goal",side,{match},actor)}if(r<goalProb+.22){if(home)v.savesAway++;else v.savesHome++;return eventText(v,`${minute}' ${club.short} şutunda kaleci kritik kurtarış yaptı.`,"save",side,{match},actor)}if(r<goalProb+.33)return eventText(v,`${minute}' ${club.short} direğe takıldı!`,"post",side,{match},actor);return eventText(v,`${minute}' ${club.short} şutu dışarı gitti.`,"miss",side,{match},actor)}
function project(w,h,x,y){const top=58,bottom=24,m=top+(bottom-top)*y;return[m+x*(w-m*2),26+y*(h-48)]}
function poly(g,pts,fill,stroke=null){g.beginPath();pts.forEach((p,i)=>i?g.lineTo(...p):g.moveTo(...p));g.closePath();if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}}
function lineNorm(g,w,h,points){g.beginPath();points.forEach(([x,y],i)=>{const p=project(w,h,x,y);i?g.lineTo(...p):g.moveTo(...p)});g.stroke()}
function pitch(g,w,h){const lite=document.body.classList.contains("performance-lite");const bg=g.createLinearGradient(0,0,0,h);bg.addColorStop(0,"#08161b");bg.addColorStop(.22,"#0e2b25");bg.addColorStop(1,"#061217");g.fillStyle=bg;g.fillRect(0,0,w,h);for(let i=0;i<(lite?12:72);i++){const x=(i*97)%w,y=6+((i*47)%30),a=.12+((i%5)/40);g.fillStyle=`rgba(218,232,226,${a})`;g.fillRect(x,y,2,2)}for(let i=0;i<(lite?6:10);i++){const bands=lite?6:10,y0=i/bands,y1=(i+1)/bands,c=i%2?COLORS.grass1:COLORS.grass2;poly(g,[project(w,h,0,y0),project(w,h,1,y0),project(w,h,1,y1),project(w,h,0,y1)],c)}g.lineWidth=1.6;g.strokeStyle=COLORS.line;lineNorm(g,w,h,[[0,0],[1,0],[1,1],[0,1],[0,0]]);lineNorm(g,w,h,[[.5,0],[.5,1]]);const cp=project(w,h,.5,.5),scale=(h-48)*.12;g.beginPath();g.arc(cp[0],cp[1],scale,0,Math.PI*2);g.stroke();lineNorm(g,w,h,[[0,.22],[.16,.22],[.16,.78],[0,.78]]);lineNorm(g,w,h,[[1,.22],[.84,.22],[.84,.78],[1,.78]]);lineNorm(g,w,h,[[0,.36],[.07,.36],[.07,.64],[0,.64]]);lineNorm(g,w,h,[[1,.36],[.93,.36],[.93,.64],[1,.64]]);if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){if(!lite){const far=g.createLinearGradient(0,0,0,60);far.addColorStop(0,"rgba(103,181,255,.28)");far.addColorStop(1,"rgba(103,181,255,0)");g.fillStyle=far;g.fillRect(0,0,w,75)}}}}}}}}}}}}}}}}}}}}}}
function updateVisual(v,dt){const all=[...v.visual.home,...v.visual.away];for(const p of all){const fatigue=clamp((p.stamina||100)/100,.55,1);p.x+=(p.tx-p.x)*Math.min(.13*fatigue+dt*.8,.22);p.y+=(p.ty-p.y)*Math.min(.13*fatigue+dt*.8,.22);if(Math.abs(p.x-p.tx)<.015&&Math.random()<.015){p.tx=clamp(p.baseX+(Math.random()-.5)*.055,.03,.97);p.ty=clamp(p.baseY+(Math.random()-.5)*.07,.03,.97)}}const b=v.visual.ball;b.trail.unshift([b.x,b.y]);b.trail=b.trail.slice(0,7);b.x+=(b.tx-b.x)*.20;b.y+=(b.ty-b.y)*.20;if(Math.hypot(b.tx-b.x,b.ty-b.y)<.025&&Math.random()<.04){const team=Math.random()<v.possessionHome/100?v.visual.home:v.visual.away,p=pick(team);if(p){b.tx=p.x;b.ty=p.y}}const f=v.visual.focus;f.x+=(f.targetX-f.x)*.08;f.y+=(f.targetY-f.y)*.08;v.visual.camera+=(0-v.visual.camera)*.035}
function player(g,w,h,p,color,ctx){const [x,y]=project(w,h,p.x,p.y),pers=.70+p.y*.42,r=7.2*pers,lite=document.body.classList.contains("performance-lite");if(lite){g.fillStyle=color;g.beginPath();g.arc(x,y,r*.88,0,Math.PI*2);g.fill();g.fillStyle="#fff";g.font=`700 ${Math.max(7,8*pers)}px system-ui`;g.textAlign="center";g.textBaseline="middle";g.fillText(String(p.num),x,y);return}g.save();g.globalAlpha=.22;g.fillStyle="#000";g.beginPath();g.ellipse(x+2,y+r*.95,r*1.15,r*.43,0,0,Math.PI*2);g.fill();g.globalAlpha=1;g.fillStyle=color;g.strokeStyle="rgba(255,255,255,.78)";g.lineWidth=1.2;g.beginPath();g.moveTo(x-r*.8,y+r*.4);g.lineTo(x-r*.52,y-r*.55);g.quadraticCurveTo(x,y-r*1.02,x+r*.52,y-r*.55);g.lineTo(x+r*.8,y+r*.4);g.closePath();g.fill();g.stroke();g.fillStyle="#fff";g.font=`700 ${Math.max(7,8*pers)}px system-ui`;g.textAlign="center";g.textBaseline="middle";g.fillText(String(p.num),x,y-r*.05);if(p.id&&p.y>.68){g.font="600 8px system-ui";g.fillStyle="rgba(255,255,255,.9)";g.fillText(shortName(p.id,ctx).slice(0,11),x,y+r*1.7)}g.restore()}
function renderCanvas(c,match,ctx,online=false){const v=ensure(match,ctx),w=Math.max(640,c.clientWidth||640),h=Math.round(w*9/16),dpr=Math.min(devicePixelRatio||1,document.body.classList.contains("performance-lite")?1:1.5);if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr)}const g=c.getContext("2d"),t=now();g.setTransform(dpr,0,0,dpr,0,0);g.clearRect(0,0,w,h);updateVisual(v,.016);g.save();const z=1+v.visual.camera*.25,fp=project(w,h,v.visual.focus.x,v.visual.focus.y);g.translate((w/2-fp[0])*.10,(h/2-fp[1])*.06);g.translate(w/2,h/2);g.scale(z,z);g.translate(-w/2,-h/2);pitch(g,w,h);for(const p of v.visual.ball.trail.slice().reverse()){const q=project(w,h,p[0],p[1]);g.fillStyle="rgba(255,255,255,.10)";g.beginPath();g.arc(q[0],q[1],2,0,Math.PI*2);g.fill()}const homeColor=ctx.club?.colors?.primary||ctx.homeClub?.color||COLORS.home,awayColor=ctx.awayColor||ctx.awayClub?.color||COLORS.away;const sorted=[...v.visual.home.map(p=>({p,c:homeColor})),...v.visual.away.map(p=>({p,c:awayColor}))].sort((a,b)=>a.p.y-b.p.y);for(const x of sorted)player(g,w,h,x.p,x.c,ctx);const bp=project(w,h,v.visual.ball.x,v.visual.ball.y),bs=3.6+v.visual.ball.y*2;g.fillStyle="rgba(0,0,0,.24)";g.beginPath();g.ellipse(bp[0]+2,bp[1]+5,bs*1.2,bs*.42,0,0,Math.PI*2);g.fill();g.fillStyle="#f7f7f4";g.strokeStyle="#172027";g.lineWidth=1;g.beginPath();g.arc(bp[0],bp[1],bs,0,Math.PI*2);g.fill();g.stroke();g.restore();g.fillStyle="rgba(3,10,14,.78)";g.fillRect(14,13,176,31);g.fillStyle="#fff";g.font="700 11px system-ui";g.fillText("MATCH ENGINE 2.0 • V9",27,32);const ev=v.visual.event||"Canlı maç";const tw=Math.min(w-40,Math.max(270,g.measureText(ev).width+36));g.fillStyle="rgba(4,10,14,.82)";g.fillRect((w-tw)/2,h-43,tw,29);g.fillStyle="#f3f7f5";g.font="600 12px system-ui";g.textAlign="center";g.fillText(ev,w/2,h-24);g.textAlign="left";if(v.visual.goalUntil>t){g.fillStyle="rgba(4,15,12,.56)";g.fillRect(0,0,w,h);g.fillStyle="#fff";g.textAlign="center";g.font=`900 ${Math.min(68,w*.09)}px system-ui`;g.fillText("GOL!",w/2,h*.48);g.font="700 15px system-ui";g.fillText("QUIZ MOMENTUMU YENİDEN BAŞLIYOR",w/2,h*.56);g.textAlign="left"}updateOverlay(match,v,online);return true}
function updateOverlay(match,v,online){const id=online?"v9OnlineStats":"v9SoloStats",canvas=document.getElementById(online?"v7OnlineCanvas":"v7MatchCanvas");if(!canvas)return;let el=document.getElementById(id);if(!el){el=document.createElement("div");el.id=id;el.className="v9-match-stats";canvas.insertAdjacentElement("afterend",el)}if(now()-v.visual.lastUi<350)return;v.visual.lastUi=now();el.innerHTML=`<span><b>${Math.round(v.possessionHome)}%</b> Top</span><span><b>${v.passesHome}</b> Pas</span><span><b>${v.cornersHome}</b> Korner</span><span><b>${v.foulsHome}</b> Faul</span><span><b>${v.yellowHome}</b> 🟨</span><span><b>${v.offsidesHome}</b> Ofsayt</span><span><b>${v.savesHome}</b> Kurtarış</span><span><b>${v.substitutionsHome}</b> Değişiklik</span>`}
function drawSolo(c,match,club,ctx={}){return renderCanvas(c,match,{...ctx,club,xi:club.xi,playerMeta:ctx.playerMeta||window.QF_V7?.playerMeta},false)}
function drawOnline(c,match,homeClub,awayClub){return renderCanvas(c,match,{homeClub,awayClub,xi:homeClub?.xi,playerMeta:window.QF_V7?.playerMeta||{}},true)}
function summary(match){const v=match?.v9;if(!v)return{};return{possession:v.possessionHome,passes:v.passesHome,corners:v.cornersHome,fouls:v.foulsHome,yellow:v.yellowHome,red:v.redHome,offsides:v.offsidesHome,saves:v.savesHome,subs:v.substitutionsHome,injuries:v.injuriesHome.length,matchEngine:9}}
window.QF_MATCH_V9={ensure,stepSolo,stepOnline,drawSolo,drawOnline,summary,state:m=>m?.v9||null};
})();