(()=>{"use strict";
const KEY="qf-v13-graphics",defaults={enabled:true,quality:"auto"},clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let cfg=load(),scene=null,canvas=null,sourceCanvas=null,raf=0,last=performance.now(),lastRender=0,level=2,avgIntervals=[],lastQualityChange=0,lastMoment=null,oldSolo=null,oldOnline=null,bypassInstalled=false,sizeCache=null,matrixPool=[],matrixPoolIndex=0,lastHudUpdate=0,lastHudText="",camState=null;
const stats={frames:0,drawCalls:0,level:2,targetFps:60,avgFps:60,renderMs:0,webgl2:false,renderer:"",software:false,active:false,fallback:false,players:0,instances:0};
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{...defaults}}}function save(){localStorage.setItem(KEY,JSON.stringify(cfg))}
function mat4(){const i=matrixPoolIndex++;return matrixPool[i]||(matrixPool[i]=new Float32Array(16))}
function trs(x,y,z,sx=1,sy=1,sz=1,ry=0,rx=0){const o=mat4(),cy=Math.cos(ry),syy=Math.sin(ry),cx=Math.cos(rx),sxx=Math.sin(rx);o[0]=cy*sx;o[1]=syy*sxx*sx;o[2]=-syy*cx*sx;o[4]=0;o[5]=cx*sy;o[6]=sxx*sy;o[8]=syy*sz;o[9]=-cy*sxx*sz;o[10]=cy*cx*sz;o[12]=x;o[13]=y;o[14]=z;o[15]=1;return o}
function perspective(fovy,aspect,near,far){const o=mat4(),f=1/Math.tan(fovy/2),nf=1/(near-far);o[0]=f/aspect;o[5]=f;o[10]=(far+near)*nf;o[11]=-1;o[14]=2*far*near*nf;return o}
function lookAt(eye,target,up=[0,1,0]){const o=mat4();let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx;l=Math.hypot(xx,xy,xz)||1;xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;o[0]=xx;o[1]=yx;o[2]=zx;o[4]=xy;o[5]=yy;o[6]=zy;o[8]=xz;o[9]=yz;o[10]=zz;o[12]=-(xx*eye[0]+xy*eye[1]+xz*eye[2]);o[13]=-(yx*eye[0]+yy*eye[1]+yz*eye[2]);o[14]=-(zx*eye[0]+zy*eye[1]+zz*eye[2]);o[15]=1;return o}
function cubeMesh(){const p=[],n=[],idx=[],faces=[[[0,0,-1],[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1]],[[0,0,1],[-1,-1,1],[-1,1,1],[1,1,1],[1,-1,1]],[[-1,0,0],[-1,-1,-1],[-1,1,-1],[-1,1,1],[-1,-1,1]],[[1,0,0],[1,-1,-1],[1,-1,1],[1,1,1],[1,1,-1]],[[0,1,0],[-1,1,-1],[1,1,-1],[1,1,1],[-1,1,1]],[[0,-1,0],[-1,-1,-1],[-1,-1,1],[1,-1,1],[1,-1,-1]]];for(const f of faces){const b=p.length/3;for(let j=1;j<5;j++){p.push(...f[j]);n.push(...f[0])}idx.push(b,b+1,b+2,b,b+2,b+3)}return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(idx)}}
function sphereMesh(lat=7,lon=10){const p=[],n=[],i=[];for(let y=0;y<=lat;y++){const ph=y/lat*Math.PI;for(let x=0;x<=lon;x++){const th=x/lon*Math.PI*2,nx=Math.sin(ph)*Math.cos(th),ny=Math.cos(ph),nz=Math.sin(ph)*Math.sin(th);p.push(nx,ny,nz);n.push(nx,ny,nz)}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){const a=y*(lon+1)+x,b=a+lon+1;i.push(a,b,a+1,b,b+1,a+1)}return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(i)}}
function cylinderMesh(seg=8){const p=[],n=[],i=[];for(let y=0;y<=1;y++){const yy=y?1:-1;for(let s=0;s<=seg;s++){const a=s/seg*Math.PI*2,x=Math.cos(a),z=Math.sin(a);p.push(x,yy,z);n.push(x,0,z)}}for(let s=0;s<seg;s++){const a=s,b=s+1,c=(seg+1)+s,d=c+1;i.push(a,c,b,b,c,d)}return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(i)}}
function compile(gl,type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh)||"shader");return sh}
function makeProgram(gl){const vs=compile(gl,gl.VERTEX_SHADER,`#version 300 es\nlayout(location=0) in vec3 aPos;layout(location=1) in vec3 aNormal;layout(location=2) in vec4 i0;layout(location=3) in vec4 i1;layout(location=4) in vec4 i2;layout(location=5) in vec4 i3;layout(location=6) in vec4 iColor;uniform mat4 uP,uV;out vec3 vN;out vec3 vW;out vec4 vC;void main(){mat4 M=mat4(i0,i1,i2,i3);vec4 w=M*vec4(aPos,1.);vW=w.xyz;vN=normalize(mat3(M)*aNormal);vC=iColor;gl_Position=uP*uV*w;}`),fs=compile(gl,gl.FRAGMENT_SHADER,`#version 300 es\nprecision highp float;in vec3 vN;in vec3 vW;in vec4 vC;uniform vec3 uLight;out vec4 outColor;void main(){vec3 N=normalize(vN),L=normalize(uLight);float d=max(.12,dot(N,L)),rim=pow(1.-max(0.,dot(N,normalize(vec3(0.,18.,30.)-vW))),2.2);vec3 c=vC.rgb*(.42+d*.72)+rim*.09;float fog=clamp((length(vW.xz)-54.)/95.,0.,.38);c=mix(c,vec3(.015,.028,.04),fog);outColor=vec4(c,vC.a);}`);const pr=gl.createProgram();gl.attachShader(pr,vs);gl.attachShader(pr,fs);gl.linkProgram(pr);if(!gl.getProgramParameter(pr,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(pr)||"link");return pr}
function gpuMesh(gl,m){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);const inter=new Float32Array((m.p.length/3)*6);for(let a=0,b=0;a<m.p.length;a+=3,b+=6){inter[b]=m.p[a];inter[b+1]=m.p[a+1];inter[b+2]=m.p[a+2];inter[b+3]=m.n[a];inter[b+4]=m.n[a+1];inter[b+5]=m.n[a+2]}gl.bufferData(gl.ARRAY_BUFFER,inter,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,m.i,gl.STATIC_DRAW);const inst=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,inst);gl.bufferData(gl.ARRAY_BUFFER,21*4*512,gl.DYNAMIC_DRAW);const stride=21*4;for(let c=0;c<4;c++){const loc=2+c;gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,4,gl.FLOAT,false,stride,c*16);gl.vertexAttribDivisor(loc,1)}gl.enableVertexAttribArray(6);gl.vertexAttribPointer(6,4,gl.FLOAT,false,stride,64);gl.vertexAttribDivisor(6,1);gl.bindVertexArray(null);return{vao,inst,count:m.i.length,cpu:new Float32Array(21*512)}}
function makeScene(c){const gl=c.getContext("webgl2",{alpha:false,antialias:false,powerPreference:"high-performance",desynchronized:true});if(!gl)throw new Error("WebGL2 kullanılamıyor");const dbg=gl.getExtension("WEBGL_debug_renderer_info"),renderer=String(dbg?gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)||""),software=/swiftshader|llvmpipe|software/i.test(renderer),pr=makeProgram(gl);gl.useProgram(pr);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.disable(gl.BLEND);stats.webgl2=true;stats.renderer=renderer;stats.software=software;return{gl,pr,cube:gpuMesh(gl,cubeMesh()),sphere:gpuMesh(gl,sphereMesh(software?5:7,software?7:10)),cyl:gpuMesh(gl,cylinderMesh(software?6:8)),uP:gl.getUniformLocation(pr,"uP"),uV:gl.getUniformLocation(pr,"uV"),uLight:gl.getUniformLocation(pr,"uLight"),software}}
function add(arr,m,c){arr.push({m,c})}
function uploadDraw(s,mesh,items){if(!items.length)return;const gl=s.gl,need=items.length*21;if(mesh.cpu.length<need)mesh.cpu=new Float32Array(Math.max(need,mesh.cpu.length*2));const data=mesh.cpu;let o=0;for(const it of items){data.set(it.m,o);o+=16;data[o++]=it.c[0];data[o++]=it.c[1];data[o++]=it.c[2];data[o++]=it.c[3]??1;data[o++]=0}gl.bindVertexArray(mesh.vao);gl.bindBuffer(gl.ARRAY_BUFFER,mesh.inst);gl.bufferSubData(gl.ARRAY_BUFFER,0,data.subarray(0,need));gl.drawElementsInstanced(gl.TRIANGLES,mesh.count,gl.UNSIGNED_SHORT,0,items.length);stats.drawCalls++;stats.instances+=items.length}
function hex(c){c=String(c||"#2ea8ff").replace("#","");if(c.length===3)c=c.split("").map(x=>x+x).join("");const n=parseInt(c,16)||0x2ea8ff;return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255,1]}
function hash(s){let h=2166136261;for(const ch of String(s||"x")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
const SKINS=[[.82,.61,.46,1],[.70,.47,.32,1],[.56,.35,.24,1],[.89,.70,.55,1],[.43,.27,.19,1]],HAIR=[[.035,.03,.027,1],[.11,.066,.038,1],[.18,.11,.055,1],[.025,.022,.022,1]];
function palette(id){const h=hash(id);return{skin:SKINS[h%SKINS.length],hair:HAIR[(h>>>4)%HAIR.length]}}
function source(){const on=document.getElementById("v7OnlineCanvas");if(on){const n=window.QF_V7_ONLINE_TEST?.net?.();if(n?.match?.running&&n.match.v9)return{canvas:on,v:n.match.v9,match:n.match,home:n.hostClub,away:n.guestClub}}const solo=document.getElementById("v7MatchCanvas");if(solo){const m=window.QF_V7_TEST?.match?.();if(m?.running&&m.v9)return{canvas:solo,v:m.v9,match:m,home:window.QF_V7_CORE?.clubSnapshot?.(),away:m.opponent}}return null}
function advance(v,dt){if(!v?.visual)return;dt=Math.min(.034,Math.max(.001,dt||.016));for(const p of[...(v.visual.home||[]),...(v.visual.away||[])]){const stamina=clamp((p.stamina||100)/100,.55,1),a=1-Math.exp(-dt*(3.9*stamina));p.x+=(p.tx-p.x)*a;p.y+=(p.ty-p.y)*a}const b=v.visual.ball;if(b){const a=1-Math.exp(-dt*7.2);b.x+=(b.tx-b.x)*a;b.y+=(b.ty-b.y)*a}const f=v.visual.focus;if(f){const a=1-Math.exp(-dt*3.2);f.x+=(f.targetX-f.x)*a;f.y+=(f.targetY-f.y)*a}}
function installBypass(){if(bypassInstalled||!window.QF_MATCH_V9)return;const a=window.QF_MATCH_V9;oldSolo=a.drawSolo?.bind(a);oldOnline=a.drawOnline?.bind(a);if(oldSolo)a.drawSolo=(c,m,club,ctx={})=>{if(stats.active&&c===sourceCanvas){const v=a.ensure(m,{...ctx,club,xi:club?.xi||[],playerMeta:ctx.playerMeta||window.QF_V7?.playerMeta});return true}return oldSolo(c,m,club,ctx)};if(oldOnline)a.drawOnline=(c,m,h,aw)=>{if(stats.active&&c===sourceCanvas){const v=a.ensure(m,{homeClub:h,awayClub:aw,xi:h?.xi||[],playerMeta:window.QF_V7?.playerMeta||{}});return true}return oldOnline(c,m,h,aw)};bypassInstalled=true}
function attach(src){if(sourceCanvas===src.canvas&&canvas?.isConnected&&scene)return;detach();sourceCanvas=src.canvas;const p=sourceCanvas.parentElement;if(!p)return;p.style.position="relative";canvas=document.createElement("canvas");canvas.id="v13MatchCanvas3D";canvas.className="v13-gl-canvas";canvas.setAttribute("aria-label","3D canlı futbol maçı");p.appendChild(canvas);try{scene=makeScene(canvas);sourceCanvas.style.visibility="hidden";sourceCanvas.style.opacity="0";canvas.style.visibility="visible";canvas.style.opacity="1";stats.active=true;stats.fallback=false;ensureHud()}catch(e){stats.active=false;stats.fallback=true;sourceCanvas.style.visibility="visible";canvas.remove();canvas=null;scene=null;ensureFallback(String(e?.message||e))}}
function detach(){stats.active=false;if(sourceCanvas){sourceCanvas.style.visibility="visible";sourceCanvas.style.opacity="1"}canvas?.remove();document.getElementById("v13BroadcastHud")?.remove();document.getElementById("v13Fallback")?.remove();scene=null;canvas=null;sourceCanvas=null;sizeCache=null;camState=null}
function ensureHud(){if(document.getElementById("v13BroadcastHud")||!sourceCanvas)return;const e=document.createElement("div");e.id="v13BroadcastHud";e.className="v13-broadcast-hud";e.innerHTML=`<b>3D CANLI</b><span id="v13Perf">60 FPS • YÜKSEK</span>`;sourceCanvas.parentElement?.appendChild(e)}
function ensureFallback(msg){if(document.getElementById("v13Fallback")||!sourceCanvas)return;const e=document.createElement("div");e.id="v13Fallback";e.className="v13-fallback";e.textContent=`3D kullanılamadı • ${msg}`;sourceCanvas.parentElement?.appendChild(e)}
function resize(force=false){if(!force&&sizeCache&&canvas?.isConnected&&sourceCanvas?.isConnected)return sizeCache;if(!canvas||!sourceCanvas||!scene)return null;const r=sourceCanvas.getBoundingClientRect(),pr=sourceCanvas.parentElement?.getBoundingClientRect();if(!pr||r.width<10||r.height<10)return null;canvas.style.left=`${r.left-pr.left}px`;canvas.style.top=`${r.top-pr.top}px`;canvas.style.width=`${r.width}px`;canvas.style.height=`${r.height}px`;const base=level===2?1.0:level===1?.82:.64,dpr=Math.min(devicePixelRatio||1,base),w=Math.max(480,Math.round(r.width*dpr)),h=Math.max(270,Math.round(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}sizeCache={w,h,cssW:r.width,cssH:r.height};return sizeCache}
function norm(p){return{x:(p.x-.5)*96,z:(p.y-.5)*60}}
function sceneInstances(src,t){const C=[],S=[],Y=[],q=level;const grassA=[.045,.28,.15,1],grassB=[.052,.34,.18,1],white=[1,1,.98,1],stand=[.045,.06,.075,1],stand2=[.08,.11,.14,1];add(C,trs(0,-.20,0,53,.18,34),grassA);const stripes=q===0?5:q===1?7:9;for(let i=0;i<stripes;i++){const w=53/stripes,x=-53+w+i*w*2;add(C,trs(x,-.01,0,w,.012,33.6),i%2?grassB:grassA)}const line=(x,z,sx,sz)=>add(C,trs(x,.058,z,Math.max(sx,.075),.027,Math.max(sz,.075)),white);line(0,-33.6,52.7,.045);line(0,33.6,52.7,.045);line(-52.7,0,.045,33.6);line(52.7,0,.045,33.6);line(0,0,.035,33.5);line(-43,0,.08,20);line(43,0,.08,20);
for(const side of[-1,1]){const px=side*47.85;line(px,-20,4.85,.08);line(px,20,4.85,.08);line(side*48.5,0,.08,9);const sx=side*50.6;line(sx,-9,2.1,.08);line(sx,9,2.1,.08);add(S,trs(side*42,.09,0,.13,.035,.13),white)}
add(S,trs(0,.09,0,.13,.035,.13),white);const seg=q===0?8:q===1?12:18;for(let j=0;j<seg;j++){const a=j/seg*Math.PI*2;line(Math.cos(a)*9.15,Math.sin(a)*9.15,9.15*Math.PI/seg*.52,.035)}for(const side of[-1,1]){const gx=side*53.2;add(C,trs(gx,1.25,-3.66,.07,1.25,.07),white);add(C,trs(gx,1.25,3.66,.07,1.25,.07),white);add(C,trs(gx,2.48,0,.07,.07,3.66),white)}const levels=q===0?1:q===1?2:2;for(const z of[-40,40])for(let l=0;l<levels;l++)add(C,trs(0,1.6+l*2.7,z+(z<0?-l*2.3:l*2.3),59-l*3.4,1.5,3.2),l%2?stand2:stand);for(const x of[-61,61])for(let l=0;l<levels;l++)add(C,trs(x+(x<0?-l*2.3:l*2.3),1.6+l*2.7,0,3.2,1.5,39-l*2.7),l%2?stand2:stand);if(q>0){for(const [x,z] of[[-57,-37],[-57,37],[57,-37],[57,37]]){add(C,trs(x,10,z,.12,10,.12),[.22,.24,.27,1]);add(C,trs(x,20,z,2.2,.25,.7),[.95,.94,.75,1])}}
 const hc=hex(src.home?.color||src.home?.colors?.primary||"#2ea8ff"),ac=hex(src.away?.color||src.away?.colors?.primary||"#e2bd55"),ball=norm(src.v.visual.ball||{x:.5,y:.5});let idx=0;for(const [team,color] of[[src.v.visual.home||[],hc],[src.v.visual.away||[],ac]])for(const p of team){const pos=norm(p),yaw=Math.atan2(ball.x-pos.x,ball.z-pos.z),speed=Math.hypot((p.tx??p.x)-p.x,(p.ty??p.y)-p.y),run=Math.sin(t*.0088+idx*1.37)*clamp(.12+speed*4,.12,.38),pal=palette(p.id||idx),keeper=idx%11===0,shirt=keeper?[.12,.63,.34,1]:color,short=[Math.max(.025,shirt[0]*.42),Math.max(.025,shirt[1]*.42),Math.max(.025,shirt[2]*.42),1],sock=[.92,.93,.94,1],boot=[.025,.028,.032,1];add(Y,trs(pos.x,1.82,pos.z,.50,.70,.31,yaw),shirt);add(Y,trs(pos.x,1.03,pos.z,.41,.32,.27,yaw),short);add(S,trs(pos.x-.43,2.16,pos.z,.20,.22,.22,yaw),shirt);add(S,trs(pos.x+.43,2.16,pos.z,.20,.22,.22,yaw),shirt);add(Y,trs(pos.x,2.45,pos.z,.15,.12,.15,yaw),pal.skin);add(S,trs(pos.x,2.86,pos.z,.35,.40,.35,yaw),pal.skin);if(q>0)add(S,trs(pos.x,3.08,pos.z-.015,.355,.17,.355,yaw),pal.hair);add(Y,trs(pos.x-.22,.43+run*.08,pos.z,.14,.29,.14,yaw,run),sock);add(Y,trs(pos.x+.22,.43-run*.08,pos.z,.14,.29,.14,yaw,-run),sock);add(Y,trs(pos.x-.22,.92+run*.10,pos.z,.17,.28,.17,yaw,run*.8),short);add(Y,trs(pos.x+.22,.92-run*.10,pos.z,.17,.28,.17,yaw,-run*.8),short);add(Y,trs(pos.x-.54,1.78,pos.z,.115,.43,.115,yaw,-run*.72),pal.skin);add(Y,trs(pos.x+.54,1.78,pos.z,.115,.43,.115,yaw,run*.72),pal.skin);if(q>0){add(C,trs(pos.x-.22,.14+run*.08,pos.z-.05,.17,.08,.32,yaw),boot);add(C,trs(pos.x+.22,.14-run*.08,pos.z-.05,.17,.08,.32,yaw),boot)}idx++}
 add(S,trs(ball.x,.48,ball.z,.32,.32,.32,t*.003),[.97,.97,.94,1]);stats.players=idx;return{C,S,Y}}
function camera(src){const f=src.v.visual.focus||{x:.5,y:.5},fx=(f.x-.5)*78,fz=(f.y-.5)*46,m=lastMoment;const hot=m&&performance.now()-m.at<1600&&(m.type==="goal"||m.phase==="finish"||m.type==="save"||m.type==="post");if(hot){const side=m.side==="away"?-1:1;return{eye:[fx-side*12,17,28],target:[fx*.88,1.4,fz*.82]}}return{eye:[fx-10,25,39],target:[fx*.78,1.15,fz*.60]}}
const V14_LIGHT=new Float32Array([-.25,.88,.38]);
function render(src,t,dt){matrixPoolIndex=0;advance(src.v,dt);const sz=resize();if(!sz||!scene)return;const s=scene,g=s.gl,start=performance.now();g.viewport(0,0,sz.w,sz.h);g.clearColor(.008,.017,.026,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(s.pr);g.uniformMatrix4fv(s.uP,false,perspective(Math.PI/5.05,sz.w/sz.h,.1,220));const cam=camera(src);g.uniformMatrix4fv(s.uV,false,lookAt(cam.eye,cam.target));g.uniform3fv(s.uLight,V14_LIGHT);stats.drawCalls=0;stats.instances=0;const inst=sceneInstances(src,t);uploadDraw(s,s.cube,inst.C);uploadDraw(s,s.sphere,inst.S);uploadDraw(s,s.cyl,inst.Y);stats.renderMs=+(performance.now()-start).toFixed(2);stats.frames++;stats.level=level;stats.targetFps=60;if(t-lastHudUpdate>500){lastHudUpdate=t;const hud=document.getElementById("v13Perf"),text=`${Math.round(stats.avgFps)} FPS • ${level===2?"YÜKSEK":level===1?"DENGELİ":"PERFORMANS"}`;if(hud&&text!==lastHudText){hud.textContent=text;lastHudText=text}}}
function adapt(interval){avgIntervals.push(interval);if(avgIntervals.length>72)avgIntervals.shift();if(avgIntervals.length<32)return;const avg=avgIntervals.reduce((a,b)=>a+b,0)/avgIntervals.length,fps=1000/avg;stats.avgFps=fps;const now=performance.now();if(now-lastQualityChange<2200)return;if(cfg.quality!=="auto"){level=cfg.quality==="high"?2:cfg.quality==="medium"?1:0;return}if(level===2&&fps<50){level=1;lastQualityChange=now;avgIntervals=[]}else if(level===1&&fps<36){level=0;lastQualityChange=now;avgIntervals=[]}else if(level===0&&fps>43){level=1;lastQualityChange=now;avgIntervals=[]}else if(level===1&&fps>57){level=2;lastQualityChange=now;avgIntervals=[]}}
function loop(t){const interval=Math.max(1,Math.min(50,t-last));last=t;installBypass();const src=source();if(!cfg.enabled||!src){if(scene||canvas)detach();raf=requestAnimationFrame(loop);return}attach(src);if(!scene){raf=requestAnimationFrame(loop);return}adapt(interval);lastRender=t;render(src,t,interval/1000);raf=requestAnimationFrame(loop)}
window.addEventListener("qf:v11-commentary",e=>{const d=e.detail||{};lastMoment={...d,at:performance.now()}});
window.addEventListener("resize",()=>{sizeCache=null;if(canvas&&sourceCanvas)resize(true)});
window.addEventListener("beforeunload",()=>cancelAnimationFrame(raf));
function boot(){try{window.QF_MATCH_3D_V10?.setSetting?.("enabled",false);window.QF_MATCH_3D_V11?.setSetting?.("enabled",false)}catch{}installBypass();raf=requestAnimationFrame(loop)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
window.QF_MATCH_3D_V13={getSettings:()=>({...cfg}),setSetting:(k,v)=>{if(k in cfg){cfg[k]=v;save();return true}return false},state:()=>({...stats,canvas:canvas?.id||"",source:sourceCanvas?.id||""}),forceQuality:q=>{level=q==="high"?2:q==="medium"?1:0;lastQualityChange=performance.now();return level},detach};
})();

/* V14_FRAME_PACING: every RAF renders; quality only changes resolution/detail, never animation cadence. */

/* V15_BROADCAST_REALISM: slower delta-time player springs, camera easing and high-contrast complete pitch markings. */
