(()=>{"use strict";
const KEY="qf-v11-graphics",defaults={enabled:true,quality:"auto",camera:"broadcast",replays:true},clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let cfg=load(),scene=null,raf=0,last=performance.now(),activeCanvas=null,sourceCanvas=null,snapshots=[],lastSnap=0,replay=null,lastMoment=null,ballSmooth=null,disabledV10=false;
const stats={frames:0,drawCalls:0,lastFrameMs:0,avgFrameMs:0,quality:"",webgl2:false,replays:0,software:false,renderer:"",playersHigh:0};let frameCosts=[];
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{...defaults}}}function save(){localStorage.setItem(KEY,JSON.stringify(cfg))}
function mat4(){return new Float32Array(16)}
function perspective(fovy,aspect,near,far,o=mat4()){const f=1/Math.tan(fovy/2),nf=1/(near-far);o[0]=f/aspect;o[5]=f;o[10]=(far+near)*nf;o[11]=-1;o[14]=2*far*near*nf;return o}
function lookAt(eye,target,up=[0,1,0],o=mat4()){let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx;l=Math.hypot(xx,xy,xz)||1;xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;o[0]=xx;o[1]=yx;o[2]=zx;o[4]=xy;o[5]=yy;o[6]=zy;o[8]=xz;o[9]=yz;o[10]=zz;o[12]=-(xx*eye[0]+xy*eye[1]+xz*eye[2]);o[13]=-(yx*eye[0]+yy*eye[1]+yz*eye[2]);o[14]=-(zx*eye[0]+zy*eye[1]+zz*eye[2]);o[15]=1;return o}
function trs(x,y,z,sx=1,sy=1,sz=1,ry=0,rx=0,o=mat4()){const cy=Math.cos(ry),syy=Math.sin(ry),cx=Math.cos(rx),sxx=Math.sin(rx);o[0]=cy*sx;o[1]=syy*sxx*sx;o[2]=-syy*cx*sx;o[4]=0;o[5]=cx*sy;o[6]=sxx*sy;o[8]=syy*sz;o[9]=-cy*sxx*sz;o[10]=cy*cx*sz;o[12]=x;o[13]=y;o[14]=z;o[15]=1;return o}
function meshCube(){const p=[],n=[],i=[];const faces=[[[0,0,-1],[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1]],[[0,0,1],[-1,-1,1],[-1,1,1],[1,1,1],[1,-1,1]],[[-1,0,0],[-1,-1,-1],[-1,1,-1],[-1,1,1],[-1,-1,1]],[[1,0,0],[1,-1,-1],[1,-1,1],[1,1,1],[1,1,-1]],[[0,1,0],[-1,1,-1],[1,1,-1],[1,1,1],[-1,1,1]],[[0,-1,0],[-1,-1,-1],[-1,-1,1],[1,-1,1],[1,-1,-1]]];faces.forEach((f,k)=>{const base=p.length/3;for(let j=1;j<5;j++){p.push(...f[j]);n.push(...f[0])}i.push(base,base+1,base+2,base,base+2,base+3)});return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(i)}}
function meshSphere(lat=8,lon=12){const p=[],n=[],i=[];for(let y=0;y<=lat;y++){const v=y/lat,ph=v*Math.PI;for(let x=0;x<=lon;x++){const u=x/lon,th=u*Math.PI*2,nx=Math.sin(ph)*Math.cos(th),ny=Math.cos(ph),nz=Math.sin(ph)*Math.sin(th);p.push(nx,ny,nz);n.push(nx,ny,nz)}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){const a=y*(lon+1)+x,b=a+lon+1;i.push(a,b,a+1,b,b+1,a+1)}return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(i)}}
function meshCylinder(seg=10){const p=[],n=[],i=[];for(let y=0;y<=1;y++){const yy=y?1:-1;for(let s=0;s<=seg;s++){const a=s/seg*Math.PI*2,x=Math.cos(a),z=Math.sin(a);p.push(x,yy,z);n.push(x,0,z)}}for(let s=0;s<seg;s++){const a=s,b=s+1,c=(seg+1)+s,d=c+1;i.push(a,c,b,b,c,d)}for(const yy of[-1,1]){const center=p.length/3;p.push(0,yy,0);n.push(0,yy,0);const start=p.length/3;for(let s=0;s<=seg;s++){const a=s/seg*Math.PI*2;p.push(Math.cos(a),yy,Math.sin(a));n.push(0,yy,0)}for(let s=0;s<seg;s++){if(yy>0)i.push(center,start+s,start+s+1);else i.push(center,start+s+1,start+s)}}return{p:new Float32Array(p),n:new Float32Array(n),i:new Uint16Array(i)}}
function compile(gl,type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh)||"shader");return sh}
function program(gl){const vs=compile(gl,gl.VERTEX_SHADER,`#version 300 es\nlayout(location=0) in vec3 aPos;layout(location=1) in vec3 aNormal;uniform mat4 uP,uV,uM;out vec3 vN;out vec3 vW;void main(){vec4 w=uM*vec4(aPos,1.);vW=w.xyz;vN=normalize(mat3(uM)*aNormal);gl_Position=uP*uV*w;}`),fs=compile(gl,gl.FRAGMENT_SHADER,`#version 300 es\nprecision highp float;in vec3 vN;in vec3 vW;uniform vec4 uC;uniform vec3 uLight;uniform float uGloss;out vec4 outColor;void main(){vec3 N=normalize(vN),L=normalize(uLight),V=normalize(vec3(0.,14.,28.)-vW);float diff=max(.0,dot(N,L)),rim=pow(1.-max(.0,dot(N,V)),2.4),spec=pow(max(.0,dot(reflect(-L,N),V)),22.)*uGloss;float fog=clamp((length(vW.xz)-48.)/95.,0.,.46);vec3 c=uC.rgb*(.40+.68*diff)+rim*vec3(.09,.13,.16)+spec*vec3(.42);c=mix(c,vec3(.018,.035,.048),fog);outColor=vec4(c,uC.a);}`);const pr=gl.createProgram();gl.attachShader(pr,vs);gl.attachShader(pr,fs);gl.linkProgram(pr);if(!gl.getProgramParameter(pr,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(pr)||"link");return pr}
function bufferMesh(gl,m){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);const inter=new Float32Array((m.p.length/3)*6);for(let k=0,j=0;k<m.p.length;k+=3,j+=6){inter[j]=m.p[k];inter[j+1]=m.p[k+1];inter[j+2]=m.p[k+2];inter[j+3]=m.n[k];inter[j+4]=m.n[k+1];inter[j+5]=m.n[k+2]}gl.bufferData(gl.ARRAY_BUFFER,inter,gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,m.i,gl.STATIC_DRAW);gl.bindVertexArray(null);return{vao,count:m.i.length}}
function makeScene(canvas){const gl=canvas.getContext("webgl2",{alpha:false,antialias:true,powerPreference:"high-performance"});if(!gl)throw new Error("WebGL2 yok");const dbg=gl.getExtension("WEBGL_debug_renderer_info"),renderer=String(dbg?gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)||""),software=/swiftshader|llvmpipe|software/i.test(renderer),pr=program(gl);gl.useProgram(pr);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);stats.webgl2=true;stats.software=software;stats.renderer=renderer;return{gl,pr,cube:bufferMesh(gl,meshCube()),sphere:bufferMesh(gl,meshSphere(software?5:8,software?7:12)),cyl:bufferMesh(gl,meshCylinder(software?6:10)),uP:gl.getUniformLocation(pr,"uP"),uV:gl.getUniformLocation(pr,"uV"),uM:gl.getUniformLocation(pr,"uM"),uC:gl.getUniformLocation(pr,"uC"),uLight:gl.getUniformLocation(pr,"uLight"),uGloss:gl.getUniformLocation(pr,"uGloss"),p:mat4(),v:mat4(),software,renderer}}
function draw(s,mesh,m,color,gloss=.06){const g=s.gl;g.uniformMatrix4fv(s.uM,false,m);g.uniform4fv(s.uC,color);g.uniform1f(s.uGloss,gloss);g.bindVertexArray(mesh.vao);g.drawElements(g.TRIANGLES,mesh.count,g.UNSIGNED_SHORT,0);stats.drawCalls++}
function hex(c){c=String(c||"#2ea8ff").replace("#","");if(c.length===3)c=c.split("").map(x=>x+x).join("");const n=parseInt(c,16)||0x2ea8ff;return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255,1]}
function hash(s){let h=2166136261;for(const ch of String(s||"x")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
const SKINS=[[.82,.61,.46,1],[.69,.45,.31,1],[.56,.35,.24,1],[.89,.70,.55,1],[.43,.27,.19,1]],HAIRS=[[.055,.043,.036,1],[.12,.075,.045,1],[.025,.022,.022,1],[.22,.14,.07,1]];
function palette(id){const h=hash(id);return{skin:SKINS[h%SKINS.length],hair:HAIRS[(h>>4)%HAIRS.length]}}
function quality(){if(cfg.quality!=="auto")return cfg.quality;if(scene?.software||document.body.classList.contains("performance-lite"))return"low";return(navigator.hardwareConcurrency||4)>=8&&devicePixelRatio<=2?"high":"medium"}
function source(){const online=document.getElementById("v7OnlineCanvas");if(online){const n=window.QF_V7_ONLINE_TEST?.net?.();if(n?.match?.running&&n.match.v9)return{canvas:online,match:n.match,v:n.match.v9,home:n.hostClub,away:n.guestClub,online:true}}const solo=document.getElementById("v7MatchCanvas");if(solo){const m=window.QF_V7_TEST?.match?.();if(m?.running&&m.v9)return{canvas:solo,match:m,v:m.v9,home:window.QF_V7_CORE?.clubSnapshot?.(),away:m.opponent,online:false}}return null}
function smoothPlayer(p,dt){if(p._v11x==null){p._v11x=p.x;p._v11y=p.y;p._v11px=p.x;p._v11py=p.y}const k=1-Math.pow(.0018,Math.min(.04,dt));p._v11px=p._v11x;p._v11py=p._v11y;p._v11x+=(p.x-p._v11x)*k*.36;p._v11y+=(p.y-p._v11y)*k*.36;return{x:p._v11x,y:p._v11y,dx:(p._v11x-p._v11px)/Math.max(.008,dt),dy:(p._v11y-p._v11py)/Math.max(.008,dt)}}
function norm(p){return{x:(p.x-.5)*96,z:(p.y-.5)*60}}
function lineBox(s,x,z,sx,sz,c=[.92,.96,.94,1]){draw(s,s.cube,trs(x,.035,z,sx,.018,sz),c,.02)}
function field(s){const q=quality(),low=q==="low",stripes=low?5:q==="medium"?8:11;draw(s,s.cube,trs(0,-.18,0,53,.18,34),[.038,.25,.135,1],.01);for(let i=0;i<stripes;i++){const width=53/stripes,x=-53+width+i*width*2;draw(s,s.cube,trs(x,-.012,0,width,.012,33.5),i%2?[.052,.34,.18,1]:[.043,.30,.16,1],.01)}const w=[.94,.97,.94,1];lineBox(s,0,-33.6,52.6,.045,w);lineBox(s,0,33.6,52.6,.045,w);lineBox(s,-52.6,0,.045,33.6,w);lineBox(s,52.6,0,.045,33.6,w);lineBox(s,0,0,.035,33.5,w);lineBox(s,-43,0,.035,20,w);lineBox(s,43,0,.035,20,w);if(!low){lineBox(s,-48.5,0,.035,9,w);lineBox(s,48.5,0,.035,9,w)}const seg=low?7:q==="medium"?12:20;for(let j=0;j<seg;j++){const a=j/seg*Math.PI*2;lineBox(s,Math.cos(a)*9.15,Math.sin(a)*9.15,9.15*Math.PI/seg*.52,.035,w)}for(const side of[-1,1]){const gx=side*53.2;draw(s,s.cube,trs(gx,1.25,-3.66,.07,1.25,.07),w,.14);draw(s,s.cube,trs(gx,1.25,3.66,.07,1.25,.07),w,.14);draw(s,s.cube,trs(gx,2.48,0,.07,.07,3.66),w,.14);if(!low)draw(s,s.cube,trs(gx+side*1.5,.25,0,1.5,.03,3.66),[.74,.79,.79,.28],.02)}}
function stadium(s,t){const q=quality(),levels=q==="low"?1:q==="medium"?2:3,dark=[.042,.055,.068,1],seat=[.072,.105,.135,1];for(const z of[-40,40])for(let l=0;l<levels;l++)draw(s,s.cube,trs(0,1.5+l*2.6,z+(z<0?-l*2.2:l*2.2),58-l*3,1.4,3.2),l%2?seat:dark,.02);for(const x of[-61,61])for(let l=0;l<levels;l++)draw(s,s.cube,trs(x+(x<0?-l*2.2:l*2.2),1.5+l*2.6,0,3.2,1.4,39-l*2.5),l%2?seat:dark,.02);if(q!=="low")for(const [x,z] of[[-57,-37],[-57,37],[57,-37],[57,37]]){draw(s,s.cube,trs(x,10,z,.12,10,.12),[.22,.24,.27,1],.08);draw(s,s.cube,trs(x,20,z,2.2,.25,.7),[.96,.95,.78,1],.4)}if(q==="high"&&!s.software){for(let k=0;k<36;k++){const side=k%4,band=Math.floor(k/4),a=(band%9)/9;let x=0,z=0;if(side<2){x=-52+a*104;z=side?-41:41}else{x=side===2?-62:62;z=-34+a*68}const pulse=.52+.28*Math.sin(t*.0018+k);draw(s,s.sphere,trs(x,3.6+(k%3)*.68,z,.12,.12,.12),[.18+.35*pulse,.23,.28,1],.03)}}}
function player(s,p,color,ball,t,i,keeper,dt){const sm=smoothPlayer(p,dt),q=norm(sm),b=ballSmooth||norm(ball),yaw=Math.atan2(b.x-q.x,b.z-q.z),speed=clamp(Math.hypot(sm.dx,sm.dy)*.018,0,1),run=Math.sin(t*.0105+i*1.41)*(.12+.34*speed),lean=clamp(sm.dx*.0018,-.12,.12),pal=palette(p.id||i),shirt=keeper?[.12,.60,.34,1]:color,short=[Math.max(.03,shirt[0]*.42),Math.max(.03,shirt[1]*.42),Math.max(.03,shirt[2]*.42),1],sock=[.91,.93,.94,1],boot=[.025,.03,.035,1],qual=quality();
 draw(s,s.cube,trs(q.x,.12,q.z,.42,.05,.27,yaw),[0,0,0,.22],.01);
 if(qual==="low"){draw(s,s.cube,trs(q.x,1.48,q.z,.39,1.12,.25,yaw,lean),shirt,.04);draw(s,s.sphere,trs(q.x,2.76,q.z,.28,.32,.28,yaw),pal.skin,.06);return}
 draw(s,s.cube,trs(q.x,1.72,q.z,.46,.66,.25,yaw,lean),shirt,.07);draw(s,s.cube,trs(q.x,.98,q.z,.40,.38,.24,yaw),short,.04);draw(s,s.sphere,trs(q.x,2.66,q.z,.30,.36,.30,yaw),pal.skin,.09);draw(s,s.sphere,trs(q.x,2.87,q.z-.015,.305,.16,.305,yaw),pal.hair,.03);
 const legX=.21,legY=.57,legLen=.48,armX=.53,armY=1.75,armLen=.44;
 draw(s,s.cyl,trs(q.x-legX,legY+run*.22,q.z,.135,legLen,.135,yaw,run),sock,.035);draw(s,s.cyl,trs(q.x+legX,legY-run*.22,q.z,.135,legLen,.135,yaw,-run),sock,.035);
 draw(s,s.cube,trs(q.x-legX,.12+run*.13,q.z-.08,.18,.09,.32,yaw,run*.15),boot,.1);draw(s,s.cube,trs(q.x+legX,.12-run*.13,q.z-.08,.18,.09,.32,yaw,-run*.15),boot,.1);
 if(qual==="medium")return;
 stats.playersHigh++;draw(s,s.cyl,trs(q.x-armX,armY-run*.12,q.z,.105,armLen,.105,yaw,-run*.92),pal.skin,.03);draw(s,s.cyl,trs(q.x+armX,armY+run*.12,q.z,.105,armLen,.105,yaw,run*.92),pal.skin,.03);draw(s,s.sphere,trs(q.x-armX,1.20-run*.22,q.z,.12,.13,.12),pal.skin,.03);draw(s,s.sphere,trs(q.x+armX,1.20+run*.22,q.z,.12,.13,.12),pal.skin,.03);draw(s,s.cyl,trs(q.x,2.28,q.z,.14,.17,.14,yaw),pal.skin,.03)
}
function dataView(src,dt){let home=src.v.visual.home,away=src.v.visual.away,ball=src.v.visual.ball,focus=src.v.visual.focus,isReplay=false;if(replay&&performance.now()<replay.until&&replay.list.length){const pr=clamp((performance.now()-replay.start)/(replay.until-replay.start),0,1),idx=Math.min(replay.list.length-1,Math.floor(pr*replay.list.length)),r=replay.list[idx];home=r.home.map((a,i)=>({...src.v.visual.home[i],x:a[0],y:a[1],_v11x:a[0],_v11y:a[1]}));away=r.away.map((a,i)=>({...src.v.visual.away[i],x:a[0],y:a[1],_v11x:a[0],_v11y:a[1]}));ball={x:r.ball[0],y:r.ball[1]};focus={x:r.focus[0],y:r.focus[1]};isReplay=true}else if(replay&&performance.now()>=replay.until)replay=null;const raw=norm(ball);if(!ballSmooth)ballSmooth={x:raw.x,z:raw.z};const bk=1-Math.pow(.001,Math.min(.04,dt));ballSmooth.x+=(raw.x-ballSmooth.x)*bk*.48;ballSmooth.z+=(raw.z-ballSmooth.z)*bk*.48;return{home,away,ball,focus,replay:isReplay}}
function cameraFor(d){const f=d.focus||{x:.5,y:.5},fx=(f.x-.5)*70,fz=(f.y-.5)*42,phase=lastMoment?.phase||"",side=lastMoment?.side==="away"?-1:1;let eye,target;if(cfg.camera==="tactical"){eye=[0,79,.01];target=[0,0,0]}else if(cfg.camera==="goal"){eye=[side*50,11,1.5];target=[side*32,0,0]}else{const cinematic=["finish","result"].includes(phase)||d.replay,boost=cinematic?1:0;eye=[fx-13-side*boost*3,33-boost*7,51-boost*14];target=[fx*.70+side*boost*7,0,fz*.42]}return{eye,target}}
function snapshot(src){return{home:src.v.visual.home.map(p=>[p._v11x??p.x,p._v11y??p.y]),away:src.v.visual.away.map(p=>[p._v11x??p.x,p._v11y??p.y]),ball:[src.v.visual.ball.x,src.v.visual.ball.y],focus:[src.v.visual.focus.x,src.v.visual.focus.y]}}
function render(src,t,dt){const c=activeCanvas,s=scene,g=s.gl,rect=sourceCanvas.getBoundingClientRect(),q=quality(),dpr=Math.min(devicePixelRatio||1,q==="high"?1.55:q==="medium"?1.18:.9),w=Math.max(640,Math.round(rect.width*dpr)),h=Math.max(360,Math.round(rect.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h}g.viewport(0,0,w,h);g.clearColor(.008,.021,.030,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);stats.drawCalls=0;stats.playersHigh=0;perspective(Math.PI/4.35,w/h,.1,250,s.p);const d=dataView(src,dt),cam=cameraFor(d);lookAt(cam.eye,cam.target,[0,1,0],s.v);g.useProgram(s.pr);g.uniformMatrix4fv(s.uP,false,s.p);g.uniformMatrix4fv(s.uV,false,s.v);g.uniform3fv(s.uLight,new Float32Array([-.32,.88,.38]));field(s);stadium(s,t);const hc=hex(src.home?.color||src.home?.colors?.primary||"#2ea8ff"),ac=hex(src.away?.color||src.away?.colors?.primary||"#e8c66a");for(let i=0;i<d.home.length;i++)player(s,d.home[i],hc,d.ball,t,i,i===0,dt);for(let i=0;i<d.away.length;i++)player(s,d.away[i],ac,d.ball,t,i+11,i===0,dt);const b=ballSmooth||norm(d.ball);draw(s,s.cube,trs(b.x,.12,b.z,.38,.045,.30),[0,0,0,.20],.01);draw(s,s.sphere,trs(b.x,.48,b.z,.28,.28,.28,t*.003),[.96,.97,.94,1],.16);hud(q,d)}
function disableV10(){if(disabledV10)return;try{window.QF_MATCH_3D_V10?.setSetting?.("enabled",false);disabledV10=true}catch{}}
function attach(src){if(sourceCanvas===src.canvas&&activeCanvas?.isConnected)return;detach(false);disableV10();document.getElementById("v10MatchCanvas3D")?.remove();document.getElementById("v10BroadcastHud")?.remove();src.canvas.classList.remove("v10-fallback-hidden");sourceCanvas=src.canvas;const p=sourceCanvas.parentElement;p.style.position="relative";const c=document.createElement("canvas");c.id="v11MatchCanvas3D";c.className="v10-gl-canvas v11-gl-canvas";c.setAttribute("aria-label","V11 gerçekçi 3D canlı futbol yayını");p.insertBefore(c,sourceCanvas.nextSibling);activeCanvas=c;try{scene=makeScene(c);sourceCanvas.classList.add("v10-fallback-hidden");ensureHud(p)}catch(e){c.remove();activeCanvas=null;scene=null;sourceCanvas.classList.remove("v10-fallback-hidden");try{window.QF_MATCH_3D_V10?.setSetting?.("enabled",true);disabledV10=false}catch{}}}
function detach(reenable=true){if(sourceCanvas)sourceCanvas.classList.remove("v10-fallback-hidden");activeCanvas?.remove();document.getElementById("v11BroadcastHud")?.remove();sourceCanvas=null;activeCanvas=null;scene=null;ballSmooth=null;snapshots=[];replay=null;if(reenable&&disabledV10){try{window.QF_MATCH_3D_V10?.setSetting?.("enabled",true)}catch{}disabledV10=false}}
function ensureHud(p){if(document.getElementById("v11BroadcastHud"))return;const e=document.createElement("div");e.id="v11BroadcastHud";e.className="v10-broadcast-hud";e.innerHTML=`<div class="v10-live"><i></i><b>CANLI V11</b><span id="v11CamName">YAYIN</span></div><div class="v10-hud-actions"><button data-v11cam="broadcast">Yayın</button><button data-v11cam="tactical">Taktik</button><button data-v11cam="goal">Kale</button><select id="v11Quality" aria-label="V11 grafik kalitesi"><option value="auto">Otomatik</option><option value="high">Ultra oyuncu</option><option value="medium">Dengeli</option><option value="low">Performans</option></select></div><div id="v11ReplayBadge" class="v10-replay">TEKRAR</div><div id="v11MomentRibbon" class="v11-moment-ribbon"></div>`;p.appendChild(e);e.querySelectorAll("[data-v11cam]").forEach(b=>b.onclick=()=>{cfg.camera=b.dataset.v11cam;save();e.querySelectorAll("[data-v11cam]").forEach(x=>x.classList.toggle("active",x===b))});const q=e.querySelector("#v11Quality");q.value=cfg.quality;q.onchange=()=>{cfg.quality=q.value;save()};e.querySelector(`[data-v11cam="${cfg.camera}"]`)?.classList.add("active")}
function hud(q,d){const h=document.getElementById("v11BroadcastHud");if(!h)return;const cam=h.querySelector("#v11CamName");if(cam)cam.textContent=(cfg.camera==="broadcast"?"YAYIN":cfg.camera==="tactical"?"TAKTİK":"KALE")+` • ${q.toUpperCase()}`;h.querySelector("#v11ReplayBadge")?.classList.toggle("show",!!d.replay)}
window.addEventListener("qf:v11-commentary",e=>{lastMoment=e.detail||null;const r=document.getElementById("v11MomentRibbon");if(r){r.textContent=lastMoment.text||"";r.classList.add("show");setTimeout(()=>r.classList.remove("show"),1300)}});
window.addEventListener("qf:v9-event",e=>{const d=e.detail||{};if(d.type==="goal"&&cfg.replays&&snapshots.length>10){replay={list:snapshots.slice(-28),start:performance.now()+650,until:performance.now()+3600};stats.replays++}});
function tick(t){const dt=clamp((t-last)/1000,.001,.05);last=t;stats.frames++;stats.quality=quality();const src=source();if(!cfg.enabled||!src){if(scene||activeCanvas||sourceCanvas)detach(false);setTimeout(()=>{raf=requestAnimationFrame(tick)},240);return}attach(src);if(scene&&activeCanvas){if(t-lastSnap>110){snapshots.push(snapshot(src));if(snapshots.length>38)snapshots.shift();lastSnap=t}const st=performance.now();render(src,t,dt);const cost=Math.max(.01,performance.now()-st);stats.lastFrameMs=cost;frameCosts.push(cost);if(frameCosts.length>120)frameCosts.shift();stats.avgFrameMs=frameCosts.reduce((a,b)=>a+b,0)/frameCosts.length;if(cfg.quality==="auto"&&frameCosts.length>30&&stats.avgFrameMs>24&&!scene.software)document.body.classList.add("performance-lite")}raf=requestAnimationFrame(tick)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{raf=requestAnimationFrame(tick)},{once:true});else raf=requestAnimationFrame(tick);window.addEventListener("beforeunload",()=>cancelAnimationFrame(raf));
window.QF_MATCH_3D_V11={getSettings:()=>({...cfg}),setSetting:(k,v)=>{if(k in cfg){cfg[k]=v;save();return true}return false},state:()=>({...stats,active:!!scene,replay:!!replay,canvas:activeCanvas?.id||""}),forceReplay:()=>{if(snapshots.length){replay={list:snapshots.slice(),start:performance.now(),until:performance.now()+2500};stats.replays++;return true}return false}};
})();
