(()=>{"use strict";/* V10_LOD_OPT */
const KEY="qf-v10-graphics",defaults={enabled:true,quality:"auto",camera:"broadcast",replays:true},clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let cfg=load(),scene=null,raf=0,last=performance.now(),frames=[],intervals=[],snapshots=[],lastSnap=0,replay=null,lastEvent="",activeCanvas=null,sourceCanvas=null;
const stats={frames:0,drawCalls:0,lastFrameMs:0,avgFrameMs:0,avgIntervalMs:0,quality:"",webgl2:false,replays:0,fallback:""};
function load(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return{...defaults}}}function save(){localStorage.setItem(KEY,JSON.stringify(cfg))}
function hex(c){c=String(c||"#2ea8ff").replace("#","");if(c.length===3)c=c.split("").map(x=>x+x).join("");const n=parseInt(c,16)||0x2ea8ff;return[((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255,1]}
function mat4(){return new Float32Array(16)}function ident(o=mat4()){o[0]=o[5]=o[10]=o[15]=1;return o}function mul(a,b,o=mat4()){for(let c=0;c<4;c++)for(let r=0;r<4;r++){let s=0;for(let k=0;k<4;k++)s+=a[k*4+r]*b[c*4+k];o[c*4+r]=s}return o}
function perspective(fovy,aspect,near,far,o=mat4()){const f=1/Math.tan(fovy/2),nf=1/(near-far);o[0]=f/aspect;o[5]=f;o[10]=(far+near)*nf;o[11]=-1;o[14]=2*far*near*nf;return o}
function lookAt(eye,target,up=[0,1,0],o=mat4()){let zx=eye[0]-target[0],zy=eye[1]-target[1],zz=eye[2]-target[2],l=Math.hypot(zx,zy,zz)||1;zx/=l;zy/=l;zz/=l;let xx=up[1]*zz-up[2]*zy,xy=up[2]*zx-up[0]*zz,xz=up[0]*zy-up[1]*zx;l=Math.hypot(xx,xy,xz)||1;xx/=l;xy/=l;xz/=l;const yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;o[0]=xx;o[1]=yx;o[2]=zx;o[4]=xy;o[5]=yy;o[6]=zy;o[8]=xz;o[9]=yz;o[10]=zz;o[12]=-(xx*eye[0]+xy*eye[1]+xz*eye[2]);o[13]=-(yx*eye[0]+yy*eye[1]+yz*eye[2]);o[14]=-(zx*eye[0]+zy*eye[1]+zz*eye[2]);o[15]=1;return o}
function trs(x,y,z,sx=1,sy=1,sz=1,ry=0,rx=0,o=mat4()){const cy=Math.cos(ry),syy=Math.sin(ry),cx=Math.cos(rx),sxx=Math.sin(rx);o[0]=cy*sx;o[1]=syy*sxx*sx;o[2]=-syy*cx*sx;o[4]=0;o[5]=cx*sy;o[6]=sxx*sy;o[8]=syy*sz;o[9]=-cy*sxx*sz;o[10]=cy*cx*sz;o[12]=x;o[13]=y;o[14]=z;o[15]=1;return o}
function cube(){const p=[-1,-1,-1,1,-1,-1,1,1,-1,-1,1,-1,-1,-1,1,1,-1,1,1,1,1,-1,1,1],idx=[0,1,2,0,2,3,5,4,7,5,7,6,4,0,3,4,3,7,1,5,6,1,6,2,3,2,6,3,6,7,4,5,1,4,1,0];return{p:new Float32Array(p),i:new Uint16Array(idx)}}
function sphere(lat=7,lon=10){const p=[],i=[];for(let y=0;y<=lat;y++){const v=y/lat,ph=v*Math.PI;for(let x=0;x<=lon;x++){const u=x/lon,th=u*Math.PI*2;p.push(Math.sin(ph)*Math.cos(th),Math.cos(ph),Math.sin(ph)*Math.sin(th))}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){const a=y*(lon+1)+x,b=a+lon+1;i.push(a,b,a+1,b,b+1,a+1)}return{p:new Float32Array(p),i:new Uint16Array(i)}}
function compile(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)||"shader");return s}function program(gl){const vs=compile(gl,gl.VERTEX_SHADER,`#version 300 es\nin vec3 aPos;uniform mat4 uP,uV,uM;out vec3 vN;out vec3 vW;void main(){vec4 w=uM*vec4(aPos,1.);vW=w.xyz;vN=normalize(mat3(uM)*aPos);gl_Position=uP*uV*w;}`),fs=compile(gl,gl.FRAGMENT_SHADER,`#version 300 es\nprecision highp float;in vec3 vN;in vec3 vW;uniform vec4 uC;uniform vec3 uLight;out vec4 outColor;void main(){float d=max(.18,dot(normalize(vN),normalize(uLight)));float fog=clamp((length(vW.xz)-45.)/85.,0.,.42);vec3 c=uC.rgb*(.48+d*.62);c=mix(c,vec3(.025,.045,.06),fog);outColor=vec4(c,uC.a);}`);const p=gl.createProgram();gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||"link");return p}
function bufferMesh(gl,m){const vao=gl.createVertexArray();gl.bindVertexArray(vao);const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,m.p,gl.STATIC_DRAW);const loc=0;gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,m.i,gl.STATIC_DRAW);gl.bindVertexArray(null);return{vao,count:m.i.length}}
function makeScene(canvas){const gl=canvas.getContext("webgl2",{alpha:false,antialias:true,powerPreference:"high-performance"});if(!gl)throw new Error("WebGL2 yok");const dbg=gl.getExtension("WEBGL_debug_renderer_info"),renderer=String(dbg?gl.getParameter(dbg.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER)||"");const software=/swiftshader|llvmpipe|software/i.test(renderer);const pr=program(gl),cubeM=bufferMesh(gl,cube()),sphereM=bufferMesh(gl,sphere(software?5:7,software?7:10));gl.useProgram(pr);gl.bindAttribLocation(pr,0,"aPos");gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);stats.webgl2=true;return{gl,pr,cube:cubeM,sphere:sphereM,uP:gl.getUniformLocation(pr,"uP"),uV:gl.getUniformLocation(pr,"uV"),uM:gl.getUniformLocation(pr,"uM"),uC:gl.getUniformLocation(pr,"uC"),uLight:gl.getUniformLocation(pr,"uLight"),p:mat4(),v:mat4(),m:mat4(),software,renderer}}
function drawMesh(s,mesh,m,color){const g=s.gl;g.uniformMatrix4fv(s.uM,false,m);g.uniform4fv(s.uC,color);g.bindVertexArray(mesh.vao);g.drawElements(g.TRIANGLES,mesh.count,g.UNSIGNED_SHORT,0);stats.drawCalls++}
function lineBox(s,x,z,sx,sz,c=[.92,.96,.94,1]){drawMesh(s,s.cube,trs(x,.035,z,sx,.018,sz),c)}
function field(s){const q=resolveQuality(),low=q==="low",stripes=low?5:q==="medium"?7:10;drawMesh(s,s.cube,trs(0,-.18,0,53,.18,34),[.045,.28,.16,1]);for(let i=0;i<stripes;i++){const width=53/stripes,x=-53+width+i*width*2;drawMesh(s,s.cube,trs(x,-.01,0,width,.012,33.5),i%2?[.055,.35,.20,1]:[.045,.31,.18,1])}const w=[.94,.97,.94,1];lineBox(s,0,-33.6,52.6,.045,w);lineBox(s,0,33.6,52.6,.045,w);lineBox(s,-52.6,0,.045,33.6,w);lineBox(s,52.6,0,.045,33.6,w);lineBox(s,0,0,.035,33.5,w);lineBox(s,-43,0,.035,20,w);lineBox(s,43,0,.035,20,w);if(!low){lineBox(s,-48.5,0,.035,9,w);lineBox(s,48.5,0,.035,9,w)}const seg=low?6:q==="medium"?10:16;for(let j=0;j<seg;j++){const a=j/seg*Math.PI*2;lineBox(s,Math.cos(a)*9.15,Math.sin(a)*9.15,9.15*Math.PI/seg*.52,.035,w)}for(const side of[-1,1]){const gx=side*53.2;drawMesh(s,s.cube,trs(gx,1.25,-3.66,.07,1.25,.07),w);drawMesh(s,s.cube,trs(gx,1.25,3.66,.07,1.25,.07),w);drawMesh(s,s.cube,trs(gx,2.48,0,.07,.07,3.66),w);if(!low)drawMesh(s,s.cube,trs(gx+side*1.5,.25,0,1.5,.03,3.66),[.72,.78,.78,.32])}}
function stadium(s,t){const q=resolveQuality(),low=q==="low",levels=low?1:q==="medium"?2:3,dark=[.055,.07,.085,1],seat=[.08,.12,.16,1];for(const z of[-40,40])for(let l=0;l<levels;l++)drawMesh(s,s.cube,trs(0,1.5+l*2.5,z+(z<0?-l*2.2:l*2.2),58-l*3,1.4,3.2),l%2?seat:dark);for(const x of[-61,61])for(let l=0;l<levels;l++)drawMesh(s,s.cube,trs(x+(x<0?-l*2.2:l*2.2),1.5+l*2.5,0,3.2,1.4,39-l*2.5),l%2?seat:dark);if(!low)for(const [x,z] of[[-57,-37],[-57,37],[57,-37],[57,37]]){drawMesh(s,s.cube,trs(x,10,z,.12,10,.12),[.25,.28,.31,1]);drawMesh(s,s.cube,trs(x,20,z,2.2,.25,.7),[.92,.94,.78,1])}if(q==="high"&&!s.software&&!document.body.classList.contains("performance-lite")){for(let k=0;k<28;k++){const side=k%4,band=Math.floor(k/4),a=(band%7)/7;let x=0,z=0;if(side<2){x=-52+a*104;z=side?-41:41}else{x=side===2?-62:62;z=-34+a*68}const pulse=.55+.35*Math.sin(t*.002+k);drawMesh(s,s.sphere,trs(x,3.5+(k%3)*.75,z,.13,.13,.13),[.25+.45*pulse,.28,.32,1])}}}
function normPos(p){return{x:(p.x-.5)*96,z:(p.y-.5)*60}}
function player(s,p,color,ball,t,i,keeper=false){const q=normPos(p),b=ball?normPos(ball):{x:0,z:0},yaw=Math.atan2(b.x-q.x,b.z-q.z),quality=resolveQuality(),run=Math.sin(t*.009+i*1.7)*.22*(.5+(100-(p.stamina||100))/100),skin=[.72,.48,.33,1],shirt=keeper?[.18,.68,.38,1]:color,short=[Math.max(.04,shirt[0]*.48),Math.max(.04,shirt[1]*.48),Math.max(.04,shirt[2]*.48),1],sock=[.92,.93,.94,1];if(quality==="low"){drawMesh(s,s.cube,trs(q.x,1.38,q.z,.42,1.18,.28,yaw),shirt);return}drawMesh(s,s.cube,trs(q.x,.22,q.z,.42,.09,.32,yaw),[0,0,0,.22]);drawMesh(s,s.cube,trs(q.x,1.85,q.z,.46,.72,.27,yaw),shirt);drawMesh(s,s.sphere,trs(q.x,2.82,q.z,.34,.38,.34,yaw),skin);if(quality==="medium"){drawMesh(s,s.cube,trs(q.x, .73,q.z,.34,.55,.22,yaw,run*.25),short);return}drawMesh(s,s.cube,trs(q.x-.22,1.02+run,q.z,.15,.57,.14,yaw,run),short);drawMesh(s,s.cube,trs(q.x+.22,1.02-run,q.z,.15,.57,.14,yaw,-run),short);drawMesh(s,s.cube,trs(q.x-.55,1.85,q.z,.12,.54,.12,yaw,-run*.8),skin);drawMesh(s,s.cube,trs(q.x+.55,1.85,q.z,.12,.54,.12,yaw,run*.8),skin);drawMesh(s,s.cube,trs(q.x-.22,.35+run,q.z,.14,.38,.14,yaw),sock);drawMesh(s,s.cube,trs(q.x+.22,.35-run,q.z,.14,.38,.14,yaw),sock)}
function snapshot(v){return{at:performance.now(),home:v.visual.home.map(p=>[p.x,p.y,p.stamina||100]),away:v.visual.away.map(p=>[p.x,p.y,p.stamina||100]),ball:[v.visual.ball.x,v.visual.ball.y],focus:[v.visual.focus.x,v.visual.focus.y],event:v.visual.event,eventType:v.visual.eventType}}
function viewData(v,t){if(replay&&performance.now()<replay.until&&replay.list.length){const progress=clamp((performance.now()-replay.start)/(replay.until-replay.start),0,1),idx=Math.min(replay.list.length-1,Math.floor(progress*replay.list.length)),r=replay.list[idx];return{home:r.home.map((a,i)=>({...v.visual.home[i],x:a[0],y:a[1],stamina:a[2]})),away:r.away.map((a,i)=>({...v.visual.away[i],x:a[0],y:a[1],stamina:a[2]})),ball:{x:r.ball[0],y:r.ball[1]},focus:{x:r.focus[0],y:r.focus[1]},replay:true}}if(replay&&performance.now()>=replay.until)replay=null;return{home:v.visual.home,away:v.visual.away,ball:v.visual.ball,focus:v.visual.focus,replay:false}}
function source(){const online=document.getElementById("v7OnlineCanvas");if(online){const n=window.QF_V7_ONLINE_TEST?.net?.();if(n?.match?.running&&n.match.v9)return{canvas:online,match:n.match,v:n.match.v9,home:n.hostClub,away:n.guestClub,online:true}}const solo=document.getElementById("v7MatchCanvas");if(solo){const m=window.QF_V7_TEST?.match?.();if(m?.running&&m.v9)return{canvas:solo,match:m,v:m.v9,home:window.QF_V7_CORE?.clubSnapshot?.(),away:m.opponent,online:false}}return null}
function cameraFor(data,w,h){const f=data.focus||{x:.5,y:.5},fx=(f.x-.5)*70,fz=(f.y-.5)*42,evt=lastEvent;let eye,target;if(cfg.camera==="tactical"){eye=[0,78,.01];target=[0,0,0]}else if(cfg.camera==="goal"){const side=evt?.side==="away"?-1:1;eye=[side*48,13,2];target=[side*28,0,0]}else{const boost=evt?.type==="goal"||data.replay?1:0;eye=[fx-14-boost*7,34-boost*6,54-boost*12];target=[fx*.72,0,fz*.45]}return{eye,target}}
function render(src,time){const c=activeCanvas,s=scene,g=s.gl,rect=sourceCanvas.getBoundingClientRect(),quality=resolveQuality(),dpr=Math.min(devicePixelRatio||1,quality==="high"?1.55:quality==="medium"?1.15:.9),w=Math.max(640,Math.round(rect.width*dpr)),h=Math.max(360,Math.round(rect.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h}g.viewport(0,0,w,h);g.clearColor(.012,.025,.035,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);stats.drawCalls=0;perspective(Math.PI/4.2,w/h,.1,240,s.p);const data=viewData(src.v,time),cam=cameraFor(data,w,h);lookAt(cam.eye,cam.target,[0,1,0],s.v);g.useProgram(s.pr);g.uniformMatrix4fv(s.uP,false,s.p);g.uniformMatrix4fv(s.uV,false,s.v);g.uniform3fv(s.uLight,new Float32Array([-.25,.85,.42]));field(s);stadium(s,time);const hc=hex(src.home?.color||src.home?.colors?.primary||"#2ea8ff"),ac=hex(src.away?.color||"#e8c66a");for(let i=0;i<data.home.length;i++)player(s,data.home[i],hc,data.ball,time,i,i===0);for(let i=0;i<data.away.length;i++)player(s,data.away[i],ac,data.ball,time,i+11,i===0);const b=normPos(data.ball);drawMesh(s,s.cube,trs(b.x,.17,b.z,.42,.07,.42),[0,0,0,.18]);drawMesh(s,s.sphere,trs(b.x,.55,b.z,.32,.32,.32,time*.004),[.96,.97,.94,1]);updateHud(src,data,quality)}
function resolveQuality(){if(cfg.quality!=="auto")return cfg.quality;if(scene?.software||document.body.classList.contains("performance-lite"))return"low";if((navigator.hardwareConcurrency||4)>=8&&(devicePixelRatio||1)<=2)return"high";return"medium"}
function attach(src){if(sourceCanvas===src.canvas&&activeCanvas?.isConnected)return;detach();sourceCanvas=src.canvas;const p=sourceCanvas.parentElement;p.style.position="relative";const c=document.createElement("canvas");c.id="v10MatchCanvas3D";c.className="v10-gl-canvas";c.setAttribute("aria-label","3D canlı futbol maç simülasyonu");p.insertBefore(c,sourceCanvas.nextSibling);activeCanvas=c;try{scene=makeScene(c);sourceCanvas.classList.add("v10-fallback-hidden");stats.fallback="";ensureHud(p)}catch(e){stats.fallback=String(e?.message||e);c.remove();activeCanvas=null;scene=null;sourceCanvas.classList.remove("v10-fallback-hidden");ensureFallbackBadge(p)}}
function detach(){if(sourceCanvas)sourceCanvas.classList.remove("v10-fallback-hidden");activeCanvas?.remove();document.getElementById("v10BroadcastHud")?.remove();document.getElementById("v10FallbackBadge")?.remove();sourceCanvas=null;activeCanvas=null;scene=null;snapshots=[];replay=null}
function ensureFallbackBadge(p){let e=document.getElementById("v10FallbackBadge");if(!e){e=document.createElement("div");e.id="v10FallbackBadge";e.className="v10-fallback-badge";e.textContent="2.5D GÜVENLİ MOD";p.appendChild(e)}}
function ensureHud(p){let e=document.getElementById("v10BroadcastHud");if(e)return;e=document.createElement("div");e.id="v10BroadcastHud";e.className="v10-broadcast-hud";e.innerHTML=`<div class="v10-live"><i></i><b>3D CANLI</b><span id="v10CamName">YAYIN</span></div><div class="v10-hud-actions"><button data-v10cam="broadcast">Yayın</button><button data-v10cam="tactical">Taktik</button><button data-v10cam="goal">Kale</button><select id="v10Quality" aria-label="Grafik kalitesi"><option value="auto">Otomatik</option><option value="high">Yüksek</option><option value="medium">Orta</option><option value="low">Düşük</option></select></div><div id="v10ReplayBadge" class="v10-replay">TEKRAR</div>`;p.appendChild(e);e.querySelectorAll("[data-v10cam]").forEach(b=>b.onclick=()=>{cfg.camera=b.dataset.v10cam;save();e.querySelectorAll("[data-v10cam]").forEach(x=>x.classList.toggle("active",x===b))});const q=e.querySelector("#v10Quality");q.value=cfg.quality;q.onchange=()=>{cfg.quality=q.value;save()};e.querySelector(`[data-v10cam="${cfg.camera}"]`)?.classList.add("active")}
function updateHud(src,data,quality){const h=document.getElementById("v10BroadcastHud");if(!h)return;const cam=h.querySelector("#v10CamName");if(cam)cam.textContent=(cfg.camera==="broadcast"?"YAYIN":cfg.camera==="tactical"?"TAKTİK":"KALE")+` • ${quality.toUpperCase()}`;h.querySelector("#v10ReplayBadge")?.classList.toggle("show",!!data.replay)}
function tick(t){const interval=Math.max(1,t-last);last=t;intervals.push(interval);if(intervals.length>120)intervals.shift();stats.avgIntervalMs=intervals.reduce((a,b)=>a+b,0)/intervals.length;stats.frames++;stats.quality=resolveQuality();const src=source();if(!cfg.enabled||!src){if(!src)detach();raf=requestAnimationFrame(tick);return}attach(src);if(scene&&activeCanvas){if(t-lastSnap>90){snapshots.push(snapshot(src.v));if(snapshots.length>34)snapshots.shift();lastSnap=t}const rs=performance.now();render(src,t);const cost=Math.max(.01,performance.now()-rs);stats.lastFrameMs=cost;frames.push(cost);if(frames.length>120)frames.shift();stats.avgFrameMs=frames.reduce((a,b)=>a+b,0)/frames.length}if(cfg.quality==="auto"&&frames.length>=24&&stats.avgFrameMs>24&&!scene?.software&&!document.body.classList.contains("performance-lite")){document.body.classList.add("performance-lite");stats.quality="low"}raf=requestAnimationFrame(tick)}
window.addEventListener("qf:v9-event",e=>{lastEvent=e.detail||{};if(lastEvent.type==="goal"&&cfg.replays&&snapshots.length>8){replay={list:snapshots.slice(-24),start:performance.now()+500,until:performance.now()+2700};stats.replays++}});
window.addEventListener("beforeunload",()=>cancelAnimationFrame(raf));if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{raf=requestAnimationFrame(tick)},{once:true});else raf=requestAnimationFrame(tick);
window.QF_MATCH_3D_V10={getSettings:()=>({...cfg}),setSetting:(k,v)=>{if(k in cfg){cfg[k]=v;save();return true}return false},state:()=>({...stats,active:!!scene,replay:!!replay,canvas:activeCanvas?.id||"",software:!!scene?.software,renderer:scene?.renderer||""}),forceReplay:()=>{if(snapshots.length){replay={list:snapshots.slice(),start:performance.now(),until:performance.now()+1800};stats.replays++;return true}return false}};
})();