(()=>{"use strict";const C=()=>window.QF_V7_CORE,D=window.QF_DATA||{},IMG=window.QF_IMAGES||{};let N={peer:null,conn:null,isHost:false,room:"",hostClub:null,guestClub:null,match:null,timer:0,qTimer:0};const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function code(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join("")}
function status(html){const e=$("v7OnlineStatus");if(e)e.innerHTML=html}
function close(){clearInterval(N.timer);clearInterval(N.qTimer);try{N.conn?.close()}catch{}try{N.peer?.destroy()}catch{}N={peer:null,conn:null,isHost:false,room:"",hostClub:null,guestClub:null,match:null,timer:0,qTimer:0}}
function bind(){const h=$("v7OnlineHost"),j=$("v7OnlineJoin");if(h)h.onclick=create;if(j)j.onclick=()=>join(($("v7OnlineCode")?.value||"").trim().toUpperCase())}
function create(){if(!window.Peer){C().toast("Peer bağlantı kütüphanesi hazır değil.");return}close();N.isHost=true;N.room=code();N.hostClub=C().clubSnapshot();status(`<div class="v7-card"><small>ODA KODU</small><div class="v7-code">${N.room}</div><p>Rakip başkan bekleniyor…</p></div>`);N.peer=new Peer(`qfv7-${N.room}`);N.peer.on("connection",conn=>{if(N.conn){conn.close();return}N.conn=conn;wire(conn)});N.peer.on("error",()=>status(`<small>Oda açılamadı. Yeniden dene.</small>`))}
function join(room){if(!room||room.length<4){C().toast("Geçerli oda kodu gir.");return}if(!window.Peer){C().toast("Peer bağlantı kütüphanesi hazır değil.");return}close();N.isHost=false;N.room=room;N.guestClub=C().clubSnapshot();status(`<div class="v7-card"><p>${room} odasına bağlanılıyor…</p></div>`);N.peer=new Peer();N.peer.on("open",()=>{N.conn=N.peer.connect(`qfv7-${room}`,{reliable:true});wire(N.conn)});N.peer.on("error",()=>status(`<small>Odaya bağlanılamadı.</small>`))}
function wire(conn){conn.on("open",()=>{if(N.isHost){status(`<div class="v7-card"><p>Rakip bağlandı. Kulüp bilgisi bekleniyor…</p></div>`)}else conn.send({t:"hello",club:C().clubSnapshot()})});conn.on("data",msg=>onMsg(msg));conn.on("close",()=>{if(N.match?.running)end("disconnect");else status(`<small>Bağlantı kapandı.</small>`)});conn.on("error",()=>{})}
function onMsg(m){if(!m||!m.t)return;if(N.isHost){if(m.t==="hello"){N.guestClub=m.club;N.conn.send({t:"welcome",club:N.hostClub});renderLobby()}else if(m.t==="answer")hostAnswer("away",m.id,m.qid)}else{if(m.t==="welcome"){N.hostClub=m.club;renderLobby()}else if(m.t==="start"){N.match=m.state;renderMatch()}else if(m.t==="state"){N.match=m.state;update()}else if(m.t==="question"){N.match.question=m.question;N.match.answeredAway=false;renderQuestion()}else if(m.t==="end"){N.match=m.state;renderEnd()}}}
function renderLobby(){const me=N.isHost?N.hostClub:N.guestClub,op=N.isHost?N.guestClub:N.hostClub;if(!me||!op)return;status(`<div class="v7-card"><div class="v7-scoreboard"><div class="v7-team-name"><b>${esc(me.name)}</b><small>${me.strength} güç</small></div><div class="v7-score">VS</div><div class="v7-team-name"><b>${esc(op.name)}</b><small>${op.strength} güç</small></div></div><div class="v7-lobby-players"><div class="v7-lobby-player">✓ ${esc(me.name)}</div><div class="v7-lobby-player">✓ ${esc(op.name)}</div></div>${N.isHost?`<button class="v7-btn primary" id="v7OnlineStart" style="margin-top:12px">2 Dakikalık Maçı Başlat</button>`:`<p style="color:var(--v7muted)">Kurucu maçı başlatacak.</p>`}</div>`);if(N.isHost)$("v7OnlineStart").onclick=start}
function blankMatch(){return{running:true,start:performance.now(),duration:120000,minute:0,home:0,away:0,momentumHome:0,momentumAway:0,multHome:1,multAway:1,correctHome:0,correctAway:0,wrongHome:0,wrongAway:0,xgHome:0,xgAway:0,shotsHome:0,shotsAway:0,question:C().makeQuestion(),answeredHome:false,answeredAway:false,firstCorrect:"",qExpires:performance.now()+6000,lastEvent:performance.now(),events:["0' Canlı başkanlar maçı başladı."]}}
function start(){if(!N.isHost||!N.guestClub)return;N.match=blankMatch();N.conn.send({t:"start",state:N.match});renderMatch();N.timer=setInterval(hostTick,500);N.qTimer=setInterval(hostQuestionTick,200)}
function screen(){C().go("match");return $("v7-match")}
function renderMatch(){const el=screen(),h=N.hostClub,g=N.guestClub;if(!el||!h||!g||!N.match)return;el.innerHTML=`<div class="v7-head"><div><h1>Canlı Online Kulüp Maçı</h1><p>Gerçek 2 dakika = 90 dakika. Quiz doğruları gol çarpanını yükseltir.</p></div><span class="v7-chip">ODA ${N.room}</span></div><div class="v7-match"><div><div class="v7-scoreboard"><div class="v7-team-name"><b>${esc(h.name)}</b><small>${h.strength} güç</small></div><div class="v7-score"><span id="v7OnH">0</span> - <span id="v7OnA">0</span></div><div class="v7-team-name"><b>${esc(g.name)}</b><small>${g.strength} güç</small></div></div><canvas id="v7OnlineCanvas" class="v7-match-canvas"></canvas><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:10px"><div><div style="display:flex;justify-content:space-between"><b>${esc(h.short)}</b><span id="v7OnHM">0% • ×1.00</span></div><div class="v7-meter"><i id="v7OnHBar"></i></div></div><div><div style="display:flex;justify-content:space-between"><b>${esc(g.short)}</b><span id="v7OnAM">0% • ×1.00</span></div><div class="v7-meter gold"><i id="v7OnABar"></i></div></div></div></div><aside class="v7-match-side"><div id="v7OnlineQ"></div><section class="v7-card"><div class="v7-card-title"><h3>Canlı Maç</h3><b id="v7OnMin">0'</b></div><div class="v7-metrics"><div class="v7-metric"><b id="v7OnMyCorrect">0</b><span>SENİN DOĞRU</span></div><div class="v7-metric"><b id="v7OnOppCorrect">0</b><span>RAKİP DOĞRU</span></div><div class="v7-metric"><b id="v7OnXg">0.00</b><span>TOPLAM xG</span></div><div class="v7-metric"><b>2:00</b><span>SÜRE</span></div></div><div class="v7-eventlog" id="v7OnLog"></div></section></aside></div>`;renderQuestion();update();requestAnimationFrame(draw)}
function renderQuestion(){const el=$("v7OnlineQ");if(!el||!N.match?.question)return;const q=N.match.question,side=N.isHost?"Home":"Away",answered=N.match[`answered${side}`];el.innerHTML=C().questionHtml(q,answered);el.querySelectorAll("[data-qanswer]").forEach(b=>b.onclick=()=>submitAnswer(b.dataset.qanswer))}
function submitAnswer(id){if(!N.match?.running)return;const key=N.isHost?"answeredHome":"answeredAway";if(N.match[key])return;if(N.isHost)hostAnswer("home",id,N.match.question.id);else{N.match.answeredAway=true;N.conn.send({t:"answer",id,qid:N.match.question.id});renderQuestion()}}
function hostAnswer(side,id,qid){if(!N.match?.running||qid!==N.match.question.id)return;const k=side==="home"?"answeredHome":"answeredAway";if(N.match[k])return;N.match[k]=true;const ok=id===N.match.question.correct;if(ok){const first=!N.match.firstCorrect;N.match.firstCorrect= N.match.firstCorrect||side;const gain=first?18:9,mm=side==="home"?"momentumHome":"momentumAway",cc=side==="home"?"correctHome":"correctAway";N.match[cc]++;N.match[mm]=clamp(N.match[mm]+gain,0,100);log(`${Math.round(N.match.minute)}' ${side==="home"?N.hostClub.short:N.guestClub.short} doğru cevap: +${gain} momentum.`)}else{const mm=side==="home"?"momentumHome":"momentumAway",ww=side==="home"?"wrongHome":"wrongAway";N.match[ww]++;N.match[mm]=clamp(N.match[mm]-4,0,100);log(`${Math.round(N.match.minute)}' Yanlış cevap: momentum kaybı.`)}calcMult();broadcast();if(N.match.answeredHome&&N.match.answeredAway)N.match.qExpires=performance.now()+650;renderQuestion()}
function calcMult(){N.match.multHome=1+N.match.momentumHome/100*.9+(N.hostClub.strength-70)/140;N.match.multAway=1+N.match.momentumAway/100*.9+(N.guestClub.strength-70)/140}
function hostQuestionTick(){if(!N.isHost||!N.match?.running)return;if(performance.now()>=N.match.qExpires){N.match.question=C().makeQuestion();N.match.answeredHome=false;N.match.answeredAway=false;N.match.firstCorrect="";N.match.qExpires=performance.now()+6000;N.conn.send({t:"question",question:N.match.question});renderQuestion()}}
function attackChance(side){const me=side==="home"?N.hostClub:N.guestClub,op=side==="home"?N.guestClub:N.hostClub,mom=side==="home"?N.match.momentumHome:N.match.momentumAway,mult=side==="home"?N.match.multHome:N.match.multAway;return clamp(.025+(me.strength-op.strength)*.0015+mom*.0008+(mult-1)*.025,.012,.18)}
function hostTick(){if(!N.isHost||!N.match?.running)return;const now=performance.now(),elapsed=now-N.match.start;N.match.minute=clamp(elapsed/N.match.duration*90,0,90);if(window.QF_MATCH_V9?.stepOnline){const ev=window.QF_MATCH_V9.stepOnline(N.match,{now,elapsed,homeClub:N.hostClub,awayClub:N.guestClub});if(ev?.text)log(ev.text);calcMult();broadcast();update();if(elapsed>=N.match.duration)end("time");return}if(now-N.match.lastEvent>1700){N.match.lastEvent=now;const homeBias=.5+(N.hostClub.strength-N.guestClub.strength)/220+(N.match.momentumHome-N.match.momentumAway)/600,side=Math.random()<homeBias?"home":"away",xg=clamp(.04+Math.random()*.31+(side==="home"?N.match.momentumHome:N.match.momentumAway)/240,.03,.68);if(side==="home"){N.match.xgHome+=xg;N.match.shotsHome++;if(Math.random()<xg*attackChance("home")*4.1){N.match.home++;N.match.momentumHome=0;N.match.multHome=1;log(`${Math.round(N.match.minute)}' GOL ${N.hostClub.short}! Momentum sıfırlandı.`)}else{const miss=Math.random();if(miss<.42)log(`${Math.round(N.match.minute)}' ${N.hostClub.short} şutu dışarı gitti.`);else if(miss<.78)log(`${Math.round(N.match.minute)}' ${N.hostClub.short} şutunda kaleci kurtardı.`);else log(`${Math.round(N.match.minute)}' ${N.hostClub.short} direğe takıldı!`)}}else{N.match.xgAway+=xg;N.match.shotsAway++;if(Math.random()<xg*attackChance("away")*4.1){N.match.away++;N.match.momentumAway=0;N.match.multAway=1;log(`${Math.round(N.match.minute)}' GOL ${N.guestClub.short}! Momentum sıfırlandı.`)}else{const miss=Math.random();if(miss<.42)log(`${Math.round(N.match.minute)}' ${N.guestClub.short} şutu dışarı gitti.`);else if(miss<.78)log(`${Math.round(N.match.minute)}' ${N.guestClub.short} şutunda kaleci kurtardı.`);else log(`${Math.round(N.match.minute)}' ${N.guestClub.short} direğe takıldı!`)}}}calcMult();broadcast();update();if(elapsed>=N.match.duration)end("time")}
function broadcast(){try{N.conn?.send({t:"state",state:N.match})}catch{}}
function log(t){N.match.events.unshift(t);N.match.events=N.match.events.slice(0,18)}
function update(){if(!N.match)return;const set=(id,t)=>{const e=$(id);if(e)e.textContent=t};set("v7OnH",N.match.home);set("v7OnA",N.match.away);set("v7OnMin",`${Math.round(N.match.minute)}'`);set("v7OnHM",`${Math.round(N.match.momentumHome)}% • ×${N.match.multHome.toFixed(2)}`);set("v7OnAM",`${Math.round(N.match.momentumAway)}% • ×${N.match.multAway.toFixed(2)}`);const my=N.isHost?N.match.correctHome:N.match.correctAway,opp=N.isHost?N.match.correctAway:N.match.correctHome;set("v7OnMyCorrect",my);set("v7OnOppCorrect",opp);set("v7OnXg",(N.match.xgHome+N.match.xgAway).toFixed(2));const hb=$("v7OnHBar"),ab=$("v7OnABar");if(hb)hb.style.width=`${N.match.momentumHome}%`;if(ab)ab.style.width=`${N.match.momentumAway}%`;const logEl=$("v7OnLog");if(logEl)logEl.innerHTML=N.match.events.map(x=>`<div>${esc(x)}</div>`).join("");renderQuestion()}
function draw(){if(!N.match?.running)return;const c=$("v7OnlineCanvas");if(c){if(window.QF_MATCH_V9?.drawOnline?.(c,N.match,N.hostClub,N.guestClub)){requestAnimationFrame(draw);return}const w=Math.max(620,c.clientWidth),h=w*9/16,dpr=Math.min(devicePixelRatio||1,1.35);if(c.width!==Math.round(w*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr)}const g=c.getContext("2d");g.setTransform(dpr,0,0,dpr,0,0);g.fillStyle="#12623e";g.fillRect(0,0,w,h);g.strokeStyle="rgba(255,255,255,.45)";g.lineWidth=2;g.strokeRect(18,18,w-36,h-36);g.beginPath();g.moveTo(w/2,18);g.lineTo(w/2,h-18);g.stroke();g.beginPath();g.arc(w/2,h/2,54,0,Math.PI*2);g.stroke();const t=performance.now()/1000;for(let team=0;team<2;team++){g.fillStyle=team===0?(N.hostClub.color||"#49b5ff"):"#e6c86f";for(let i=0;i<11;i++){const row=Math.floor(i/4),lane=i%4,x=team===0?90+row*125:w-90-row*125,y=65+lane*(h-130)/3+Math.sin(t+i)*7;g.beginPath();g.arc(x,y,7,0,Math.PI*2);g.fill()}}g.fillStyle="#fff";g.beginPath();g.arc(w/2+Math.sin(t*1.5)*w*.2,h/2+Math.cos(t*.8)*h*.2,5,0,Math.PI*2);g.fill()}requestAnimationFrame(draw)}
function end(reason){if(!N.match||!N.match.running)return;N.match.running=false;clearInterval(N.timer);clearInterval(N.qTimer);if(N.isHost)N.conn?.send({t:"end",state:N.match});renderEnd()}
function renderEnd(){const el=$("v7-match");if(!el||!N.match)return;const me=N.isHost?N.hostClub:N.guestClub,opp=N.isHost?N.guestClub:N.hostClub,my=N.isHost?N.match.home:N.match.away,other=N.isHost?N.match.away:N.match.home,correct=N.isHost?N.match.correctHome:N.match.correctAway;C().applyOnlineResult({at:Date.now(),opponent:opp.name,type:"Online Kulüp",gf:my,ga:other,correct,wrong:N.isHost?N.match.wrongHome:N.match.wrongAway,xgFor:N.isHost?N.match.xgHome:N.match.xgAway,xgAgainst:N.isHost?N.match.xgAway:N.match.xgHome});el.innerHTML=`<div class="v7-head"><div><h1>Online Maç Bitti</h1><p>İki kulübün 90 dakikalık simülasyonu 2 gerçek dakikada tamamlandı.</p></div></div><section class="v7-card"><div class="v7-scoreboard"><div class="v7-team-name"><b>${esc(N.hostClub.name)}</b></div><div class="v7-score">${N.match.home} - ${N.match.away}</div><div class="v7-team-name"><b>${esc(N.guestClub.name)}</b></div></div><div class="v7-metrics"><div class="v7-metric"><b>${N.match.correctHome}</b><span>EV DOĞRU</span></div><div class="v7-metric"><b>${N.match.correctAway}</b><span>DEP DOĞRU</span></div><div class="v7-metric"><b>${N.match.xgHome.toFixed(2)}</b><span>EV xG</span></div><div class="v7-metric"><b>${N.match.xgAway.toFixed(2)}</b><span>DEP xG</span></div></div><button class="v7-btn primary" id="v7OnlineBack" style="margin-top:14px">Online Merkeze Dön</button></section>`;$("v7OnlineBack").onclick=()=>{close();C().go("online")}}
window.QF_V7_ONLINE={bind,create,join,close};window.QF_V7_ONLINE_TEST={net:()=>N,hostAnswer:(id)=>hostAnswer("home",id,N.match?.question?.id),forceGoal:(side="home")=>{if(!N.match)return;if(side==="home"){N.match.home++;N.match.momentumHome=0}else{N.match.away++;N.match.momentumAway=0}calcMult();broadcast();update()},finish:()=>{if(N.match){N.match.start=performance.now()-N.match.duration;hostTick()}}};
})();