(()=>{"use strict";
const state={fitRuns:0,tight:false,pagers:0,lastScreen:"",version:"13.0.0",legacyDisabled:false,swUpdated:false,officeClosed:0};let fitTimer=0,scanTimer=0;
function activeScreen(){return document.querySelector(".v7-screen.active")}
function updateVersionLabels(){document.title="Quiz Football V13 — 3D Match Broadcast";document.querySelectorAll(".v7-brand small").forEach(x=>x.textContent="CHAIRMAN MODE • V13");document.querySelectorAll(".brand small").forEach(x=>x.textContent="V13")}
function disableLegacy(){try{window.QF_MATCH_3D_V10?.setSetting?.("enabled",false);window.QF_MATCH_3D_V11?.setSetting?.("enabled",false);window.QF_COMMENTARY_V10_SUPPRESS_V8=true;document.body.classList.remove("performance-lite","v12-smooth-renderer","v12-low-motion");for(const id of["v10MatchCanvas3D","v11MatchCanvas3D","v10BroadcastHud","v11BroadcastHud","v12RenderBadge","v10CommentaryControls"])document.getElementById(id)?.remove();state.legacyDisabled=true}catch{}}
function perPage(list){if(list.closest("#v7-market"))return 10;if(list.closest("#v7-manager"))return 8;if(list.closest("#v7-squad"))return 8;if(list.closest(".v9-office"))return 8;return 10}
function applyPage(list,keep=false){if(!list?.isConnected)return;const items=[...list.children].filter(x=>!x.classList.contains("v13-pager"));if(!items.length)return;const per=perPage(list),pages=Math.max(1,Math.ceil(items.length/per));let page=keep?+(list.dataset.v13Page||0):+(list.dataset.v13Page||0);page=clamp(page,0,pages-1);list.dataset.v13Page=String(page);items.forEach((el,i)=>{el.style.display=i>=page*per&&i<(page+1)*per?"":"none"});let pager=list.nextElementSibling;if(!pager?.classList.contains("v13-pager")){pager=document.createElement("div");pager.className="v13-pager";pager.innerHTML='<button type="button" data-dir="-1">← Önceki</button><span></span><button type="button" data-dir="1">Sonraki →</button>';list.insertAdjacentElement("afterend",pager);pager.addEventListener("click",e=>{const b=e.target.closest("button[data-dir]");if(!b)return;list.dataset.v13Page=String(clamp((+list.dataset.v13Page||0)+(+b.dataset.dir),0,Math.max(0,Math.ceil([...list.children].length/per)-1)));applyPage(list,true);fit()});state.pagers++}const span=pager.querySelector("span"),btns=pager.querySelectorAll("button");if(span)span.textContent=`${page+1} / ${pages}`;if(btns[0])btns[0].disabled=page<=0;if(btns[1])btns[1].disabled=page>=pages-1;pager.style.display=pages>1?"flex":"none"}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function paginate(){const selectors=["#v7-squad .v7-list","#v7-manager .v7-list","#v7MarketGrid",".v9-office .v9-list"];for(const sel of selectors)document.querySelectorAll(sel).forEach(l=>applyPage(l,true))}
function fit(){clearTimeout(fitTimer);fitTimer=setTimeout(()=>{if(innerWidth<=760)return;const main=document.querySelector(".v7-main"),screen=activeScreen();if(!main||!screen)return;screen.style.zoom="1";screen.style.transform="";main.scrollTop=0;document.body.classList.remove("v13-tight");requestAnimationFrame(()=>{const overflow=screen.scrollHeight>main.clientHeight+3||screen.getBoundingClientRect().bottom>main.getBoundingClientRect().bottom+3;if(overflow)document.body.classList.add("v13-tight");state.tight=overflow;state.fitRuns++;state.lastScreen=screen.id||"";main.scrollTop=0})},60)}
function closeMatchOverlays(){if(!document.querySelector("#v7-match.active,#v7-online-match.active"))return;document.querySelectorAll("#v9Office.open,.v9-office.open").forEach(x=>{x.classList.remove("open");state.officeClosed++})}
function scan(){updateVersionLabels();disableLegacy();closeMatchOverlays();paginate();fit();const match=!!document.querySelector("#v7-match.active,#v7-online-match.active");document.body.classList.toggle("v13-match-active",match)}
function updateServiceWorker(){if(!("serviceWorker" in navigator))return;navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.update().catch(()=>null)))).then(()=>state.swUpdated=true).catch(()=>{})}
function boot(){document.body.classList.add("v13-runtime");disableLegacy();updateVersionLabels();paginate();fit();updateServiceWorker();clearInterval(scanTimer);scanTimer=setInterval(scan,900);const root=document.querySelector("#chairmanV7")||document.body;new MutationObserver(m=>{let needs=false;for(const r of m){if(r.type==="childList"||r.type==="attributes"){needs=true;break}}if(needs){clearTimeout(root.__v13mo);root.__v13mo=setTimeout(()=>{paginate();updateVersionLabels();fit()},80)}}).observe(root,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});window.addEventListener("resize",fit)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
window.QF_V13={state:()=>({...state,screen:activeScreen()?.id||"",renderer:window.QF_MATCH_3D_V13?.state?.()||{},commentary:window.QF_COMMENTARY_V13?.state?.()||{}}),fit,paginate,scan};
})();
