(()=>{"use strict";
const state={fitRuns:0,tight:false,pagers:0,lastScreen:"",version:"15.0.0",legacyDisabled:false,swUpdated:false,officeClosed:0,audioRaised:false,readability:true,mutations:0,overlayGuards:0};let fitTimer=0,observerTimer=0,lastMatch=false,guardTimer=0,officeObserver=null;
function activeScreen(){return document.querySelector(".v7-screen.active")}
function updateVersionLabels(){document.title="Quiz Football V15 — 3D Match Broadcast";document.querySelectorAll(".v7-brand small").forEach(x=>x.textContent="CHAIRMAN MODE • V15");document.querySelectorAll(".brand small").forEach(x=>x.textContent="V15")}
function ensureReadableStyle(){if(document.getElementById("v13ReadableBoost"))return;const s=document.createElement("style");s.id="v13ReadableBoost";s.textContent=`body.v13-runtime .v7-row b{font-size:13px!important}body.v13-runtime .v7-row small{font-size:11px!important}body.v13-runtime .v7-chip{font-size:11px!important}body.v13-runtime .v7-table td{font-size:12px!important}body.v13-runtime .v7-table th{font-size:11px!important}body.v13-runtime .v7-metric span{font-size:11px!important}#v7-squad .v7-player-dot b{font-size:12px!important;text-shadow:0 1px 3px #000}#v7-squad .v7-player-dot span{font-size:10.5px!important}#v7-match .v7-qclub b{font-size:13px!important}#v7-match .v7-qopt{font-size:12px!important}#v7-match .v7-eventlog{font-size:11.5px!important}.v13-pager button,.v13-pager span{font-size:12px!important}`;document.head.appendChild(s)}
function disableLegacy(){if(state.legacyDisabled)return;try{window.QF_MATCH_3D_V10?.setSetting?.("enabled",false);window.QF_MATCH_3D_V11?.setSetting?.("enabled",false);window.QF_COMMENTARY_V10_SUPPRESS_V8=true;document.body.classList.remove("performance-lite","v12-smooth-renderer","v12-low-motion");for(const id of["v10MatchCanvas3D","v11MatchCanvas3D","v10BroadcastHud","v11BroadcastHud","v12RenderBadge","v10CommentaryControls"])document.getElementById(id)?.remove();state.legacyDisabled=true}catch{}}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function perPage(list){if(list.closest("#v7-market"))return 8;if(list.closest("#v7-manager"))return 7;if(list.closest("#v7-squad"))return 6;if(list.closest(".v9-office"))return 7;return 8}
function applyPage(list,keep=false){if(!list?.isConnected)return;const items=[...list.children].filter(x=>!x.classList.contains("v13-pager"));if(!items.length)return;const per=perPage(list),pages=Math.max(1,Math.ceil(items.length/per));let page=keep?+(list.dataset.v13Page||0):0;page=clamp(page,0,pages-1);list.dataset.v13Page=String(page);items.forEach((el,i)=>{el.style.display=i>=page*per&&i<(page+1)*per?"":"none"});let pager=list.nextElementSibling;if(!pager?.classList.contains("v13-pager")){pager=document.createElement("div");pager.className="v13-pager";pager.innerHTML='<button type="button" data-dir="-1">← Önceki</button><span></span><button type="button" data-dir="1">Sonraki →</button>';list.insertAdjacentElement("afterend",pager);pager.addEventListener("click",e=>{const b=e.target.closest("button[data-dir]");if(!b)return;list.dataset.v13Page=String(clamp((+list.dataset.v13Page||0)+(+b.dataset.dir),0,pages-1));applyPage(list,true);fit()});state.pagers++}const span=pager.querySelector("span"),btns=pager.querySelectorAll("button");if(span)span.textContent=`${page+1} / ${pages}`;if(btns[0])btns[0].disabled=page<=0;if(btns[1])btns[1].disabled=page>=pages-1;pager.style.display=pages>1?"flex":"none"}
function paginate(){for(const sel of["#v7-squad .v7-list","#v7-manager .v7-list","#v7MarketGrid",".v9-office .v9-list"])document.querySelectorAll(sel).forEach(l=>applyPage(l,true))}
function fit(){clearTimeout(fitTimer);fitTimer=setTimeout(()=>{if(innerWidth<=760)return;const main=document.querySelector(".v7-main"),screen=activeScreen();if(!main||!screen)return;screen.style.zoom="1";screen.style.transform="";main.scrollTop=0;document.body.classList.remove("v13-tight");requestAnimationFrame(()=>{const mr=main.getBoundingClientRect(),sr=screen.getBoundingClientRect(),overflow=screen.scrollHeight>main.clientHeight+3||sr.bottom>mr.bottom+3;if(overflow)document.body.classList.add("v13-tight");state.tight=overflow;state.fitRuns++;state.lastScreen=screen.id||"";main.scrollTop=0})},90)}
function matchActive(){return!!document.querySelector("#v7-match.active,#v7-online-match.active")}
function closeMatchOverlays(){if(!matchActive())return;document.body.classList.add("v13-match-active");document.querySelectorAll("#v9Office,.v9-office").forEach(x=>{if(x.classList.contains("open")){x.classList.remove("open");state.officeClosed++}x.setAttribute("aria-hidden","true")})}
function guardMatchOverlays(){if(!matchActive())return;state.overlayGuards++;closeMatchOverlays();cancelAnimationFrame(guardTimer);guardTimer=requestAnimationFrame(closeMatchOverlays);for(const ms of[60,160,360,760,1200])setTimeout(()=>{if(matchActive())closeMatchOverlays()},ms)}
function watchOffice(){const office=document.querySelector("#v9Office,.v9-office");if(!office||office.__v13Watched)return;office.__v13Watched=true;officeObserver?.disconnect();officeObserver=new MutationObserver(()=>{if(matchActive()&&office.classList.contains("open"))closeMatchOverlays()});officeObserver.observe(office,{attributes:true,attributeFilter:["class"]})}
function raiseAudio(){const dock=document.getElementById("qfAudioDock");if(!dock)return;dock.style.setProperty("position","fixed","important");dock.style.setProperty("z-index","2147483000","important");dock.style.setProperty("pointer-events","auto","important");const toggle=document.getElementById("qfAudioToggle");if(toggle)toggle.style.setProperty("pointer-events","auto","important");const panel=document.getElementById("qfAudioPanel");if(panel)panel.style.setProperty("pointer-events","auto","important");state.audioRaised=true}
function scan(reason="manual"){ensureReadableStyle();updateVersionLabels();disableLegacy();raiseAudio();watchOffice();paginate();fit();const match=matchActive();document.body.classList.toggle("v13-match-active",match);if(match)guardMatchOverlays();if(match!==lastMatch){lastMatch=match;if(match)guardMatchOverlays();fit()}}
function updateServiceWorker(){if(!("serviceWorker" in navigator))return;navigator.serviceWorker.getRegistrations().then(rs=>Promise.all(rs.map(r=>r.update().catch(()=>null)))).then(()=>state.swUpdated=true).catch(()=>{});let reloaded=false;navigator.serviceWorker.addEventListener("controllerchange",()=>{if(reloaded)return;reloaded=true;const k="qf-v13-controller-reload";if(sessionStorage.getItem(k))return;sessionStorage.setItem(k,"1");location.reload()})}
function scheduleScan(){clearTimeout(observerTimer);observerTimer=setTimeout(()=>{state.mutations++;scan("mutation")},90)}
function boot(){document.body.classList.add("v13-runtime");ensureReadableStyle();disableLegacy();updateVersionLabels();paginate();fit();updateServiceWorker();raiseAudio();watchOffice();lastMatch=matchActive();const chairman=document.querySelector("#chairmanV7");if(chairman)new MutationObserver(m=>{if(m.some(r=>r.type==="attributes")){if(matchActive())closeMatchOverlays();scheduleScan()}}).observe(chairman,{subtree:true,attributes:true,attributeFilter:["class"]});new MutationObserver(m=>{if(m.some(r=>r.type==="childList")){watchOffice();scheduleScan()}}).observe(document.body,{subtree:true,childList:true});window.addEventListener("resize",()=>{fit();setTimeout(fit,180)},{passive:true});document.addEventListener("click",e=>{if(e.target.closest?.(".v7-nav button,.v9-office-nav,.v13-pager button,.v7-btn"))setTimeout(()=>{paginate();watchOffice();if(matchActive())guardMatchOverlays();fit()},25)},true);window.addEventListener("qf:v9-event",()=>{if(matchActive())closeMatchOverlays()})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
window.QF_V13={state:()=>({...state,screen:activeScreen()?.id||"",renderer:window.QF_MATCH_3D_V13?.state?.()||{},commentary:window.QF_COMMENTARY_V13?.state?.()||{}}),fit,paginate,scan,raiseAudio,guardMatchOverlays};
})();
