(()=>{"use strict";
const CROWD_URL="https://upload.wikimedia.org/wikipedia/commons/1/15/Festival_concert_people_crowd.ogg";
const CHEER_URL="https://upload.wikimedia.org/wikipedia/commons/e/e8/Hurray.ogg";
const REACT_URL="https://upload.wikimedia.org/wikipedia/commons/0/0f/Ohhh_ahhh.ogg";
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),pick=a=>a[Math.floor(Math.random()*a.length)];
const state={fitRuns:0,lastScale:1,autoFallback:false,fallbackReason:"",sampleFps:0,humanCrowd:false,humanCrowdError:"",v9Bypass:false,officeAutoClosed:0,commentaryMutations:0};
const recent=new Map();let perfSample=null,perfTimer=0,fitTimer=0,oldDrawSolo=null,oldDrawOnline=null,mediaUnlocked=false,crowdBed=null,goalCheer=null,chanceReact=null,speakWrapped=false;
function noRepeat(key,arr){const seen=recent.get(key)||[],pool=arr.filter(x=>!seen.includes(x)),v=pick(pool.length?pool:arr);recent.set(key,[...seen.slice(-4),v]);return v}
function matchActive(){return !!document.querySelector("#v7-match.active")||!!document.querySelector("#v7-online-match.active")}
function audioSettings(){return window.QF_AUDIO_V8?.getSettings?.()||{enabled:true,crowd:true,crowdVolume:.18,commentary:true}}
function commentarySettings(){return window.QF_COMMENTARY_V10?.getSettings?.()||{enabled:true,crowd:true,crowdLevel:.44}}
function closeBlockingOverlays(){if(!matchActive())return;document.querySelectorAll("#v9Office.open,.v9-office.open").forEach(el=>{el.classList.remove("open");state.officeAutoClosed++});document.querySelector(".v7-main")?.scrollTo?.(0,0)}
function setFit(screen,main,scale){scale=clamp(scale,.54,1);screen.style.zoom=String(scale);screen.classList.toggle("v12-fit-active",scale<.995);screen.dataset.v12Scale=scale.toFixed(3);state.lastScale=scale;state.fitRuns++}
function fitActiveScreen(){clearTimeout(fitTimer);fitTimer=setTimeout(()=>{if(innerWidth<761)return;const main=document.querySelector(".v7-main"),screen=document.querySelector(".v7-screen.active");if(!main||!screen)return;main.scrollTop=0;screen.style.zoom="1";requestAnimationFrame(()=>{const available=Math.max(1,main.clientHeight-2),needed=Math.max(1,screen.scrollHeight),s1=Math.min(1,available/needed);setFit(screen,main,s1);requestAnimationFrame(()=>{const needed2=Math.max(1,screen.scrollHeight*(parseFloat(screen.style.zoom)||1)),s2=Math.min(parseFloat(screen.style.zoom)||1,(parseFloat(screen.style.zoom)||1)*available/needed2);setFit(screen,main,s2);main.scrollTop=0})})},45)}
function advanceVisual(v,dt=.016){if(!v?.visual)return;const all=[...(v.visual.home||[]),...(v.visual.away||[])];for(const p of all){const fatigue=clamp((p.stamina||100)/100,.55,1);p.x+=(p.tx-p.x)*Math.min(.13*fatigue+dt*.8,.22);p.y+=(p.ty-p.y)*Math.min(.13*fatigue+dt*.8,.22)}const b=v.visual.ball;if(b){b.trail ||= [];b.trail.unshift([b.x,b.y]);b.trail=b.trail.slice(0,7);b.x+=(b.tx-b.x)*.20;b.y+=(b.ty-b.y)*.20}const f=v.visual.focus;if(f){f.x+=(f.targetX-f.x)*.08;f.y+=(f.targetY-f.y)*.08}v.visual.camera+=(0-(v.visual.camera||0))*.035}
function installV9Bypass(){const api=window.QF_MATCH_V9;if(!api||oldDrawSolo)return;oldDrawSolo=api.drawSolo?.bind(api);oldDrawOnline=api.drawOnline?.bind(api);if(oldDrawSolo)api.drawSolo=(c,match,club,ctx={})=>{if(document.getElementById("v11MatchCanvas3D")&&!document.body.classList.contains("v12-smooth-renderer")){const v=api.ensure(match,{...ctx,club,xi:club?.xi||[],playerMeta:ctx.playerMeta||window.QF_V7?.playerMeta});advanceVisual(v);state.v9Bypass=true;return true}return oldDrawSolo(c,match,club,ctx)};if(oldDrawOnline)api.drawOnline=(c,match,home,away)=>{if(document.getElementById("v11MatchCanvas3D")&&!document.body.classList.contains("v12-smooth-renderer")){const v=api.ensure(match,{homeClub:home,awayClub:away,xi:home?.xi||[],playerMeta:window.QF_V7?.playerMeta||{}});advanceVisual(v);state.v9Bypass=true;return true}return oldDrawOnline(c,match,home,away)} }
function ensureBadge(text="AKICI YAYIN"){const canvas=document.querySelector("#v7MatchCanvas,#v7OnlineCanvas");if(!canvas)return;let b=document.getElementById("v12RenderBadge");if(!b){b=document.createElement("div");b.id="v12RenderBadge";b.className="v12-render-badge";canvas.parentElement?.appendChild(b)}b.textContent=text}
function restore3DForNextMatch(){if(!state.autoFallback)return;try{window.QF_MATCH_3D_V11?.setSetting?.("enabled",true)}catch{}document.body.classList.remove("v12-smooth-renderer","v12-low-motion");document.getElementById("v12RenderBadge")?.remove();state.autoFallback=false;state.fallbackReason="";perfSample=null}
function fallback(reason){if(state.autoFallback)return;state.autoFallback=true;state.fallbackReason=reason;document.body.classList.add("v12-smooth-renderer","v12-low-motion","performance-lite");try{window.QF_MATCH_3D_V11?.setSetting?.("enabled",false)}catch{}try{window.QF_MATCH_3D_V10?.setSetting?.("enabled",false)}catch{}for(const id of["v11MatchCanvas3D","v11BroadcastHud","v10MatchCanvas3D","v10BroadcastHud"])document.getElementById(id)?.remove();for(const c of document.querySelectorAll("#v7MatchCanvas,#v7OnlineCanvas")){c.classList.remove("v10-fallback-hidden");c.style.visibility="visible";c.style.opacity="1";c.style.display="block"}ensureBadge(reason.includes("software")?"AKICI YAYIN • UYUMLU GPU":"AKICI YAYIN • FPS KORUMA")}
function performanceWatch(){clearInterval(perfTimer);perfTimer=setInterval(()=>{installV9Bypass();closeBlockingOverlays();syncHumanCrowd();if(!matchActive()){restore3DForNextMatch();return}const api=window.QF_MATCH_3D_V11,s=api?.state?.();if(!s?.active)return;if(s.software){fallback("software renderer");return}const now=performance.now();if(!perfSample){perfSample={frames:s.frames,t:now};return}const dt=(now-perfSample.t)/1000;if(dt<1.7)return;const fps=(s.frames-perfSample.frames)/dt;state.sampleFps=+fps.toFixed(1);perfSample={frames:s.frames,t:now};if(fps<45)fallback(`low fps ${fps.toFixed(1)}`)},700)}
function makeAudio(src,loop=false){const a=new Audio(src);a.preload="none";a.loop=loop;a.playsInline=true;return a}
function prepareHumanCrowd(){if(crowdBed)return;crowdBed=makeAudio(CROWD_URL,true);goalCheer=makeAudio(CHEER_URL,false);chanceReact=makeAudio(REACT_URL,false);crowdBed.volume=.001;goalCheer.volume=.62;chanceReact.volume=.36}
function unlockHumanCrowd(){prepareHumanCrowd();if(mediaUnlocked){syncHumanCrowd();return}crowdBed.preload="auto";goalCheer.preload="auto";chanceReact.preload="auto";const p=crowdBed.play();if(p?.then)p.then(()=>{mediaUnlocked=true;state.humanCrowd=true;syncHumanCrowd()}).catch(e=>{state.humanCrowdError=String(e?.name||e||"audio blocked")});else{mediaUnlocked=true;state.humanCrowd=true;syncHumanCrowd()}}
function syncHumanCrowd(){if(!crowdBed||!mediaUnlocked)return;const a=audioSettings(),c=commentarySettings(),on=matchActive()&&a.enabled!==false&&a.crowd!==false&&c.crowd!==false;const level=clamp((a.crowdVolume??.18)*.72+(c.crowdLevel??.44)*.18,.08,.30);crowdBed.volume=on?level:.001;if(crowdBed.paused)crowdBed.play().catch(()=>{})}
function reaction(type){if(!mediaUnlocked)return;const a=audioSettings();if(a.enabled===false||a.crowd===false)return;const src=type==="goal"?goalCheer:chanceReact;if(!src)return;try{src.pause();src.currentTime=0;src.volume=type==="goal"?.68:.38;src.play().catch(()=>{})}catch{}}
function mutateCommentary(d){if(!d?.phase)return;const actor=d.actorName||"oyuncu",lane=d.lane||"center";if(d.phase==="build"){const map={left:[`${actor} sol çizgiden hızlanıyor, önünde boş alan var!`,`${actor} sol kanatta topu aldı, şimdi rakibinin üstüne gidiyor!`,`${actor} soldan geliyor, tempo bir anda yükseldi!`],right:[`${actor} sağ çizgiden bindiriyor, önünde boşluk var!`,`${actor} sağ kanatta hızlandı, savunmayı geriye itiyor!`,`${actor} sağdan geliyor, şimdi tehlike büyüyor!`],center:[`${actor} merkezden hızla geliyor, savunmanın arasına girdi!`,`${actor} yüzünü kaleye döndü, şimdi boşluğu görüyor!`,`${actor} orta alandan taşıyor, rakip savunma geri kaçıyor!`]};d.text=noRepeat(`build-${lane}`,map[lane]||map.center);d.excitement=Math.max(+d.excitement||0,58)}
 else if(d.phase==="delivery"){const arr=lane==="center"?[`${actor} başını kaldırdı... savunma arasına bıraktı!`,`${actor} ince pası gönderdi, ceza sahasında hareketlilik var!`,`${actor} tek pasla savunmanın dengesini bozdu!`]:[`${actor} başını kaldırdı... ORTA GELİYOR!`,`${actor} çizgiye indi, ortasını yaptı!`,`${actor} ceza alanına çok tehlikeli kesti!`,`${actor} içeri çevirdi, savunma alarmda!`];d.text=noRepeat(`delivery-${lane}`,arr);d.excitement=Math.max(+d.excitement||0,72)}
 else if(d.phase==="finish"){const arr=[`${actor} yükseldi... VURDU!`,`${actor} gelişine dokundu... VURUŞ GELDİ!`,`${actor} topun gelişine vuruyor!`,`${actor} ceza sahasında kontrol etti... ŞUT!`,`${actor} kafayı vurdu!`];d.text=noRepeat("finish",arr);d.excitement=Math.max(+d.excitement||0,86)}
 else if(d.phase==="result"){if(d.type==="goal"){d.text=noRepeat("goal",[`GOOOOOOOL! GOL GOL GOL! ${actor}! Tribünler ayağa kalktı!`,`GOOOOOOOL! ${actor}! Müthiş bir gol, stadyum yıkılıyor!`,`GOL! GOL! GOL! ${actor} fileleri buldu! Ne hücum ama!`,`GOOOOOOOL! ${actor}! İşte futbol, işte bitiriş!`]);d.excitement=100;d.importance=100;reaction("goal")}else if(d.type==="post"){d.text=noRepeat("post",[`DİREK! İnanılmaz, top direkten geri geldi!`,`VURDU... DİREK! Gol santimlerle kaçtı!`,`DİREKTEN DÖNDÜ! Tribünler bir anda ayağa kalktı!`]);d.excitement=Math.max(+d.excitement||0,92);reaction("post")}else if(d.type==="save"){d.text=noRepeat("save",[`VURDU! KALECİ ÇIKARDI! Müthiş kurtarış!`,`Kaleci uzandı... İNANILMAZ KURTARIŞ!`,`Net gol pozisyonu, kaleci son anda çıkardı!`]);d.excitement=Math.max(+d.excitement||0,88);reaction("save")}else if(d.type==="miss"){d.text=noRepeat("miss",[`Vuruş dışarıda! Çok büyük fırsat kaçtı!`,`Ahhh! Top az farkla dışarı gitti!`,`VURDU... olmadı! Tribünlerden büyük bir ah sesi!`]);d.excitement=Math.max(+d.excitement||0,76);reaction("miss")}}state.commentaryMutations++}
function wrapSpeech(){if(speakWrapped||!window.speechSynthesis)return;try{const original=window.speechSynthesis.speak.bind(window.speechSynthesis);window.speechSynthesis.speak=(u)=>{if(matchActive()&&/^tr([-_]|$)/i.test(u.lang||"tr-TR")){const t=String(u.text||"");if(/GO+L|GOL!|GOL GOL/i.test(t)){u.rate=.92;u.pitch=1.08;u.volume=1}else if(/VURDU|ŞUT|ORTA GELİYOR|tehlike/i.test(t)){u.rate=1.12;u.pitch=1.01;u.volume=1}else{u.rate=Math.max(u.rate||1,1.02);u.volume=Math.max(u.volume||.9,.94)}}return original(u)};speakWrapped=true}catch{}}
function setBroadcastDefaults(){const c=window.QF_COMMENTARY_V10;if(!c)return false;try{if(!localStorage.getItem("qf-v12-broadcast-defaults")){c.setSetting?.("style","excited");c.setSetting?.("rate",1.04);c.setSetting?.("pitch",.98);c.setSetting?.("importantOnly",true);c.setSetting?.("chantWords",true);c.setSetting?.("crowdLevel",.50);localStorage.setItem("qf-v12-broadcast-defaults","1")}return true}catch{return false}}
window.addEventListener("qf:v11-commentary",e=>mutateCommentary(e.detail||{}));
document.addEventListener("pointerdown",unlockHumanCrowd,true);
document.addEventListener("keydown",unlockHumanCrowd,true);
window.addEventListener("resize",fitActiveScreen);
document.addEventListener("click",e=>{if(e.target.closest?.(".v7-nav button,.v9-office-nav,.v7-btn"))fitActiveScreen()},true);
function boot(){document.body.classList.add("v12-runtime");prepareHumanCrowd();wrapSpeech();installV9Bypass();fitActiveScreen();performanceWatch();let tries=0;const t=setInterval(()=>{tries++;wrapSpeech();installV9Bypass();setBroadcastDefaults();fitActiveScreen();if(tries>20)clearInterval(t)},350);const main=document.querySelector(".v7-main");if(main)new MutationObserver(rs=>{if(rs.some(r=>r.target?.classList?.contains?.("v7-screen")))fitActiveScreen()}).observe(main,{subtree:true,attributes:true,attributeFilter:["class"]})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
window.QF_V12={state:()=>({...state,matchActive:matchActive(),mediaUnlocked}),fit:fitActiveScreen,fallback:()=>fallback("manual"),restore:restore3DForNextMatch,unlockAudio:unlockHumanCrowd};
})();
