import { chromium } from 'playwright-core';
import fs from 'node:fs';
const bins=['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'];
const executablePath=bins.find(p=>fs.existsSync(p));if(!executablePath)throw new Error('Chrome missing');
const base=process.env.QF_TEST_BASE||'http://127.0.0.1:4189/';
const out='qa-artifacts-v15';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required','--use-angle=swiftshader','--enable-webgl','--ignore-gpu-blocklist']});
const ctx=await browser.newContext({viewport:{width:1366,height:768}}),p=await ctx.newPage(),errors=[];
p.on('pageerror',e=>errors.push(String(e)));p.on('console',m=>{if(m.type()==='error'&&!/status of (401|403|404)|Failed to load resource/i.test(m.text()))errors.push(m.text())});
const fail=m=>{throw new Error(m)},log=(...x)=>console.log('[V15 QA]',...x);
await p.addInitScript(()=>{if(!sessionStorage.getItem('qf-v15-seeded')){localStorage.clear();localStorage.setItem('qf-v5-profile',JSON.stringify({username:'V15QA',profileKey:'v15qa'}));localStorage.setItem('qf-v15-simulator','3d');sessionStorage.setItem('qf-v15-seeded','1')}});
try{
 await p.goto(base,{waitUntil:'domcontentloaded'});await p.waitForSelector('#v7Onboard',{timeout:15000});await p.locator('#v7ClubName').fill('V15 QA FC');await p.locator('#v7ClubShort').fill('V15');await p.locator('#v7CreateClub').click();await p.waitForSelector('#v7-home.active',{timeout:8000});
 await p.locator('#v7Arcade').click();await p.waitForSelector('#homeScreen.active',{timeout:8000});await p.locator('#soloStartBtn').click();await p.waitForSelector('#gameScreen.active',{timeout:10000});await p.waitForTimeout(500);
 const quiz=await p.evaluate(()=>{const s=document.querySelector('#gameScreen.active'),r=s?.getBoundingClientRect(),layout=document.querySelector('#gameScreen .v5-game-layout')?.getBoundingClientRect();return{scrollY,docH:document.documentElement.scrollHeight,innerH:window.innerHeight,screen:r?{top:r.top,bottom:r.bottom,height:r.height}:null,layout:layout?{top:layout.top,bottom:layout.bottom,height:layout.height}:null,bodyOverflow:getComputedStyle(document.body).overflow}});log('quiz',quiz);if(quiz.scrollY!==0)fail(`Quiz page scrolled: ${quiz.scrollY}`);if(quiz.docH>quiz.innerH+6)fail(`Quiz document overflows ${quiz.docH}>${quiz.innerH}`);if(quiz.screen&&quiz.screen.bottom>quiz.innerH+4)fail(`Quiz screen overflows viewport: ${JSON.stringify(quiz.screen)}`);await p.screenshot({path:`${out}/quiz-1366x768.png`,fullPage:false});
 await p.reload({waitUntil:'domcontentloaded'});await p.waitForSelector('#v7-home.active',{timeout:10000});await p.waitForFunction(()=>!!window.QF_BROADCAST_V15&&!!window.QF_COMMENTARY_V15&&!!window.QF_MATCH_3D_V13,{timeout:10000});
 await p.mouse.click(500,300);await p.evaluate(()=>window.QF_AUDIO_V13?.unlock?.());await p.evaluate(()=>window.QF_V7_TEST.startFast());await p.waitForSelector('#v7-match.active',{timeout:8000});await p.waitForSelector('#v15SimulatorSwitch',{timeout:8000});await p.waitForFunction(()=>window.QF_MATCH_3D_V13?.state?.().players===22,{timeout:10000});
 const initial=await p.evaluate(()=>({r:window.QF_MATCH_3D_V13.state(),b:window.QF_BROADCAST_V15.state()}));log('3d initial',initial);if(!initial.r.active||initial.r.players!==22)fail(`3D not active: ${JSON.stringify(initial)}`);if(initial.r.targetFps!==60)fail(`3D target is not 60Hz: ${initial.r.targetFps}`);
 await p.locator('#v15SimulatorSwitch [data-v15-mode="2d"]').click();await p.waitForTimeout(260);const two=await p.evaluate(()=>({mode:window.QF_BROADCAST_V15.state().mode,r:window.QF_MATCH_3D_V13.state(),src:getComputedStyle(document.getElementById('v7MatchCanvas')).visibility}));log('2d',two);if(two.mode!=='2d'||two.r.active||two.src==='hidden')fail(`2D switch failed: ${JSON.stringify(two)}`);
 await p.locator('#v15SimulatorSwitch [data-v15-mode="3d"]').click();await p.waitForFunction(()=>window.QF_MATCH_3D_V13?.state?.().active,{timeout:6000});const three=await p.evaluate(()=>({mode:window.QF_BROADCAST_V15.state().mode,r:window.QF_MATCH_3D_V13.state(),src:getComputedStyle(document.getElementById('v7MatchCanvas')).visibility}));log('3d restored',three);if(three.mode!=='3d'||!three.r.active||three.src!=='hidden')fail(`3D restore failed: ${JSON.stringify(three)}`);
 const smooth=await p.evaluate(()=>new Promise(resolve=>{const vals=[],times=[];let i=0;window.QF_BROADCAST_V15.ambientNow();function f(t){const m=window.QF_V7_TEST.match(),x=m?.v9?.visual?.home?.[6]?.x;vals.push(typeof x==='number'?x.toFixed(5):'x');times.push(t);if(++i>=45){const gaps=times.slice(1).map((v,j)=>v-times[j]).sort((a,b)=>a-b),distinct=new Set(vals).size;resolve({distinct,p50:gaps[Math.floor(gaps.length*.5)]||0,p95:gaps[Math.floor(gaps.length*.95)]||0,max:gaps.at(-1)||0})}else requestAnimationFrame(f)}requestAnimationFrame(f)}));log('smooth',smooth);if(smooth.distinct<25)fail(`player movement is step-like: ${JSON.stringify(smooth)}`);
 const latency=await p.evaluate(()=>new Promise(resolve=>{window.QF_COMMENTARY_V15.resetDedupe();const old=document.getElementById('qfCommentaryCaption');if(old)old.textContent='';const start=performance.now();window.dispatchEvent(new CustomEvent('qf:v9-event',{detail:{type:'goal',side:'home',minute:73,text:"73' GOL! David Beckham bitirdi."}}));const iv=setInterval(()=>{const el=document.getElementById('qfCommentaryCaption');if(el?.textContent&&/GO+L/i.test(el.textContent)){clearInterval(iv);resolve({ms:performance.now()-start,text:el.textContent,state:window.QF_COMMENTARY_V15.state()})}},8);setTimeout(()=>{clearInterval(iv);resolve({ms:9999,text:'',state:window.QF_COMMENTARY_V15.state()})},900)}));log('commentary latency',latency);if(latency.ms>220)fail(`commentary/caption is late: ${latency.ms}ms`);if(!/GO+L/i.test(latency.text))fail(`instant goal commentary missing: ${latency.text}`);if(latency.state.rate>.72)fail(`commentary too fast: ${latency.state.rate}`);
 const before=latency.state;await p.evaluate(()=>{const d={type:'goal',side:'home',minute:73,text:"73' GOL! David Beckham bitirdi."};window.dispatchEvent(new CustomEvent('qf:v9-event',{detail:d}));window.dispatchEvent(new CustomEvent('qf:v9-event',{detail:d}))});await p.waitForTimeout(180);const after=await p.evaluate(()=>window.QF_COMMENTARY_V15.state());log('dedupe',after);if(after.deduped<=before.deduped)fail('duplicate goal events were not suppressed');
 const controls=await p.evaluate(()=>{const e=document.getElementById('v15SimulatorSwitch');return{exists:!!e,buttons:e?.querySelectorAll('button').length||0,text:e?.textContent||'',left:e?.getBoundingClientRect().left||0,top:e?.getBoundingClientRect().top||0}});if(!controls.exists||controls.buttons!==2||!controls.text.includes('3D')||!controls.text.includes('2D'))fail(`simulator control missing: ${JSON.stringify(controls)}`);
 await p.screenshot({path:`${out}/match-3d-1366x768.png`,fullPage:false});await p.setViewportSize({width:1920,height:1080});await p.waitForTimeout(350);await p.screenshot({path:`${out}/match-3d-1920x1080.png`,fullPage:false});
 if(errors.length)fail(`browser errors: ${errors.slice(0,6).join(' | ')}`);
 console.log('V15 E2E PASS',JSON.stringify({quiz,smooth,latency:{ms:+latency.ms.toFixed(1),text:latency.text},renderer:three.r,broadcast:initial.b,deduped:after.deduped}));
}finally{await ctx.close();await browser.close()}
