import{chromium}from'playwright-core';import fs from'node:fs';
const bins=['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'],executablePath=bins.find(fs.existsSync);if(!executablePath)throw new Error('Chrome missing');
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage']});const ctx=await browser.newContext({viewport:{width:1440,height:900}}),page=await ctx.newPage(),base=process.env.QF_TEST_BASE||'http://127.0.0.1:4178/';const log=x=>console.log('[V6 E2E]',x);
try{
 await page.addInitScript(()=>{localStorage.setItem('qf-v5-profile',JSON.stringify({profileKey:'qa-v6-browser',username:'V6BrowserQA',rating:1000,xp:0,level:1}));localStorage.removeItem('qf-v6-club');localStorage.removeItem('qf-v6-club-history');localStorage.removeItem('qf-v6-tournament')});
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.QFV6&&document.body.classList.contains('v6-ui'),null,{timeout:12000});
 const shell=await page.evaluate(()=>({hub:document.querySelector('#hubScreen')?.classList.contains('active'),sky:getComputedStyle(document.querySelector('.sky')).display,blur:getComputedStyle(document.querySelector('.glass')).backdropFilter,club:QFV6.getClub()}));
 if(!shell.hub)throw new Error('V6 hub not default screen');if(shell.sky!=='none')throw new Error('heavy animated background still active');if(shell.blur&&!['none',''].includes(shell.blur))throw new Error('backdrop blur still active');if(!shell.club.manager_id||shell.club.squad.length<11)throw new Error('club seed incomplete');log('lightweight V6 shell + club seed passed');
 const ids=['clubScreen','squadScreen','tacticsScreen','competitionScreen','marketScreen','hubScreen','homeScreen','hubScreen'];const navTimes=[];for(const id of ids){const t=Date.now();await page.locator(`[data-v6-screen="${id}"]`).click();await page.waitForFunction(id=>document.getElementById(id)?.classList.contains('active'),id);navTimes.push(Date.now()-t)}const navAvg=navTimes.reduce((a,b)=>a+b,0)/navTimes.length;if(navAvg>180)throw new Error(`navigation too slow avg=${navAvg}`);log(`navigation average ${navAvg.toFixed(1)}ms`);
 await page.locator('[data-v6-screen="homeScreen"]').click();const frames=await page.evaluate(async()=>{const a=[];let last=performance.now();for(let i=0;i<70;i++){window.scrollTo(0,(document.body.scrollHeight-innerHeight)*(i%35)/34);await new Promise(r=>requestAnimationFrame(t=>{a.push(t-last);last=t;r()}))}window.scrollTo(0,0);return a.slice(5)});const avg=frames.reduce((a,b)=>a+b,0)/frames.length,p95=[...frames].sort((a,b)=>a-b)[Math.floor(frames.length*.95)];if(avg>45||p95>100)throw new Error(`scroll frame budget failed avg=${avg} p95=${p95}`);log(`scroll frame avg ${avg.toFixed(1)}ms p95 ${p95.toFixed(1)}ms`);
 await page.evaluate(()=>{QFV6.setFast(true);QFV6.startMatch()});await page.waitForFunction(()=>document.querySelector('#clubMatchScreen')?.classList.contains('active')&&document.querySelector('#v6MatchCanvas')?.width>0,null,{timeout:10000});await page.waitForFunction(()=>document.querySelectorAll('#v6QuizBox .v6-answer').length===4);const before=await page.evaluate(()=>QFV6.getMatch());if(before.momentum!==0)throw new Error('match momentum should start at zero');
 await page.evaluate(()=>QFV6.answerCorrect());await page.waitForFunction(()=>QFV6.getMatch()?.momentum>0,null,{timeout:4000});const raised=await page.evaluate(()=>QFV6.getMatch());if(raised.correct<1||raised.momentum<=0)throw new Error('correct answer did not raise momentum');log(`quiz momentum raised to ${raised.momentum.toFixed(1)}`);
 await page.evaluate(()=>QFV6.forceGoal());await page.waitForFunction(()=>QFV6.getMatch()?.home>=1&&QFV6.getMatch()?.momentum===0,null,{timeout:3000});log('goal reset momentum to zero');
 await page.evaluate(()=>QFV6.finish());await page.waitForFunction(()=>document.querySelector('#postMatchScreen')?.classList.contains('active'),null,{timeout:4000});const saved=await page.evaluate(()=>({history:JSON.parse(localStorage.getItem('qf-v6-club-history')||'[]'),club:JSON.parse(localStorage.getItem('qf-v6-club')||'{}')}));if(!saved.history.length)throw new Error('club match history not saved');if(!Object.keys(saved.club.player_stats||{}).length)throw new Error('player match ratings not persisted');if(saved.history[0].ratings?.length<11)throw new Error('11 player ratings missing');log('match history + player ratings persisted');
 await page.evaluate(()=>QFV6.go('competitionScreen'));await page.waitForFunction(()=>document.querySelectorAll('#v6Competitions [data-comp]').length>=4);await page.evaluate(()=>QFV6.go('marketScreen'));await page.waitForFunction(()=>document.querySelectorAll('#v6Market [data-buy]').length>0);log('competition and transfer panels rendered');
 console.log('V6 E2E PASS: performance shell, navigation, scroll frames, club persistence, live canvas match, quiz momentum, goal reset, player ratings, tournaments and market.');
}finally{await ctx.close().catch(()=>{});await browser.close()}
