import {chromium} from 'playwright-core';import fs from 'node:fs';
const candidates=['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'],executablePath=candidates.find(p=>fs.existsSync(p));if(!executablePath)throw new Error('Chrome/Chromium executable not found');
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required']});
const hostCtx=await browser.newContext({viewport:{width:1440,height:980}}),guestCtx=await browser.newContext({viewport:{width:1440,height:980}}),soloCtx=await browser.newContext({viewport:{width:1280,height:900}});const host=await hostCtx.newPage(),guest=await guestCtx.newPage(),solo=await soloCtx.newPage();const base='http://127.0.0.1:4173/';
const log=m=>console.log('[V5 E2E]',m),active=(p,id)=>p.waitForFunction(id=>document.getElementById(id)?.classList.contains('active'),id,{timeout:20000});
async function saveName(p,n){await p.locator('#profileNameInput').fill(n);await p.locator('#saveProfileBtn').click();await p.waitForFunction(n=>document.querySelector('#profileNameText')?.textContent===n,n)}
async function snapshot(p){return p.evaluate(()=>({round:document.querySelector('#roundProgress')?.textContent?.trim(),a:document.querySelector('#teamAName')?.textContent?.trim(),b:document.querySelector('#teamBName')?.textContent?.trim(),type:document.querySelector('#questionTypeChip')?.textContent?.trim(),answers:[...document.querySelectorAll('#answerGrid .answer-name')].map(x=>x.textContent.trim())}))}
try{
 await Promise.all([host.goto(base,{waitUntil:'domcontentloaded'}),guest.goto(base,{waitUntil:'domcontentloaded'}),solo.goto(base,{waitUntil:'domcontentloaded'})]);
 await saveName(host,'HostQA');await host.reload({waitUntil:'domcontentloaded'});await host.waitForFunction(()=>document.querySelector('#profileNameInput')?.value==='HostQA');log('username persisted across reload');
 await saveName(guest,'GuestQA');await host.locator('#createRoomBtn').click();await active(host,'lobbyScreen');const room=(await host.locator('#roomCodeText').textContent()).trim();if(!room||room.includes('-'))throw new Error('room code missing');
 await guest.locator('#joinCode').fill(room);await guest.locator('#joinRoomBtn').click();await active(guest,'lobbyScreen');await Promise.all([host.waitForFunction(()=>document.querySelectorAll('#lobbyPlayers .lobby-player').length===2),guest.waitForFunction(()=>document.querySelectorAll('#lobbyPlayers .lobby-player').length===2)]);log(`two-client lobby synchronized: ${room}`);
 await host.locator('#modeSelect').selectOption('blitz3');await host.locator('#choiceCountSelect').selectOption('4');await guest.waitForFunction(()=>document.querySelector('#formatPreview')?.textContent?.includes('3 dakika')&&document.querySelector('#formatPreview')?.textContent?.includes('4 seçenek'),{timeout:8000});
 await host.locator('#startGameBtn').click();await Promise.all([active(host,'gameScreen'),active(guest,'gameScreen')]);await Promise.all([host.waitForFunction(()=>document.querySelectorAll('#answerGrid .answer-card').length===4),guest.waitForFunction(()=>document.querySelectorAll('#answerGrid .answer-card').length===4)]);const timer=await guest.locator('#timerText').textContent();if(timer==='∞')throw new Error('timed Blitz mode did not start timer');let hs=await snapshot(host),gs=await snapshot(guest);if(JSON.stringify(hs)!==JSON.stringify(gs))throw new Error('clients diverged on initial round');log('Blitz 3 timer + 4 options synchronized');
 const correct=await guest.evaluate(()=>{const D=window.QF_DATA,a=document.querySelector('#teamAName').textContent.trim(),b=document.querySelector('#teamBName').textContent.trim(),A=Object.entries(D.teams).find(([,t])=>t.short===a)?.[0],B=Object.entries(D.teams).find(([,t])=>t.short===b)?.[0],visible=[...document.querySelectorAll('#answerGrid .answer-name')].map(x=>x.textContent.trim());return Object.values(D.players).find(p=>visible.includes(p.name)&&p.clubs.includes(A)&&p.clubs.includes(B))?.name||''});if(!correct)throw new Error('could not derive correct player');const before=hs.round;await guest.locator('#answerGrid .answer-card').filter({hasText:correct}).click();await Promise.all([host.waitForFunction(r=>document.querySelector('#roundProgress')?.textContent?.trim()!==r,before,{timeout:6000}),guest.waitForFunction(r=>document.querySelector('#roundProgress')?.textContent?.trim()!==r,before,{timeout:6000})]);const gscore=await guest.evaluate(()=>[...document.querySelectorAll('#scorePlayers .player-row')].find(x=>x.textContent.includes('GuestQA'))?.querySelector('strong')?.textContent?.trim());if(gscore!=='1')throw new Error(`guest score expected 1 got ${gscore}`);log('first correct scored and auto-advanced');
 hs=await snapshot(host);const wrongs=await host.evaluate(()=>{const D=window.QF_DATA,a=document.querySelector('#teamAName').textContent.trim(),b=document.querySelector('#teamBName').textContent.trim(),A=Object.entries(D.teams).find(([,t])=>t.short===a)?.[0],B=Object.entries(D.teams).find(([,t])=>t.short===b)?.[0],cards=[...document.querySelectorAll('#answerGrid .answer-card')],c=Object.values(D.players).find(p=>cards.some(x=>x.textContent.includes(p.name))&&p.clubs.includes(A)&&p.clubs.includes(B))?.name;return cards.map(x=>x.querySelector('.answer-name')?.textContent?.trim()).filter(x=>x&&x!==c)});if(wrongs.length<2)throw new Error('not enough wrong answers');const wrongRound=hs.round;await host.locator('#answerGrid .answer-card').filter({hasText:wrongs[0]}).click();await guest.locator('#answerGrid .answer-card').filter({hasText:wrongs[1]}).click();await Promise.all([host.waitForFunction(r=>document.querySelector('#roundProgress')?.textContent?.trim()!==r,wrongRound,{timeout:6000}),guest.waitForFunction(r=>document.querySelector('#roundProgress')?.textContent?.trim()!==r,wrongRound,{timeout:6000})]);log('all-wrong auto-next synchronized');
 await host.waitForFunction(()=>[...document.querySelectorAll('.team-logo img,.player-photo img')].filter(i=>i.complete&&i.naturalWidth>0).length>=6,{timeout:12000});const overflow=await host.evaluate(()=>[...document.querySelectorAll('.team-logo img')].some(img=>{const a=img.getBoundingClientRect(),b=img.parentElement.getBoundingClientRect();return a.left<b.left-1||a.right>b.right+1||a.top<b.top-1||a.bottom>b.bottom+1}));if(overflow)throw new Error('team logo overflow');log('images and logo fit passed');
 const cloud=await host.evaluate(async()=>{await window.QFCloud.ready;const p={profile_key:'qa-e2e-fixed',username:'QA_E2E',rating:1000,xp:0,level:1,games:0,wins:0,losses:0,draws:0,correct:0,wrong:0,best_streak:0,timed_best:0,solo_best:0,ranked_wins:0,chill_games:0,manager_correct:0,badges:[]};await window.QFCloud.ensureProfile(p);await window.QFCloud.leaderboard(5);return{status:window.QFCloud.status,error:window.QFCloud.lastError}});if(cloud.status!=='online')throw new Error(`global cloud not online: ${JSON.stringify(cloud)}`);log('Base44 global profile + leaderboard cloud online');
 await saveName(solo,'SoloQA');await solo.locator('.mode-tab[data-group="solo"]').click();await solo.locator('.mode-card[data-mode="managerSolo"]').click();await solo.locator('#soloStartBtn').click();await active(solo,'gameScreen');await solo.waitForFunction(()=>document.querySelector('#questionTypeChip')?.textContent?.includes('TEKNİK'));const managerAnswers=await solo.locator('#answerGrid .answer-card').count();if(managerAnswers!==6)throw new Error(`manager solo expected 6 answers got ${managerAnswers}`);await solo.waitForFunction(()=>[...document.querySelectorAll('.player-photo img')].some(i=>i.complete&&i.naturalWidth>0),{timeout:12000});log('single-player manager mode started with manager imagery');
 await solo.evaluate(()=>window.QFTest.setEndsIn(600));await active(solo,'finalScreen');log('timed game finished by clock without exhausting card deck');
 const qf=await solo.evaluate(()=>window.QFTest.profile());if(qf.username!=='SoloQA')throw new Error('solo profile lost');console.log('V5 E2E PASS: persistent username, 2-client sync, timed Blitz, first-correct, all-wrong, image fit, global leaderboard cloud, solo manager mode and timer-based finish.');
}finally{await hostCtx.close();await guestCtx.close();await soloCtx.close();await browser.close()}
