import{chromium}from'playwright-core';import fs from'node:fs';
const bins=['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'],executablePath=bins.find(fs.existsSync);if(!executablePath)throw new Error('Chrome missing');
const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required']});const ctx=await browser.newContext({viewport:{width:1440,height:900}}),page=await ctx.newPage(),base=process.env.QF_TEST_BASE||'http://127.0.0.1:4180/';const log=x=>console.log('[V8 AUDIO E2E]',x);
try{
 await page.addInitScript(()=>{localStorage.setItem('qf-v5-profile',JSON.stringify({profileKey:'qa-v8-audio',username:'AudioQA',rating:1000,xp:0,level:1}));if(!sessionStorage.getItem('qf-v8-qa-seeded')){localStorage.removeItem('qf-v8-audio');localStorage.removeItem('qf-v7-chairman');sessionStorage.setItem('qf-v8-qa-seeded','1')}});
 await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.QF_AUDIO_V8&&window.QF_V7_TEST,null,{timeout:12000});await page.mouse.click(80,80);await page.waitForFunction(()=>window.QF_AUDIO_V8.state().unlocked===true,null,{timeout:4000});log('audio context unlocked by user gesture');
 const defaults=await page.evaluate(()=>QF_AUDIO_V8.getSettings());if(!defaults.commentary||!defaults.effects||!defaults.crowd||!defaults.captions)throw new Error('default audio channels not enabled');
 await page.evaluate(()=>QF_V7_TEST.startFast());await page.waitForFunction(()=>QF_AUDIO_V8.state().active&&document.querySelector('#qfAudioDock'),null,{timeout:5000});await page.evaluate(()=>document.querySelector('#v7Onboard')?.remove());const dock=await page.locator('#qfAudioDock').isVisible();if(!dock)throw new Error('audio controls not visible during match');log('match audio dock mounted');
 await page.evaluate(()=>QF_V7_TEST.answerCorrect());await page.waitForFunction(()=>QF_AUDIO_V8.state().lastType==='correct',null,{timeout:4000});const correct=await page.evaluate(()=>QF_AUDIO_V8.state());if(correct.sfx<1||!correct.lastCaption)throw new Error('correct-answer audio/caption missing');log('correct-answer cue + commentator caption detected');
 for(const type of ['miss','save','post','goal_for','goal_against','half','late']){const r=await page.evaluate(t=>{const before=QF_AUDIO_V8.state().sfx;QF_AUDIO_V8.testEvent(t);return{before,after:QF_AUDIO_V8.state()}},type);if(r.after.lastType!==type)throw new Error(`event ${type} not dispatched`);if(type!=='late'&&r.after.sfx<=r.before)throw new Error(`event ${type} produced no SFX`)}log('miss/save/post/goal/conceded/half/late event palette passed');
 await page.locator('#qfAudioToggle').click();await page.waitForFunction(()=>!document.querySelector('#qfAudioPanel').hidden);await page.locator('[data-audio-range="master"]').fill('0.55');await page.locator('[data-audio-bool="crowd"]').uncheck();const set=await page.evaluate(()=>QF_AUDIO_V8.getSettings());if(Math.abs(set.master-.55)>.01||set.crowd!==false)throw new Error('audio controls did not update settings');log('separate master/crowd controls passed');
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.QF_AUDIO_V8);const persisted=await page.evaluate(()=>QF_AUDIO_V8.getSettings());if(Math.abs(persisted.master-.55)>.01||persisted.crowd!==false)throw new Error('audio settings did not persist');log('audio settings persisted across reload');
 console.log('V8 AUDIO E2E PASS: user-gesture unlock, Turkish commentator engine, procedural SFX, captions, match integration, controls and persistence.');
}finally{await ctx.close().catch(()=>{});await browser.close()}
