import {chromium} from 'playwright-core';import fs from 'node:fs';
const candidates=['/usr/bin/google-chrome','/usr/bin/google-chrome-stable','/usr/bin/chromium','/usr/bin/chromium-browser'],executablePath=candidates.find(p=>fs.existsSync(p));if(!executablePath)throw new Error('Chrome/Chromium executable not found');const base=process.env.QF_TEST_BASE||'http://127.0.0.1:4179/';const browser=await chromium.launch({headless:true,executablePath,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=no-user-gesture-required']});
const ctx1=await browser.newContext({viewport:{width:1440,height:960}}),ctx2=await browser.newContext({viewport:{width:1366,height:900}}),p1=await ctx1.newPage(),p2=await ctx2.newPage();const log=m=>console.log('[V7 E2E]',m);
async function createClub(p,name,short){await p.goto(base,{waitUntil:'domcontentloaded'});await p.waitForSelector('#v7Onboard',{timeout:15000});await p.locator('#v7ClubName').fill(name);await p.locator('#v7ClubShort').fill(short);await p.locator('#v7CreateClub').click();await p.waitForSelector('#v7-home.active',{timeout:10000})}
try{
 await createClub(p1,'QA Chairman FC','QAC');let s=await p1.evaluate(()=>window.QF_V7_TEST.state());if(!s.created||s.squad.length!==18)throw new Error('club creation/starter squad failed');if(Math.abs(s.budgetM-120)>.01)throw new Error(`starting budget expected 120 got ${s.budgetM}`);log('club creation + €120M starting budget passed');
 const xi=await p1.evaluate(()=>window.QF_V7_TEST.autoPick());if(xi.length!==11)throw new Error('manager did not auto-pick 11');const req=await p1.evaluate(()=>window.QF_V7_TEST.requests());if(!req.length)throw new Error('manager generated no transfer request');const before=await p1.evaluate(()=>window.QF_V7_TEST.state());const bought=await p1.evaluate(()=>window.QF_V7_TEST.approveFirst());if(!bought)throw new Error('manager request approval failed');const after=await p1.evaluate(()=>window.QF_V7_TEST.state());if(after.squad.length!==before.squad.length+1||after.budgetM>=before.budgetM)throw new Error('transfer did not update squad/budget');log('manager XI + transfer request + chairman approval passed');
 const nav=await p1.evaluate(async()=>{const names=['squad','manager','market','season','home'];const t=[];for(const n of names){const a=performance.now();document.querySelector(`[data-v7="${n}"]`).click();await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));t.push(performance.now()-a)}return t.reduce((x,y)=>x+y,0)/t.length});if(nav>180)throw new Error(`V7 navigation too slow ${nav.toFixed(1)}ms`);log(`simple chairman navigation avg ${nav.toFixed(1)}ms`);
 await p1.evaluate(()=>window.QF_V7_TEST.startFast());await p1.waitForSelector('#v7-match.active',{timeout:6000});await p1.waitForSelector('[data-qanswer]',{timeout:6000});await p1.evaluate(()=>window.QF_V7_TEST.answerCorrect());let m=await p1.evaluate(()=>window.QF_V7_TEST.match());if(!(m.momentum>0&&m.correct===1))throw new Error('quiz momentum did not rise');const raised=m.momentum;await p1.evaluate(()=>window.QF_V7_TEST.forceGoal());m=await p1.evaluate(()=>window.QF_V7_TEST.match());if(m.momentum!==0)throw new Error('goal did not reset momentum');log(`solo 2-minute engine quiz momentum ${raised.toFixed(1)} -> 0 after goal`);await p1.evaluate(()=>window.QF_V7_TEST.finishNow());await p1.waitForSelector('#v7-post.active',{timeout:5000});log('fast 90-minute simulation finishes without waiting 120s in QA');
 await createClub(p2,'QA Rival United','QAR');await p1.evaluate(()=>window.QF_V7_CORE.go('online'));await p1.locator('#v7OnlineHost').click();const room=await p1.waitForFunction(()=>window.QF_V7_ONLINE_TEST.net().room||null,{timeout:10000}).then(h=>h.jsonValue());if(!room)throw new Error('online room not created');await p2.evaluate(()=>window.QF_V7_CORE.go('online'));await p2.locator('#v7OnlineCode').fill(room);await p2.locator('#v7OnlineJoin').click();await p1.waitForSelector('#v7OnlineStart',{timeout:20000});await p1.locator('#v7OnlineStart').click();await Promise.all([p1.waitForSelector('#v7OnlineQ [data-qanswer]',{timeout:12000}),p2.waitForSelector('#v7OnlineQ [data-qanswer]',{timeout:12000})]);const q=await p1.evaluate(()=>window.QF_V7_ONLINE_TEST.net().match.question);await p1.evaluate(id=>window.QF_V7_ONLINE_TEST.hostAnswer(id),q.correct);await p1.waitForFunction(()=>window.QF_V7_ONLINE_TEST.net().match.momentumHome>=18,{timeout:3000});await p1.evaluate(()=>window.QF_V7_ONLINE_TEST.forceGoal('home'));await p2.waitForFunction(()=>window.QF_V7_ONLINE_TEST.net().match?.momentumHome===0,{timeout:4000});const sync=await Promise.all([p1.evaluate(()=>window.QF_V7_ONLINE_TEST.net().match.home),p2.evaluate(()=>window.QF_V7_ONLINE_TEST.net().match.home)]);if(sync[0]!==sync[1])throw new Error('online score diverged');log('two-chairman live room + shared quiz + goal momentum reset synchronized');
 console.log('V7 E2E PASS: club onboarding, chairman budget, manager AI, transfers, simple navigation, 2-minute match, quiz goal multiplier, goal reset and two-client online club duel.');
}finally{await ctx1.close();await ctx2.close();await browser.close()}
