import fs from 'node:fs';
const audio=fs.readFileSync('audio-v8.js','utf8'),css=fs.readFileSync('audio-v8.css','utf8'),patch=fs.readFileSync('scripts/patch-v8.mjs','utf8');
let n=0;const ok=(v,m)=>{n++;if(!v)throw new Error(`V8 AUDIO QA: ${m}`)};
ok(audio.includes('AudioContext')&&audio.includes('webkitAudioContext'),'Web Audio context fallback missing');
ok(audio.includes('SpeechSynthesisUtterance')&&audio.includes('u.lang="tr-TR"'),'Turkish speech synthesis missing');
ok(audio.includes('commentary:true')&&audio.includes('effects:true')&&audio.includes('crowd:true')&&audio.includes('captions:true'),'default audio channels missing');
ok(audio.includes('function startCrowd')&&audio.includes('createBufferSource'),'procedural stadium crowd missing');
for(const fx of ['kickoff','kick','correct','wrong','miss','save','post','goal','concede','halftime','final'])ok(audio.includes(`case"${fx}"`),`${fx} sound effect missing`);
for(const group of ['kickoff','correct','wrong','miss','save','post','defense','late','half','final'])ok(new RegExp(`${group}:\\[`).test(audio),`${group} commentary phrase group missing`);
for(const event of ['goal_for','goal_against','post','save','miss','defense'])ok(audio.includes(`return"${event}"`)||audio.includes(`case"${event}"`),`${event} classifier missing`);
ok(audio.includes('priority:10,interrupt:true'),'goal commentary priority/interrupt missing');
ok(audio.includes('qf-v8-audio'),'persistent audio settings missing');
ok(audio.includes('data-audio-range="master"')&&audio.includes('data-audio-range="commentator"')&&audio.includes('data-audio-range="effectVolume"')&&audio.includes('data-audio-range="crowdVolume"'),'separate volume controls missing');
ok(audio.includes('e.key?.toLowerCase()==="m"'),'keyboard mute shortcut missing');
ok(css.includes('.qf-commentary-caption')&&css.includes('.qf-audio-panel'),'audio UI/caption styles missing');
ok(patch.includes('quizfootball-v8.0.0')&&patch.includes('audio-v8.js')&&patch.includes('audio-v8.css'),'production/cache wiring missing');
ok(patch.includes('Top direkten döndü')&&patch.includes('Kaleci çok kritik bir kurtarış'),'solo rich miss events missing');
ok(patch.includes('direğe takıldı')&&patch.includes('şutunda kaleci kurtardı'),'online rich miss events missing');
console.log(`V8 AUDIO QA PASS: ${n} assertions; Turkish commentator, procedural SFX, crowd ambience, captions, controls and rich shot outcomes.`);