import fs from 'node:fs/promises';
const path='app-v5.js';let s=await fs.readFile(path,'utf8');let changed=0;
const oldChange='function changeSetting(){if(!isHost)return;const id=U.modeSelect.value;if(id!==S.settings.modeId){const max=+U.maxPlayers.value||8;S.settings={...settingsFor(id),maxPlayers:max}}S.settings.optionCount=[4,6,8].includes(+U.choiceSelect.value)?+U.choiceSelect.value:S.settings.optionCount;S.settings.maxPlayers=Math.max(2,Math.min(8,+U.maxPlayers.value||8));S.settings.content=["player","manager","mixed"].includes(U.contentSelect.value)?U.contentSelect.value:S.settings.content;sync()}';
const newChange='function changeSetting(e){if(!isHost)return;const id=U.modeSelect.value;if(id!==S.settings.modeId){const max=+U.maxPlayers.value||8;S.settings={...settingsFor(id),maxPlayers:max};U.choiceSelect.value=String(S.settings.optionCount);U.contentSelect.value=S.settings.content}else{S.settings.optionCount=[4,6,8].includes(+U.choiceSelect.value)?+U.choiceSelect.value:S.settings.optionCount;S.settings.content=["player","manager","mixed"].includes(U.contentSelect.value)?U.contentSelect.value:S.settings.content}S.settings.maxPlayers=Math.max(2,Math.min(8,+U.maxPlayers.value||8));sync()}';
if(s.includes(oldChange)){s=s.replace(oldChange,newChange);changed++}
const oldDeck='function makeDeck(content){const p=shuf(D.cards).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out}';
const newDeck='function makeDeck(content){const poolId=mode().pool,allowed=poolId&&V.pools?.[poolId]?new Set(V.pools[poolId]):null;const allow=c=>!allowed||(allowed.has(c.teamA)&&allowed.has(c.teamB));const p=shuf(D.cards.filter(allow)).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards.filter(allow)).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out.length?out:[...p,...m]}';
if(s.includes(oldDeck)){s=s.replace(oldDeck,newDeck);changed++}
const hook='if(location.hostname==="127.0.0.1"||location.hostname==="localhost")window.QFTest={getState:()=>structuredClone(snap()),setEndsIn:ms=>{if(isHost&&S.status==="playing"){S.endsAt=Date.now()+Math.max(50,+ms||50);sync()}},finish:()=>isHost&&finishMatch("qa"),profile:()=>({...profile})};\nwire();';
if(!s.includes('window.QFTest=')){s=s.replace('wire();\n})();',hook+'\n})();');changed++}
await fs.writeFile(path,s);
let html=await fs.readFile('index.html','utf8');if(!html.includes('data-v5-plus.js')){html=html.replace('<script src="manager-images-v5.js?v=500"></script>','<script src="manager-images-v5.js?v=500"></script>\n  <script src="data-v5-plus.js?v=520"></script>');await fs.writeFile('index.html',html);changed++}
console.log(`V5 patches applied: ${changed}`);
if(!s.includes('function changeSetting(e)'))throw new Error('mode-setting patch missing');
if(!s.includes('V.pools?.[poolId]'))throw new Error('mode-pool filter patch missing');
if(!s.includes('window.QFTest='))throw new Error('QA hook missing');
if(!html.includes('data-v5-plus.js?v=520'))throw new Error('advanced modes package not wired');
