import fs from 'node:fs/promises';
const path='app-v5.js';let s=await fs.readFile(path,'utf8');let changed=0;
const oldChange='function changeSetting(){if(!isHost)return;const id=U.modeSelect.value;if(id!==S.settings.modeId){const max=+U.maxPlayers.value||8;S.settings={...settingsFor(id),maxPlayers:max}}S.settings.optionCount=[4,6,8].includes(+U.choiceSelect.value)?+U.choiceSelect.value:S.settings.optionCount;S.settings.maxPlayers=Math.max(2,Math.min(8,+U.maxPlayers.value||8));S.settings.content=["player","manager","mixed"].includes(U.contentSelect.value)?U.contentSelect.value:S.settings.content;sync()}';
const newChange='function changeSetting(e){if(!isHost)return;const id=U.modeSelect.value;if(id!==S.settings.modeId){const max=+U.maxPlayers.value||8;S.settings={...settingsFor(id),maxPlayers:max};U.choiceSelect.value=String(S.settings.optionCount);U.contentSelect.value=S.settings.content}else{S.settings.optionCount=[4,6,8].includes(+U.choiceSelect.value)?+U.choiceSelect.value:S.settings.optionCount;S.settings.content=["player","manager","mixed"].includes(U.contentSelect.value)?U.contentSelect.value:S.settings.content}S.settings.maxPlayers=Math.max(2,Math.min(8,+U.maxPlayers.value||8));sync()}';
if(s.includes(oldChange)){s=s.replace(oldChange,newChange);changed++}
const plainDeck='function makeDeck(content){const p=shuf(D.cards).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out}';
const poolDeck='function makeDeck(content){const poolId=mode().pool,allowed=poolId&&V.pools?.[poolId]?new Set(V.pools[poolId]):null;const allow=c=>!allowed||(allowed.has(c.teamA)&&allowed.has(c.teamB));const p=shuf(D.cards.filter(allow)).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards.filter(allow)).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out.length?out:[...p,...m]}';
const advancedDeck='function makeDeck(content){const cfg=mode(),poolId=cfg.pool,allowed=poolId&&V.pools?.[poolId]?new Set(V.pools[poolId]):null,rand=cfg.daily?rng(new Date().toISOString().slice(0,10)+":"+cfg.id):Math.random;const allow=c=>!allowed||(allowed.has(c.teamA)&&allowed.has(c.teamB));const p=shuf(D.cards.filter(allow),rand).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards.filter(allow),rand).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out.length?out:[...p,...m]}';
if(s.includes(plainDeck)){s=s.replace(plainDeck,advancedDeck);changed++}else if(s.includes(poolDeck)){s=s.replace(poolDeck,advancedDeck);changed++}
const oldChoose='function choose(pid,opt,rid){if(!isHost||S.status!=="playing"||S.locked||S.currentRound?.id!==rid||S.selections[pid]||!S.options.includes(opt))return;const p=S.players[pid];if(!p||p.active===false||p.spectator||p.eliminated)return;const good=opt===S.correctAnswerId,ms=Math.max(0,Date.now()-S.roundStartedAt);S.selections[pid]={optionId:opt,correct:good,ms};if(good){p.correct++;p.streak++;p.bestStreak=Math.max(p.bestStreak,p.streak);p.fastest=p.fastest?Math.min(p.fastest,ms):ms;if(S.currentRound.kind==="manager")p.managerCorrect++;if(S.settings.rule==="team"){p.score++;S.teamScores[p.team]=(S.teamScores[p.team]||0)+1}else if(S.settings.rule==="coop"){p.score++;S.teamScores.coop++}else p.score++;S.locked=true;S.winnerId=pid;broadcast("result",{good:true,winnerId:pid});sync();okSound();return setTimeout(nextRound,S.settings.chill?1050:650)}p.wrong++;p.streak=0;if(S.settings.rule==="survival")p.eliminated=true;broadcast("result",{good:false,winnerId:null});wrongSound();if(S.settings.rule==="solo"||competitors().length===1){S.locked=true;sync();return setTimeout(nextRound,850)}sync();if(S.settings.rule==="survival"&&eligible().length<=1)return setTimeout(()=>finishMatch("survival"),700);checkSpent()}';
const newChoose='function choose(pid,opt,rid){if(!isHost||S.status!=="playing"||S.locked||S.currentRound?.id!==rid||S.selections[pid]||!S.options.includes(opt))return;const p=S.players[pid];if(!p||p.active===false||p.spectator||p.eliminated)return;const cfg=mode(),good=opt===S.correctAnswerId,ms=Math.max(0,Date.now()-S.roundStartedAt);S.selections[pid]={optionId:opt,correct:good,ms};if(good){p.correct++;p.streak++;p.bestStreak=Math.max(p.bestStreak,p.streak);p.fastest=p.fastest?Math.min(p.fastest,ms):ms;if(S.currentRound.kind==="manager")p.managerCorrect++;const pts=cfg.scoring==="streak"?1+Math.min(2,Math.floor((p.streak-1)/3)):1;if(S.settings.rule==="team"){p.score+=pts;S.teamScores[p.team]=(S.teamScores[p.team]||0)+pts}else if(S.settings.rule==="coop"){p.score+=pts;S.teamScores.coop+=pts}else p.score+=pts;S.locked=true;S.winnerId=pid;broadcast("result",{good:true,winnerId:pid,points:pts});sync();okSound();const target=+cfg.targetScore||0,hit=target&&(S.settings.rule==="team"?S.teamScores[p.team]>=target:S.settings.rule==="coop"?S.teamScores.coop>=target:p.score>=target);if(hit)return setTimeout(()=>finishMatch("target"),S.settings.chill?900:550);return setTimeout(nextRound,S.settings.chill?1050:650)}p.wrong++;p.streak=0;if(S.settings.rule==="survival")p.eliminated=true;broadcast("result",{good:false,winnerId:null});wrongSound();if(S.settings.rule==="solo"||competitors().length===1){S.locked=true;sync();return setTimeout(nextRound,850)}sync();if(S.settings.rule==="survival"&&eligible().length<=1)return setTimeout(()=>finishMatch("survival"),700);checkSpent()}';
if(s.includes(oldChoose)){s=s.replace(oldChoose,newChoose);changed++}
const oldRule='function ruleHtml(m){const arr=[m.rated?"Global rating bu maçtan etkilenir.":"Bu mod rating kaybettirmez.",m.timeLimit?`Maç ${Math.round(m.timeLimit/60)} dakika sonunda kart sayısından bağımsız biter.`:`Maç ${m.roundCount} kart sonunda biter.`,m.rule==="survival"?"Yanlış seçim oyuncuyu eler.":m.rule==="team"?"İlk doğru cevap takım puanını artırır.":m.rule==="coop"?"Herkes ortak hedef için oynar.":"Competitive akışta ilk doğru cevap turu kazanır."];return arr.map((x,i)=>`<div class="rule-row"><i>${["◈","⏱","⚡"][i]}</i><span>${esc(x)}</span></div>`).join("")}';
const newRule='function ruleHtml(m){const end=m.targetScore?`${m.targetScore} puana ilk ulaşan taraf maçı anında bitirir.`:m.timeLimit?`Maç ${Math.round(m.timeLimit/60)} dakika sonunda kart sayısından bağımsız biter.`:`Maç ${m.roundCount} kart sonunda biter.`,score=m.scoring==="streak"?"Seri uzadıkça doğru cevap 2–3 puana kadar çıkar.":m.rule==="survival"?"Yanlış seçim oyuncuyu eler.":m.rule==="team"?"İlk doğru cevap takım puanını artırır.":m.rule==="coop"?"Herkes ortak hedef için oynar.":"Competitive akışta ilk doğru cevap turu kazanır.";const arr=[m.rated?"Global rating bu maçtan etkilenir.":"Bu mod rating kaybettirmez.",end,score];return arr.map((x,i)=>`<div class="rule-row"><i>${["◈","⏱","⚡"][i]}</i><span>${esc(x)}</span></div>`).join("")}';
if(s.includes(oldRule)){s=s.replace(oldRule,newRule);changed++}
const hook='if(location.hostname==="127.0.0.1"||location.hostname==="localhost")window.QFTest={getState:()=>structuredClone(snap()),setEndsIn:ms=>{if(isHost&&S.status==="playing"){S.endsAt=Date.now()+Math.max(50,+ms||50);sync()}},finish:()=>isHost&&finishMatch("qa"),profile:()=>({...profile})};\nwire();';
if(!s.includes('window.QFTest=')){s=s.replace('wire();\n})();',hook+'\n})();');changed++}
await fs.writeFile(path,s);
let html=await fs.readFile('index.html','utf8');if(!html.includes('data-v5-plus.js')){html=html.replace('<script src="manager-images-v5.js?v=500"></script>','<script src="manager-images-v5.js?v=500"></script>\n  <script src="data-v5-plus.js?v=520"></script>');changed++}if(!html.includes('data-v5-arcade.js')){html=html.replace('<script src="data-v5-plus.js?v=520"></script>','<script src="data-v5-plus.js?v=520"></script>\n  <script src="data-v5-arcade.js?v=530"></script>');changed++}await fs.writeFile('index.html',html);
console.log(`V5 patches applied: ${changed}`);
if(!s.includes('function changeSetting(e)'))throw new Error('mode-setting patch missing');
if(!s.includes('cfg.daily?rng'))throw new Error('daily deterministic deck patch missing');
if(!s.includes('cfg.scoring==="streak"'))throw new Error('streak scoring patch missing');
if(!s.includes('finishMatch("target")'))throw new Error('target-score finish patch missing');
if(!s.includes('window.QFTest='))throw new Error('QA hook missing');
if(!html.includes('data-v5-plus.js?v=520')||!html.includes('data-v5-arcade.js?v=530'))throw new Error('advanced mode packages not wired');
