import fs from 'node:fs/promises';
const path='app-v5.js';let s=await fs.readFile(path,'utf8');let changed=0;
const oldChange='function changeSetting(){if(!isHost)return;const id=U.modeSelect.value;if(id!==S.settings.modeId){const max=+U.maxPlayers.value||8;S.settings={...settingsFor(id),maxPlayers:max}}S.settings.optionCount=[4,6,8].includes(+U.choiceSelect.value)?+U.choiceSelect.value:S.settings.optionCount;S.settings.maxPlayers=Math.max(2,Math.min(8,+U.maxPlayers.value||8));S.settings.content=["player","manager","mixed"].includes(U.contentSelect.value)?U.contentSelect.value:S.settings.content;sync()}';
const newChange='function changeSetting(e){if(!isHost)return;const id=U.modeSelect.value;if(id!==S.settings.modeId){const max=+U.maxPlayers.value||8;S.settings={...settingsFor(id),maxPlayers:max};U.choiceSelect.value=String(S.settings.optionCount);U.contentSelect.value=S.settings.content}else{S.settings.optionCount=[4,6,8].includes(+U.choiceSelect.value)?+U.choiceSelect.value:S.settings.optionCount;S.settings.content=["player","manager","mixed"].includes(U.contentSelect.value)?U.contentSelect.value:S.settings.content}S.settings.maxPlayers=Math.max(2,Math.min(8,+U.maxPlayers.value||8));sync()}';if(s.includes(oldChange)){s=s.replace(oldChange,newChange);changed++}
const oldSave='function saveName(){const n=cleanName(U.profileNameInput.value);if(n.length<2)return toast("Kullanıcı adı en az 2 karakter olsun");profile.username=n;saveProfileLocal();U.profileSetup.classList.add("saved");window.QFCloud?.ensureProfile?.({profile_key:profile.profileKey,username:n,rating:profile.rating,xp:profile.xp,level:profile.level,games:profile.games,wins:profile.wins,losses:profile.losses,draws:profile.draws,correct:profile.correct,wrong:profile.wrong,best_streak:profile.bestStreak,timed_best:profile.timedBest,solo_best:profile.soloBest,ranked_wins:profile.rankedWins,chill_games:profile.chillGames,manager_correct:profile.managerCorrect,badges:profile.badges});toast("Profil kaydedildi")}';const newSave='function saveName(){const n=cleanName(U.profileNameInput.value);if(n.length<2)return toast("Kullanıcı adı en az 2 karakter olsun");if((location.hostname==="127.0.0.1"||location.hostname==="localhost")&&/QA$/i.test(n))profile.profileKey="qa-"+n.toLowerCase();profile.username=n;saveProfileLocal();U.profileSetup.classList.add("saved");window.QFCloud?.ensureProfile?.({profile_key:profile.profileKey,username:n,rating:profile.rating,xp:profile.xp,level:profile.level,games:profile.games,wins:profile.wins,losses:profile.losses,draws:profile.draws,correct:profile.correct,wrong:profile.wrong,best_streak:profile.bestStreak,timed_best:profile.timedBest,solo_best:profile.soloBest,ranked_wins:profile.rankedWins,chill_games:profile.chillGames,manager_correct:profile.managerCorrect,badges:profile.badges});toast("Profil kaydedildi")}';if(s.includes(oldSave)){s=s.replace(oldSave,newSave);changed++}
const plainDeck='function makeDeck(content){const p=shuf(D.cards).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out}';
const poolDeck='function makeDeck(content){const poolId=mode().pool,allowed=poolId&&V.pools?.[poolId]?new Set(V.pools[poolId]):null;const allow=c=>!allowed||(allowed.has(c.teamA)&&allowed.has(c.teamB));const p=shuf(D.cards.filter(allow)).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards.filter(allow)).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out.length?out:[...p,...m]}';
const advancedDeck='function makeDeck(content){const cfg=mode(),poolId=cfg.pool,allowed=poolId&&V.pools?.[poolId]?new Set(V.pools[poolId]):null,rand=cfg.daily?rng(new Date().toISOString().slice(0,10)+":"+cfg.id):Math.random;const allow=c=>!allowed||(allowed.has(c.teamA)&&allowed.has(c.teamB));const p=shuf(D.cards.filter(allow),rand).map(c=>({kind:"player",id:c.id})),m=shuf(managerCards.filter(allow),rand).map(c=>({kind:"manager",id:c.id}));if(content==="player")return p;if(content==="manager")return m;const out=[];let pi=0,mi=0;while(pi<p.length||mi<m.length){if(pi<p.length)out.push(p[pi++]);if(pi<p.length)out.push(p[pi++]);if(mi<m.length)out.push(m[mi++])}return out.length?out:[...p,...m]}';if(s.includes(plainDeck)){s=s.replace(plainDeck,advancedDeck);changed++}else if(s.includes(poolDeck)){s=s.replace(poolDeck,advancedDeck);changed++}
if(s.includes('history.replaceState({},"",location.pathname)')){s=s.replaceAll('history.replaceState({},"",location.pathname)','window.history.replaceState({},"",location.pathname)');changed++}
await fs.writeFile(path,s);
let html=await fs.readFile('index.html','utf8');if(!html.includes('data-v5-plus.js')){html=html.replace('<script src="manager-images-v5.js?v=500"></script>','<script src="manager-images-v5.js?v=500"></script>\n  <script src="data-v5-plus.js?v=520"></script>');changed++}if(!html.includes('data-v5-arcade.js')){html=html.replace('<script src="data-v5-plus.js?v=520"></script>','<script src="data-v5-plus.js?v=520"></script>\n  <script src="data-v5-arcade.js?v=530"></script>');changed++}await fs.writeFile('index.html',html);
console.log(`V5 patches applied: ${changed}`);
if(!s.includes('function changeSetting(e)'))throw new Error('mode-setting patch missing');
if(!s.includes('cfg.daily?rng'))throw new Error('daily deterministic deck patch missing');
if(!(s.includes('cfg.scoring==="streak"')||s.includes('scoring=S.settings.scoring||cfg.scoring')))throw new Error('streak scoring patch missing');
if(!s.includes('finishMatch("target")'))throw new Error('target-score finish patch missing');
if(!s.includes('setMyScore:v=>')||!s.includes('chooseCorrect:()=>'))throw new Error('advanced QA hook missing');
if(!s.includes('window.history.replaceState'))throw new Error('safe browser history navigation patch missing');
if(!html.includes('data-v5-plus.js?v=520')||!html.includes('data-v5-arcade.js?v=530'))throw new Error('advanced mode packages not wired');
